// ============================================================================
// ACTOR_PHOTOS — photo (visage, hors costume) pour chaque acteur/actrice
// listé dans un casting, indexée par nom exact (tel qu'écrit dans cast[]
// dans data.js, sans la parenthèse éventuelle type "(narrateur)").
// 239/239 acteurs couverts (Wikipédia en priorité, TMDB en complément).
// ============================================================================

const ACTOR_PHOTOS = {
  'Aaron Taylor-Johnson': 'images/actors/aaron-taylor-johnson.jpg',
  'Adria Arjona': 'images/actors/adria-arjona.jpg',
  'Alan Cumming': 'images/actors/alan-cumming.jpg',
  'Alaqua Cox': 'images/actors/alaqua-cox.jpg',
  'Alden Ehrenreich': 'images/actors/alden-ehrenreich.jpg',
  'Alfre Woodard': 'images/actors/alfre-woodard.jpg',
  'Alfred Molina': 'images/actors/alfred-molina.jpg',
  'Alison Sealy-Smith': 'images/actors/alison-sealy-smith.jpg',
  'Amber Rose Revah': 'images/actors/amber-rose-revah.jpg',
  'Amy Rutberg': 'images/actors/amy-rutberg.jpg',
  'Andrew Garfield': 'images/actors/andrew-garfield.jpg',
  'Angelina Jolie': 'images/actors/angelina-jolie.jpg',
  'Anthony Hopkins': 'images/actors/anthony-hopkins.jpg',
  'Anthony Mackie': 'images/actors/anthony-mackie.jpg',
  'Anthony Ramos': 'images/actors/anthony-ramos.jpg',
  'Anya Taylor-Joy': 'images/actors/anya-taylor-joy.jpg',
  'Ariana DeBose': 'images/actors/ariana-debose.jpg',
  'Aubrey Plaza': 'images/actors/aubrey-plaza.jpg',
  'Awkwafina': 'images/actors/awkwafina.jpg',
  'Ayelet Zurer': 'images/actors/ayelet-zurer.png',
  'Ben Affleck': 'images/actors/ben-affleck.jpg',
  'Ben Barnes': 'images/actors/ben-barnes.jpg',
  'Ben Kingsley': 'images/actors/ben-kingsley.jpg',
  'Ben Mendelsohn': 'images/actors/ben-mendelsohn.jpg',
  'Benedict Cumberbatch': 'images/actors/benedict-cumberbatch.jpg',
  'Bradley Cooper': 'images/actors/bradley-cooper.jpg',
  'Brie Larson': 'images/actors/brie-larson.jpg',
  'Cal Dodd': 'images/actors/cal-dodd.jpg',
  'Cate Blanchett': 'images/actors/cate-blanchett.jpg',
  'Chadwick Boseman': 'images/actors/chadwick-boseman.jpg',
  'Charlie Cox': 'images/actors/charlie-cox.jpg',
  'Charlie Heaton': 'images/actors/charlie-heaton.png',
  'Chaske Spencer': 'images/actors/chaske-spencer.jpg',
  'Chiwetel Ejiofor': 'images/actors/chiwetel-ejiofor.jpg',
  'Chris Evans': 'images/actors/chris-evans.jpg',
  'Chris Hemsworth': 'images/actors/chris-hemsworth.jpg',
  'Chris Pratt': 'images/actors/chris-pratt.jpg',
  'Christian Bale': 'images/actors/christian-bale.jpg',
  'Clark Gregg': 'images/actors/clark-gregg.jpg',
  'Colin Farrell': 'images/actors/colin-farrell.jpg',
  'Corey Stoll': 'images/actors/corey-stoll.jpg',
  'Dafne Keen': 'images/actors/dafne-keen.jpg',
  'Dakota Johnson': 'images/actors/dakota-johnson.jpg',
  'Danai Gurira': 'images/actors/danai-gurira.jpg',
  'Dane DeHaan': 'images/actors/dane-dehaan.png',
  'Danny Ramirez': 'images/actors/danny-ramirez.jpg',
  'Dave Bautista': 'images/actors/dave-bautista.jpg',
  'David Harbour': 'images/actors/david-harbour.jpg',
  'David Tennant': 'images/actors/david-tennant.jpg',
  'Deborah Ann Woll': 'images/actors/deborah-ann-woll.jpg',
  'Dominic Cooper': 'images/actors/dominic-cooper.jpg',
  'Dominic West': 'images/actors/dominic-west.jpg',
  'Dominique Thorne': 'images/actors/dominique-thorne.jpg',
  'Don Cheadle': 'images/actors/don-cheadle.jpg',
  'Doug Hutchison': 'images/actors/doug-hutchison.jpg',
  'Doug Jones': 'images/actors/doug-jones.jpg',
  'Ebon Moss-Bachrach': 'images/actors/ebon-moss-bachrach.jpg',
  'Ed Skrein': 'images/actors/ed-skrein.jpg',
  'Edward Norton': 'images/actors/edward-norton.jpg',
  'Elden Henson': 'images/actors/elden-henson.jpg',
  'Elizabeth Olsen': 'images/actors/elizabeth-olsen.png',
  'Emily Hampshire': 'images/actors/emily-hampshire.jpg',
  'Emma Corrin': 'images/actors/emma-corrin.jpg',
  'Emma Stone': 'images/actors/emma-stone.jpg',
  'Ethan Hawke': 'images/actors/ethan-hawke.jpg',
  'Eugene Byrd': 'images/actors/eugene-byrd.jpg',
  'Eva Mendes': 'images/actors/eva-mendes.jpg',
  'Evangeline Lilly': 'images/actors/evangeline-lilly.jpg',
  'Famke Janssen': 'images/actors/famke-janssen.jpg',
  'Finn Jones': 'images/actors/finn-jones.jpg',
  'Florence Pugh': 'images/actors/florence-pugh.jpg',
  'Gael García Bernal': 'images/actors/gael-garcía-bernal.jpg',
  'Gemma Chan': 'images/actors/gemma-chan.jpg',
  'George Buza': 'images/actors/george-buza.jpg',
  'Goran Višnjić': 'images/actors/goran-višnjić.jpg',
  'Grace Song': 'images/actors/grace-song.jpg',
  'Guy Pearce': 'images/actors/guy-pearce.jpg',
  'Gwyneth Paltrow': 'images/actors/gwyneth-paltrow.jpg',
  'Hailee Steinfeld': 'images/actors/hailee-steinfeld.jpg',
  'Halle Berry': 'images/actors/halle-berry.jpg',
  'Harriet Sansom Harris': 'images/actors/harriet-sansom-harris.jpg',
  'Harrison Ford': 'images/actors/harrison-ford.jpg',
  'Hayley Atwell': 'images/actors/hayley-atwell.jpg',
  'Hudson Thames': 'images/actors/hudson-thames.jpg',
  'Hugh Dancy': 'images/actors/hugh-dancy.jpg',
  'Hugh Jackman': 'images/actors/hugh-jackman.jpg',
  'Hugo Weaving': 'images/actors/hugo-weaving.jpg',
  'Ian McKellen': 'images/actors/ian-mckellen.jpg',
  'Idris Elba': 'images/actors/idris-elba.jpg',
  'Iman Vellani': 'images/actors/iman-vellani.png',
  'Ioan Gruffudd': 'images/actors/ioan-gruffudd.jpg',
  'Isabela Merced': 'images/actors/isabela-merced.jpg',
  'Issa Rae': 'images/actors/issa-rae.jpg',
  'Jacob Batalon': 'images/actors/jacob-batalon.jpg',
  'Jake Gyllenhaal': 'images/actors/jake-gyllenhaal.jpg',
  'Jake Johnson': 'images/actors/jake-johnson.jpg',
  'James D\'Arcy': 'images/actors/james-d-arcy.jpg',
  'James McAvoy': 'images/actors/james-mcavoy.jpg',
  'James Spader': 'images/actors/james-spader.jpg',
  'Jamie Bell': 'images/actors/jamie-bell.jpg',
  'Jamie Foxx': 'images/actors/jamie-foxx.jpg',
  'Janet McTeer': 'images/actors/janet-mcteer.jpg',
  'Jared Leto': 'images/actors/jared-leto.jpg',
  'Jeff Bridges': 'images/actors/jeff-bridges.jpg',
  'Jeffrey Wright': 'images/actors/jeffrey-wright.jpg',
  'Jennifer Garner': 'images/actors/jennifer-garner.jpg',
  'Jennifer Hale': 'images/actors/jennifer-hale.jpg',
  'Jennifer Lawrence': 'images/actors/jennifer-lawrence.png',
  'Jeremy Bobb': 'images/actors/jeremy-bobb.jpg',
  'Jeremy Renner': 'images/actors/jeremy-renner.jpg',
  'Jesse Bradford': 'images/actors/jesse-bradford.jpg',
  'Jessica Alba': 'images/actors/jessica-alba.jpg',
  'Jessica Biel': 'images/actors/jessica-biel.jpg',
  'Jessica Henwick': 'images/actors/jessica-henwick.png',
  'Jessica Stroup': 'images/actors/jessica-stroup.jpg',
  'Joe Locke': 'images/actors/joe-locke.jpg',
  'John Travolta': 'images/actors/john-travolta.jpg',
  'Jon Bernthal': 'images/actors/jon-bernthal.jpg',
  'Jonathan Majors': 'images/actors/jonathan-majors.jpg',
  'Joseph Quinn': 'images/actors/joseph-quinn.jpg',
  'Josh Brolin': 'images/actors/josh-brolin.jpg',
  'Josh Stewart': 'images/actors/josh-stewart.jpg',
  'Julia Louis-Dreyfus': 'images/actors/julia-louis-dreyfus.jpg',
  'Juno Temple': 'images/actors/juno-temple.jpg',
  'Karen Gillan': 'images/actors/karen-gillan.jpg',
  'Kate Mara': 'images/actors/kate-mara.jpg',
  'Kathryn Hahn': 'images/actors/kathryn-hahn.png',
  'Kevin Bacon': 'images/actors/kevin-bacon.jpg',
  'Kingsley Ben-Adir': 'images/actors/kingsley-ben-adir.jpg',
  'Kirsten Dunst': 'images/actors/kirsten-dunst.jpg',
  'Kirsten Prout': 'images/actors/kirsten-prout.jpg',
  'Kris Kristofferson': 'images/actors/kris-kristofferson.jpg',
  'Krysten Ritter': 'images/actors/krysten-ritter.jpg',
  'Kurt Russell': 'images/actors/kurt-russell.jpg',
  'Laura Donnelly': 'images/actors/laura-donnelly.jpg',
  'Lenore Zann': 'images/actors/lenore-zann.jpg',
  'Leonor Varela': 'images/actors/leonor-varela.jpg',
  'Letitia Wright': 'images/actors/letitia-wright.jpg',
  'Liev Schreiber': 'images/actors/liev-schreiber.jpg',
  'Liv Tyler': 'images/actors/liv-tyler.jpg',
  'Lizzy Caplan': 'images/actors/lizzy-caplan.jpg',
  'Lupita Nyong\'o': 'images/actors/lupita-nyong-o.jpg',
  'Mahershala Ali': 'images/actors/mahershala-ali.jpg',
  'Maisie Williams': 'images/actors/maisie-williams.jpg',
  'Manny Montana': 'images/actors/manny-montana.jpg',
  'Marisa Tomei': 'images/actors/marisa-tomei.jpg',
  'Mark Ruffalo': 'images/actors/mark-ruffalo.jpg',
  'Matt Lintz': 'images/actors/matt-lintz.jpg',
  'Matt Smith': 'images/actors/matt-smith.jpg',
  'Maximiliano Hernández': 'images/actors/maximiliano-hernández.jpg',
  'May Calamawy': 'images/actors/may-calamawy.jpg',
  'Michael B. Jordan': 'images/actors/michael-b--jordan.jpg',
  'Michael Chiklis': 'images/actors/michael-chiklis.jpg',
  'Michael Clarke Duncan': 'images/actors/michael-clarke-duncan.jpg',
  'Michael Douglas': 'images/actors/michael-douglas.jpg',
  'Michael Fassbender': 'images/actors/michael-fassbender.jpg',
  'Michael Keaton': 'images/actors/michael-keaton.jpg',
  'Michelle Pfeiffer': 'images/actors/michelle-pfeiffer.jpg',
  'Michelle Williams': 'images/actors/michelle-williams.jpg',
  'Michelle Yeoh': 'images/actors/michelle-yeoh.jpg',
  'Mickey Rourke': 'images/actors/mickey-rourke.jpeg',
  'Mike Colter': 'images/actors/mike-colter.jpg',
  'Miles Teller': 'images/actors/miles-teller.png',
  'Morena Baccarin': 'images/actors/morena-baccarin.jpg',
  'Mustafa Shakir': 'images/actors/mustafa-shakir.jpg',
  'N\'Bushe Wright': 'images/actors/n-bushe-wright.jpg',
  'Natalie Portman': 'images/actors/natalie-portman.jpg',
  'Nicolas Cage': 'images/actors/nicolas-cage.jpg',
  'Oscar Isaac': 'images/actors/oscar-isaac.jpg',
  'Owen Wilson': 'images/actors/owen-wilson.jpg',
  'Patrick Stewart': 'images/actors/patrick-stewart.jpg',
  'Paul Bettany': 'images/actors/paul-bettany.jpg',
  'Paul Rudd': 'images/actors/paul-rudd.jpg',
  'Pedro Pascal': 'images/actors/pedro-pascal.jpg',
  'Pom Klementieff': 'images/actors/pom-klementieff.jpg',
  'Rachael Taylor': 'images/actors/rachael-taylor.png',
  'Rachel Weisz': 'images/actors/rachel-weisz.jpg',
  'Ray Chase': 'images/actors/ray-chase.jpg',
  'Ray Stevenson': 'images/actors/ray-stevenson.jpg',
  'Rebecca Romijn': 'images/actors/rebecca-romijn.jpg',
  'Rhys Ifans': 'images/actors/rhys-ifans.jpg',
  'Richard Madden': 'images/actors/richard-madden.jpg',
  'Rila Fukushima': 'images/actors/rila-fukushima.jpg',
  'Riz Ahmed': 'images/actors/riz-ahmed.jpg',
  'Robert Downey Jr.': 'images/actors/robert-downey-jr.jpg',
  'Ron Perlman': 'images/actors/ron-perlman.jpg',
  'Russell Crowe': 'images/actors/russell-crowe.jpg',
  'Ryan Reynolds': 'images/actors/ryan-reynolds.jpg',
  'Sacha Baron Cohen': 'images/actors/sacha-baron-cohen.jpg',
  'Sadie Sink': 'images/actors/sadie-sink.jpg',
  'Salma Hayek': 'images/actors/salma-hayek.jpg',
  'Samuel L. Jackson': 'images/actors/samuel-l--jackson.jpg',
  'Scarlett Johansson': 'images/actors/scarlett-johansson.jpg',
  'Sebastian Stan': 'images/actors/sebastian-stan.jpg',
  'Shameik Moore': 'images/actors/shameik-moore.jpg',
  'Simone Missick': 'images/actors/simone-missick.jpg',
  'Simu Liu': 'images/actors/simu-liu.jpg',
  'Sophia Di Martino': 'images/actors/sophia-di-martino.jpg',
  'Sophie Turner': 'images/actors/sophie-turner.jpg',
  'Stephen Dorff': 'images/actors/stephen-dorff.jpg',
  'Sydney Sweeney': 'images/actors/sydney-sweeney.jpg',
  'Tao Okamoto': 'images/actors/tao-okamoto.jpg',
  'Tatiana Maslany': 'images/actors/tatiana-maslany.jpg',
  'Tenoch Huerta': 'images/actors/tenoch-huerta.jpg',
  'Terrence Howard': 'images/actors/terrence-howard.jpg',
  'Tessa Thompson': 'images/actors/tessa-thompson.jpg',
  'Teyonah Parris': 'images/actors/teyonah-parris.jpg',
  'Thomas Haden Church': 'images/actors/thomas-haden-church.jpg',
  'Thomas Jane': 'images/actors/thomas-jane.jpg',
  'Tilda Swinton': 'images/actors/tilda-swinton.jpg',
  'Tim Roth': 'images/actors/tim-roth.jpg',
  'Tobey Maguire': 'images/actors/tobey-maguire.jpg',
  'Tom Hardy': 'images/actors/tom-hardy.jpg',
  'Tom Hiddleston': 'images/actors/tom-hiddleston.jpg',
  'Tom Holland': 'images/actors/tom-holland.jpg',
  'Tom Pelphrey': 'images/actors/tom-pelphrey.png',
  'Tommy Lee Jones': 'images/actors/tommy-lee-jones.jpg',
  'Tony Leung': 'images/actors/tony-leung.jpg',
  'Topher Grace': 'images/actors/topher-grace.jpg',
  'Vanessa Kirby': 'images/actors/vanessa-kirby.jpg',
  'Vera Farmiga': 'images/actors/vera-farmiga.jpg',
  'Vin Diesel': 'images/actors/vin-diesel.jpg',
  'Vincent D\'Onofrio': 'images/actors/vincent-d-onofrio.jpg',
  'Violante Placido': 'images/actors/violante-placido.jpg',
  'Wes Bentley': 'images/actors/wes-bentley.jpg',
  'Wesley Snipes': 'images/actors/wesley-snipes.jpg',
  'Willem Dafoe': 'images/actors/willem-dafoe.jpg',
  'William Hurt': 'images/actors/william-hurt.jpg',
  'Wilson Bethel': 'images/actors/wilson-bethel.jpg',
  'Woody Harrelson': 'images/actors/woody-harrelson.jpg',
  'Wyatt Russell': 'images/actors/wyatt-russell.jpg',
  'Xochitl Gomez': 'images/actors/xochitl-gomez.jpg',
  'Yahya Abdul-Mateen II': 'images/actors/yahya-abdul-mateen-ii.jpg',
  'Yasmeen Fletcher': 'images/actors/yasmeen-fletcher.jpg',
  'Zazie Beetz': 'images/actors/zazie-beetz.jpg',
  'Zendaya': 'images/actors/zendaya.jpg',
  'Zeno Robinson': 'images/actors/zeno-robinson.jpg',
  'Zoe Saldana': 'images/actors/zoe-saldana.jpg',
  'Élodie Yung': 'images/actors/élodie-yung.jpg',
};
