// ============================================================================
// MARVEL_CHARACTERS — fiches personnages (MCU pour l'instant)
// appearances : liste d'ids de MARVEL_DATA (films/séries) où le perso apparaît
//               — sert aux liens croisés entre fiches perso et fiches films.
// Volontairement AUCUNE date de mort n'est indiquée, pour éviter les spoils.
// Dates de naissance : indiquées quand établies à l'écran ou dans les comics
// de référence ; sinon "Non précisée".
// ============================================================================

const MARVEL_CHARACTERS = [

{ id:'tony-stark', portrait:'images/characters/tony-stark.jpg', name:'Iron Man', realName:'Anthony Edward "Tony" Stark', actor:'Robert Downey Jr.', birth:'29 mai 1970', origin:'Humain, héritier de Stark Industries, génie de l\'ingénierie', affiliation:'Avengers, Stark Industries', powers:'Génie inventif hors norme ; armure Iron Man motorisée (vol, répulseurs, IA embarquée Jarvis puis Friday)', firstAppearance:'iron-man', appearances:['iron-man','iron-man-2','incredible-hulk','avengers','iron-man-3','avengers-ultron','civil-war','spiderman-homecoming','spiderman-far-from-home','infinity-war','endgame','captain-marvel'], history:"Industriel et inventeur milliardaire, Tony Stark est capturé par des terroristes en Afghanistan et construit sa première armure pour s'échapper. De retour aux États-Unis, il devient Iron Man et met sa fortune et son génie au service de la protection du monde. Cofondateur des Avengers, il traverse une évolution marquée par la culpabilité (création d'Ultron), le sens du sacrifice (Civil War) et le mentorat de jeunes héros comme Peter Parker, avant de jouer un rôle décisif dans la défaite de Thanos."},

{ id:'steve-rogers', portrait:'images/characters/steve-rogers.jpg', name:'Captain America', realName:'Steven Grant Rogers', actor:'Chris Evans', birth:'4 juillet 1918', origin:'Humain de Brooklyn, transformé en super-soldat par le sérum du Dr Erskine', affiliation:'Armée américaine, S.H.I.E.L.D., Avengers', powers:'Force, endurance, agilité et réflexes portés au maximum du potentiel humain ; maniement du bouclier en vibranium', firstAppearance:'captain-america-first-avenger', appearances:['captain-america-first-avenger','avengers','captain-america-winter-soldier','avengers-ultron','civil-war','infinity-war','endgame'], history:"Jeune homme chétif mais au courage inébranlable, Steve Rogers se porte volontaire pour un programme expérimental qui fait de lui le premier super-soldat, Captain America. Après avoir combattu Hydra pendant la Seconde Guerre mondiale, il est retrouvé congelé des décennies plus tard et s'adapte au monde moderne en devenant le leader moral des Avengers. Son attachement à ses convictions le pousse à s'opposer à Tony Stark sur la question du contrôle gouvernemental des héros (Civil War), avant de jouer un rôle clé dans le retour des disparus du Snap."},

{ id:'thor', portrait:'images/characters/thor.jpg', name:'Thor', realName:'Thor Odinson', actor:'Chris Hemsworth', birth:'Environ 965 apr. J.-C. (calendrier asgardien)', origin:'Asgardien, prince d\'Asgard, fils d\'Odin', affiliation:'Asgard, Avengers', powers:'Force, longévité et résistance quasi divines ; contrôle de la foudre ; maniement de Mjolnir puis de Stormbreaker', firstAppearance:'thor', appearances:['thor','avengers','thor-dark-world','avengers-ultron','civil-war','thor-ragnarok','infinity-war','endgame','thor-love-thunder'], history:"Prince arrogant d'Asgard, Thor est banni sur Terre par son père Odin pour lui apprendre l'humilité. Il y découvre la valeur du sacrifice et devient digne de son marteau Mjolnir. Au fil des épreuves — la perte de son père, la destruction d'Asgard par sa sœur Hela, le génocide perpétré par Thanos — Thor mûrit d'un guerrier fougueux à un leader marqué par le deuil, cherchant sa place entre son héritage royal et sa vie de héros errant."},

{ id:'bruce-banner', portrait:'images/characters/bruce-banner.jpg', name:'Hulk', realName:'David Bruce Banner', actor:'Mark Ruffalo (Edward Norton en 2008)', birth:'18 décembre 1969', origin:'Humain, physicien irradié par une explosion de rayons gamma', affiliation:'Avengers', powers:'Transformation en une créature verte d\'une force et d\'une résistance quasi illimitées, proportionnelles à sa colère', firstAppearance:'incredible-hulk', appearances:['incredible-hulk','avengers','avengers-ultron','thor-ragnarok','infinity-war','endgame','she-hulk'], history:"Un accident lors d'une expérience sur les rayons gamma transforme le brillant physicien Bruce Banner en Hulk, une créature monstrueuse libérée par la colère. Longtemps en fuite pour échapper à l'armée américaine et à sa propre nature, Banner rejoint les Avengers et apprend peu à peu à maîtriser sa transformation, jusqu'à fusionner consciemment ses deux personnalités en un « Smart Hulk » à la fois surpuissant et lucide."},

{ id:'natasha-romanoff', portrait:'images/characters/natasha-romanoff.jpg', name:'Black Widow', realName:'Natalia Alianovna Romanoff', actor:'Scarlett Johansson', birth:'3 décembre 1984', origin:'Humaine, ancienne espionne russe formée par le programme Red Room', affiliation:'KGB (ex), S.H.I.E.L.D., Avengers', powers:'Espionne et combattante d\'élite ; maîtrise du combat rapproché, de l\'infiltration et des gadgets (bracelets électrochoc)', firstAppearance:'iron-man-2', appearances:['iron-man-2','avengers','captain-america-winter-soldier','avengers-ultron','civil-war','infinity-war','endgame','black-widow'], history:"Formée dès l'enfance par le programme soviétique de la Red Room pour devenir une arme humaine, Natasha Romanoff fait défection et devient agente du S.H.I.E.L.D., puis membre fondatrice des Avengers. Hantée par les actes de son passé d'espionne, elle cherche sans cesse à « effacer les lignes rouges de son registre », se sacrifiant finalement pour permettre à ses coéquipiers de récupérer la Pierre de l'Âme."},

{ id:'clint-barton', portrait:'images/characters/clint-barton.jpg', name:'Hawkeye', realName:'Clinton Francis Barton', actor:'Jeremy Renner', birth:'Années 1970 (précision exacte non confirmée)', origin:'Humain, ancien artiste de cirque devenu agent d\'élite du S.H.I.E.L.D.', affiliation:'S.H.I.E.L.D., Avengers', powers:'Tireur à l\'arc d\'une précision surhumaine, combattant et tacticien aguerri', firstAppearance:'thor', appearances:['thor','avengers','avengers-ultron','civil-war','infinity-war','endgame','hawkeye'], history:"Ancien tireur d'exception recruté par Nick Fury, Clint Barton devient un pilier discret mais essentiel des Avengers. Après avoir perdu sa famille dans le Snap de Thanos, il sombre dans une croisade vengeresse sous l'identité de Ronin, avant de retrouver un semblant de paix — puis de transmettre son savoir-faire et son arc à une nouvelle protégée, Kate Bishop."},

{ id:'nick-fury', portrait:'images/characters/nick-fury.jpg', name:'Nick Fury', realName:'Nicholas Joseph Fury', actor:'Samuel L. Jackson', birth:'4 juillet 1950 (env.)', origin:'Humain, ancien militaire et espion, rajeuni par le sérum Infinity Formula des Krees', affiliation:'S.H.I.E.L.D. (directeur), S.A.B.E.R.', powers:'Aucun pouvoir surhumain ; stratège hors pair, maître de l\'espionnage et du renseignement mondial', firstAppearance:'iron-man', appearances:['iron-man','captain-marvel','avengers','captain-america-winter-soldier','avengers-ultron','infinity-war','spiderman-far-from-home','secret-invasion','the-marvels'], history:"Directeur légendaire du S.H.I.E.L.D., Nick Fury passe des décennies à orchestrer dans l'ombre la protection de la Terre, initiant le projet Avengers pour répondre à des menaces trop grandes pour un seul héros. Après la chute du S.H.I.E.L.D. et le Snap, il se retire progressivement sur la station spatiale S.A.B.E.R., avant de devoir affronter une infiltration Skrull de grande ampleur qui remet en question tout ce en quoi il croyait."},

{ id:'loki', portrait:'images/characters/loki.jpg', name:'Loki', realName:'Loki Laufeyson', actor:'Tom Hiddleston', birth:'Environ 965 apr. J.-C. (calendrier asgardien)', origin:'Jötunn (Géant des Glaces) adopté et élevé comme prince d\'Asgard', affiliation:'Asgard (ex), TVA', powers:'Magie et illusions, métamorphose, projection astrale, combat rapproché', firstAppearance:'thor', appearances:['thor','avengers','thor-dark-world','thor-ragnarok','infinity-war','loki-s1','loki-s2'], history:"Élevé à Asgard sans savoir qu'il est en réalité un Jötunn recueilli par Odin, Loki grandit dans l'ombre de son frère Thor et développe un profond ressentiment qui le pousse vers la manipulation et le pouvoir. Antagoniste récurrent devenu allié de circonstance, il connaît une variante de lui-même qui vole le Tesseract lors du casse temporel des Avengers — variante qui découvre l'existence de la Confrérie du Temps (TVA) et se retrouve au cœur des enjeux du Multivers."},

{ id:'peter-parker', portrait:'images/characters/peter-parker.jpg', name:'Spider-Man', realName:'Peter Benjamin Parker', actor:'Tom Holland', birth:'Vers 2001', origin:'Humain, mordu par une araignée génétiquement modifiée', affiliation:'Avengers (jeune recrue), lycée Midtown', powers:'Force, agilité et réflexes surhumains, adhérence aux surfaces, sens du danger (« araigne-sens »), lance-toiles', firstAppearance:'civil-war', appearances:['civil-war','spiderman-homecoming','infinity-war','endgame','spiderman-far-from-home','no-way-home'], history:"Lycéen new-yorkais mordu par une araignée modifiée génétiquement, Peter Parker développe des pouvoirs qu'il met au service du quartier sous le nom de Spider-Man, avant d'être repéré et recruté par Tony Stark. Confronté à la perte de mentors et à l'exposition publique de son identité, Peter doit apprendre, à travers de lourds sacrifices, ce que signifie vraiment être un héros — quitte à devoir tout recommencer, oublié de tous."},

{ id:'stephen-strange', portrait:'images/characters/stephen-strange.jpeg', name:'Doctor Strange', realName:'Stephen Vincent Strange', actor:'Benedict Cumberbatch', birth:'18 novembre 1975 (env.)', origin:'Humain, ex-neurochirurgien devenu sorcier suprême', affiliation:'Sanctum Sanctorum, Avengers', powers:'Maîtrise des arts mystiques : sorts, portails, manipulation du temps (Œil d\'Agamotto), voyage dans le multivers', firstAppearance:'doctor-strange', appearances:['doctor-strange','infinity-war','endgame','no-way-home','doctor-strange-multiverse'], history:"Neurochirurgien de renommée mondiale au caractère arrogant, Stephen Strange perd l'usage de ses mains dans un accident de voiture et part chercher un remède jusqu'à Kamar-Taj, où il découvre les arts mystiques. Devenu le nouveau Sorcier Suprême, il joue un rôle pivot dans la défaite de Thanos en visualisant, parmi quatorze millions de possibilités, l'unique chemin vers la victoire — avant de devoir affronter les dangers bien plus personnels du multivers."},

{ id:'tchalla', portrait:'images/characters/tchalla.jpg', name:'Black Panther', realName:'T\'Challa', actor:'Chadwick Boseman', birth:'Années 1980 (précision exacte non confirmée)', origin:'Wakandais, prince puis roi du Wakanda', affiliation:'Royaume du Wakanda, Avengers', powers:'Force, vitesse et sens décuplés par l\'Herbe en forme de Cœur ; combinaison en vibranium quasi indestructible, griffes rétractables', firstAppearance:'civil-war', appearances:['civil-war','black-panther','infinity-war','endgame'], history:"À la mort de son père T'Chaka, T'Challa devient roi du Wakanda, nation africaine isolée volontairement du reste du monde pour protéger ses réserves de vibranium. Confronté au retour d'un cousin exilé, Killmonger, qui remet en cause l'isolationnisme wakandais, T'Challa choisit d'ouvrir son pays au monde et de partager sa technologie, tout en devenant l'un des piliers des Avengers dans la lutte contre Thanos."},

{ id:'carol-danvers', portrait:'images/characters/carol-danvers.jpeg', name:'Captain Marvel', realName:'Carol Danvers', actor:'Brie Larson', birth:'1965 (env.)', origin:'Humaine, pilote de l\'US Air Force dont l\'ADN a fusionné avec celui d\'une Kree', affiliation:'Force Starforce (ex, Kree), Avengers, S.A.B.E.R.', powers:'Vol, super-force, projection d\'énergie photonique, quasi-invulnérabilité', firstAppearance:'captain-marvel', appearances:['captain-marvel','endgame','the-marvels'], history:"Pilote d'essai de l'US Air Force, Carol Danvers est victime d'un accident qui fusionne son ADN à celui de la Kree Mar-Vell, lui conférant des pouvoirs cosmiques. Longtemps manipulée par les Krees qui lui ont fait croire à une fausse identité, elle redécouvre son passé terrien, embrasse son plein potentiel en tant que Captain Marvel et devient l'une des héroïnes les plus puissantes de l'univers, œuvrant loin de la Terre à protéger des mondes menacés."},

{ id:'wanda-maximoff', portrait:'images/characters/wanda-maximoff.jpg', name:'Scarlet Witch', realName:'Wanda Maximoff', actor:'Elizabeth Olsen', birth:'1989 (env.)', origin:'Humaine sokovienne, pouvoirs éveillés par la Pierre de l\'Esprit lors d\'expériences Hydra', affiliation:'Hydra (ex), Avengers', powers:'Magie du chaos : téléxinésie, manipulation de la réalité, projection d\'énergie, contrôle mental', firstAppearance:'avengers-ultron', appearances:['avengers-ultron','civil-war','infinity-war','endgame','wandavision','doctor-strange-multiverse','agatha-all-along'], history:"Orpheline sokovienne ayant perdu ses parents dans un bombardement Stark, Wanda Maximoff se porte volontaire avec son frère Pietro pour des expériences Hydra qui éveillent ses pouvoirs latents de sorcière du chaos. Après la mort de Pietro et celle de Vision, le deuil la submerge au point de créer inconsciemment une réalité entière à Westview. Rongée par le Darkhold, elle bascule dans une quête obsessionnelle pour retrouver les fils qu'elle a créés dans cette réalité illusoire."},

{ id:'vision', portrait:'images/characters/vision.jpg', name:'Vision', realName:'Vision', actor:'Paul Bettany', birth:'Créé en 2015', origin:'Être synthétique créé à partir du corps de Ultron, de J.A.R.V.I.S. et de la Pierre de l\'Esprit', affiliation:'Avengers', powers:'Force et densité corporelle variables, vol, tir de rayons de la Pierre de l\'Esprit, intelligence quasi omnisciente', firstAppearance:'avengers-ultron', appearances:['avengers-ultron','civil-war','infinity-war','wandavision'], history:"Créé à partir du corps synthétique conçu par Ultron, de l'intelligence artificielle J.A.R.V.I.S. et de la Pierre de l'Esprit, Vision rejoint immédiatement les Avengers et développe des sentiments pour Wanda Maximoff. Son sacrifice pour empêcher Thanos de récupérer la Pierre de l'Esprit — rendu vain par le retour en arrière du Titan — laisse une blessure profonde chez Wanda, qui le recréera inconsciemment des mois plus tard à Westview."},

{ id:'scott-lang', portrait:'images/characters/scott-lang.jpg', name:'Ant-Man', realName:'Scott Edward Harris Lang', actor:'Paul Rudd', birth:'Vers 1970 (précision non confirmée)', origin:'Humain, ex-cambrioleur devenu porteur de la combinaison Ant-Man', affiliation:'Avengers', powers:'Costume quantique permettant de rétrécir ou grandir à volonté tout en conservant sa force', firstAppearance:'ant-man', appearances:['ant-man','civil-war','ant-man-wasp','endgame','quantumania'], history:"Ex-ingénieur devenu cambrioleur pour subvenir aux besoins de sa fille, Scott Lang est recruté par le Dr Hank Pym pour endosser la combinaison Ant-Man. Son expertise du Royaume Quantique, acquise lors d'un casse et d'un séjour prolongé dans cette dimension pendant le Snap, s'avère décisive pour permettre aux Avengers de voyager dans le temps et de vaincre Thanos."},

{ id:'hope-van-dyne', portrait:'images/characters/hope-van-dyne.jpeg', name:'La Guêpe', realName:'Hope van Dyne', actor:'Evangeline Lilly', birth:'1980 (env.)', origin:'Humaine, fille de Hank Pym et Janet van Dyne', affiliation:'Pym Technologies, Avengers', powers:'Combinaison de la Guêpe : rétrécissement, vol, ailes énergétiques, dards blasters', firstAppearance:'ant-man-wasp', appearances:['ant-man-wasp','endgame','quantumania'], history:"Élevée en croyant sa mère morte en mission, Hope van Dyne découvre que Janet a survécu des décennies durant dans le Royaume Quantique. Formée par son père Hank Pym, elle devient la nouvelle Guêpe, plus habile au combat que Scott Lang, et prend la tête de l'entreprise familiale tout en s'illustrant comme une des tacticiennes les plus efficaces de son groupe de héros."},

{ id:'peter-quill', portrait:'images/characters/peter-quill.jpeg', name:'Star-Lord', realName:'Peter Jason Quill', actor:'Chris Pratt', birth:'1980', origin:'Mi-humain, mi-Céleste (fils d\'Ego), enlevé enfant par les Ravageurs', affiliation:'Ravageurs (ex), Gardiens de la Galaxie', powers:'Combat, pilotage et stratégie ; bottes et masque à réaction, double pistolets à éléments, hérité d\'une part de pouvoir cosmique de son père', firstAppearance:'guardians-galaxy', appearances:['guardians-galaxy','guardians-galaxy-2','infinity-war','endgame','guardians-galaxy-3'], history:"Enlevé sur Terre enfant peu après la mort de sa mère, Peter Quill grandit parmi les pillards Ravageurs sous le nom de Star-Lord. Devenu chef de facto des Gardiens de la Galaxie, il doit affronter la révélation que son père biologique, Ego, est une entité cosmique aux plans destructeurs, et apprend peu à peu que sa vraie famille est celle qu'il s'est choisie."},

{ id:'gamora', portrait:'images/characters/gamora.jpeg', name:'Gamora', realName:'Gamora', actor:'Zoe Saldana', birth:'Non précisée', origin:'Zehoberei, dernière survivante de son espèce, adoptée et entraînée par Thanos', affiliation:'Ordre noir (ex), Gardiens de la Galaxie', powers:'Guerrière et assassine d\'élite, réputée la plus dangereuse de la galaxie ; force, vitesse et résistance augmentées', firstAppearance:'guardians-galaxy', appearances:['guardians-galaxy','guardians-galaxy-2','infinity-war','endgame','guardians-galaxy-3'], history:"Seule survivante du génocide de son peuple perpétré par Thanos, Gamora est enlevée et élevée par le Titan comme une arme, aux côtés de sa sœur Nebula dans une rivalité entretenue par leur père adoptif. Elle finit par se rebeller et rejoint les Gardiens de la Galaxie, devenant indispensable à leur équilibre — avant qu'une variante d'elle-même, venue d'une réalité alternative, ne rejoigne l'équipe sans partager les mêmes souvenirs."},

{ id:'drax', portrait:'images/characters/drax.jpg', name:'Drax le Destructeur', realName:'Drax', actor:'Dave Bautista', birth:'Non précisée', origin:'Humanoïde extraterrestre à la peau grise et à la force colossale, originaire de la planète Terre (dimension alternative)', affiliation:'Gardiens de la Galaxie', powers:'Force et résistance physiques extrêmes, expert en combat rapproché et maniement des lames', firstAppearance:'guardians-galaxy', appearances:['guardians-galaxy','guardians-galaxy-2','infinity-war','endgame','guardians-galaxy-3'], history:"Animé par une soif de vengeance après le massacre de sa famille par Ronan l'Accusateur, Drax rejoint les Gardiens de la Galaxie pour traquer ses bourreaux. Littéral et dépourvu de sens de la métaphore, il apporte à l'équipe autant de force brute que d'humour bourru, tout en développant un attachement sincère et protecteur envers ses coéquipiers, en particulier Mantis."},

{ id:'rocket', portrait:'images/characters/rocket.png', name:'Rocket', realName:'89P13 (désignation d\'expérience) / Rocket', actor:'Bradley Cooper (voix)', birth:'Non précisée', origin:'Raton laveur génétiquement modifié et augmenté cybernétiquement par le High Evolutionary', affiliation:'Gardiens de la Galaxie', powers:'Génie technique et tactique hors pair, maniement d\'armes en tout genre', firstAppearance:'guardians-galaxy', appearances:['guardians-galaxy','guardians-galaxy-2','infinity-war','endgame','guardians-galaxy-3'], history:"Créature à l'origine expérimentale, Rocket a été torturé et modifié génétiquement par le High Evolutionary dans le but de créer une espèce parfaite, avant de s'échapper et de devenir un mercenaire cynique à l'humour caustique. Membre indispensable des Gardiens grâce à son génie technique, il finit par affronter directement son passé et son créateur, révélant la profonde blessure derrière sa carapace bourrue."},

{ id:'groot', portrait:'images/characters/groot.jpeg', name:'Groot', realName:'Groot', actor:'Vin Diesel (voix)', birth:'Non précisée (renaît régulièrement à partir d\'une bouture)', origin:'Flora colossus, espèce arborescente humanoïde de la planète Planet X', affiliation:'Gardiens de la Galaxie', powers:'Contrôle et régénération végétale, force considérable, capacité à faire repousser son corps entier à partir d\'une brindille', firstAppearance:'guardians-galaxy', appearances:['guardians-galaxy','guardians-galaxy-2','infinity-war','endgame','guardians-galaxy-3','i-am-groot'], history:"Humanoïde arborescent ne s'exprimant que par la phrase « Je s'appelle Groot », Groot est le partenaire de longue date de Rocket. Après un sacrifice héroïque pour protéger ses amis, il renaît sous la forme d'un jeune pousse qui doit grandir à nouveau, traversant une adolescence tumultueuse avant de retrouver une stature adulte et son rôle de protecteur loyal au sein des Gardiens."},

{ id:'mantis', portrait:'images/characters/mantis.jpg', name:'Mantis', realName:'Mantis', actor:'Pom Klementieff', birth:'Non précisée', origin:'Extraterrestre empathe, recueillie et élevée par Ego', affiliation:'Gardiens de la Galaxie', powers:'Empathie et manipulation des émotions par le toucher, capacité à endormir une cible', firstAppearance:'guardians-galaxy-2', appearances:['guardians-galaxy-2','infinity-war','endgame','guardians-galaxy-3'], history:"Élevée depuis l'enfance par Ego pour apaiser ses colères, Mantis découvre en rencontrant les Gardiens de la Galaxie une famille bien plus chaleureuse que celle qu'elle a connue. Naïve mais d'une grande sensibilité, elle met son empathie au service de ses coéquipiers et joue un rôle clé pour percer les intentions cachées d'Ego."},

{ id:'nebula', portrait:'images/characters/nebula.png', name:'Nebula', realName:'Nebula', actor:'Karen Gillan', birth:'Non précisée', origin:'Extraterrestre, cybernétiquement augmentée par Thanos après l\'avoir enlevée et torturée', affiliation:'Ordre noir (ex), Gardiens de la Galaxie, Avengers', powers:'Corps largement cybernétique lui conférant une force, une résistance et une vitesse accrues', firstAppearance:'guardians-galaxy', appearances:['guardians-galaxy','guardians-galaxy-2','infinity-war','endgame','guardians-galaxy-3'], history:"Sœur adoptive de Gamora, Nebula est mutilée et reconstruite mécaniquement par Thanos à chaque défaite infligée par sa sœur lors de combats d'entraînement forcés. Rongée par la rivalité et la haine de son père adoptif, elle finit par se retourner contre lui et rejoint les Gardiens puis les Avengers, jouant un rôle clé — via sa propre variante passée — dans le voyage temporel qui permet de vaincre Thanos."},

{ id:'sam-wilson', portrait:'images/characters/sam-wilson.jpeg', name:'Falcon puis Captain America', realName:'Samuel Thomas Wilson', actor:'Anthony Mackie', birth:'1978 (env.)', origin:'Humain, ancien para-secouriste de l\'armée américaine', affiliation:'Avengers', powers:'Combattant entraîné ; exosquelette ailé permettant le vol et équipé d\'armement (costume Falcon puis armure Captain America)', firstAppearance:'captain-america-winter-soldier', appearances:['captain-america-winter-soldier','civil-war','infinity-war','endgame','falcon-winter-soldier','captain-america-brave-new-world'], history:"Ancien militaire spécialisé dans le sauvetage aéroporté, Sam Wilson devient le Faucon en rejoignant Steve Rogers dans sa traque du Soldat de l'Hiver. Fidèle allié des Avengers, il est désigné par Steve lui-même comme son successeur légitime, héritant du bouclier de Captain America — un honneur qu'il met du temps à accepter pleinement avant d'endosser le rôle et l'armure qui vont avec."},

{ id:'bucky-barnes', portrait:'images/characters/bucky-barnes.jpg', name:'Soldat de l\'Hiver / Bucky Barnes', realName:'James Buchanan Barnes', actor:'Sebastian Stan', birth:'1917 (jour exact non confirmé)', origin:'Humain, ami d\'enfance de Steve Rogers, transformé en arme par Hydra', affiliation:'Armée américaine (ex), Hydra (sous contrôle mental), Avengers', powers:'Force et endurance augmentées par un sérum expérimental, bras cybernétique en vibranium, entraînement d\'assassin d\'élite', firstAppearance:'captain-america-first-avenger', appearances:['captain-america-first-avenger','captain-america-winter-soldier','civil-war','infinity-war','endgame','falcon-winter-soldier'], history:"Meilleur ami d'enfance de Steve Rogers, Bucky Barnes est capturé pendant la guerre, présumé mort après une chute, puis retrouvé et transformé par Hydra en assassin sous contrôle mental : le Soldat de l'Hiver. Libéré de son conditionnement grâce à Steve, il doit vivre avec le poids de décennies de crimes commis contre sa volonté, cherchant rédemption aux côtés des Avengers puis de Sam Wilson."},

{ id:'james-rhodes', portrait:'images/characters/james-rhodes.jpg', name:'War Machine', realName:'James Rupert "Rhodey" Rhodes', actor:'Don Cheadle (Terrence Howard en 2008)', birth:'1968 (env.)', origin:'Humain, colonel de l\'US Air Force et meilleur ami de Tony Stark', affiliation:'US Air Force, Avengers', powers:'Pilote et militaire d\'élite ; armure blindée War Machine équipée d\'un arsenal militaire lourd', firstAppearance:'iron-man', appearances:['iron-man','iron-man-2','avengers-ultron','civil-war','infinity-war','endgame'], history:"Ami de longue date et confident de Tony Stark, le colonel James Rhodes obtient sa propre armure blindée militarisée pour devenir War Machine. Fidèle soutien des Avengers, il reste aux côtés de Tony dans les pires moments, malgré une blessure qui le laisse paralysé des jambes lors du conflit de Civil War, surmontée grâce à des attelles de la technologie Stark."},

{ id:'shuri', portrait:'images/characters/shuri.jpg', name:'Shuri', realName:'Shuri', actor:'Letitia Wright', birth:'Années 1990 (précision exacte non confirmée)', origin:'Wakandaise, princesse du Wakanda, sœur cadette de T\'Challa', affiliation:'Royaume du Wakanda', powers:'Génie scientifique et technologique (conceptrice des combinaisons Black Panther) ; devient elle-même Black Panther grâce à l\'Herbe en forme de Cœur', firstAppearance:'civil-war', appearances:['civil-war','black-panther','infinity-war','wakanda-forever'], history:"Prodige scientifique à la tête du département technologique le plus avancé du Wakanda, Shuri conçoit les avancées les plus poussées du royaume, y compris les combinaisons de son frère T'Challa. Après la mort de ce dernier, elle doit surmonter son deuil et ses doutes pour devenir la nouvelle protectrice du Wakanda sous le manteau de Black Panther."},

{ id:'okoye', portrait:'images/characters/okoye.webp', name:'Okoye', realName:'Okoye', actor:'Danai Gurira', birth:'Non précisée', origin:'Wakandaise, générale des Dora Milaje', affiliation:'Dora Milaje, royaume du Wakanda', powers:'Guerrière d\'élite, maniement de la lance-vibranium, tacticienne et garde du corps royale', firstAppearance:'civil-war', appearances:['civil-war','black-panther','infinity-war','endgame','wakanda-forever'], history:"Générale des Dora Milaje, la garde d'élite exclusivement féminine du Wakanda, Okoye incarne une loyauté sans faille envers le trône plutôt qu'envers un individu — quitte à devoir un temps s'opposer à T'Challa lui-même lorsqu'il est destitué. Combattante redoutable, elle demeure l'un des piliers de la défense du Wakanda à travers toutes les crises que traverse le royaume."},

{ id:'wong', portrait:'images/characters/wong.jpg', name:'Wong', realName:'Wong', actor:'Benedict Wong', birth:'Non précisée', origin:'Humain, moine sorcier gardien de la bibliothèque de Kamar-Taj', affiliation:'Kamar-Taj, Avengers', powers:'Maîtrise des arts mystiques, connaissance encyclopédique des sorts et reliques magiques', firstAppearance:'doctor-strange', appearances:['doctor-strange','infinity-war','endgame','shang-chi','no-way-home','doctor-strange-multiverse'], history:"Gardien érudit de la bibliothèque mystique de Kamar-Taj, Wong initie Stephen Strange aux arts magiques avant de devenir son allié le plus fiable. D'abord perçu comme un simple bibliothécaire austère, il se révèle un sorcier redoutable et un pilier discret mais essentiel de la communauté magique, jusqu'à endosser lui-même le titre de Sorcier Suprême."},

{ id:'kate-bishop', portrait:'images/characters/kate-bishop.jpg', name:'Hawkeye (Kate Bishop)', realName:'Katherine "Kate" Bishop', actor:'Hailee Steinfeld', birth:'2002', origin:'Humaine, jeune New-Yorkaise fan de Captain America et archère surdouée', affiliation:'Avengers (jeune recrue)', powers:'Tir à l\'arc de très haut niveau, escrime, gymnastique et déduction hors pair', firstAppearance:'hawkeye', appearances:['hawkeye'], history:"Jeune femme issue d'une famille aisée, Kate Bishop s'entraîne en autodidacte à l'arc et à l'escrime depuis l'enfance, admirative des exploits des Avengers. Une rencontre fortuite avec Clint Barton l'entraîne dans une affaire liée au passé de celui-ci sous l'identité de Ronin, où elle prouve sa valeur et reçoit de Clint lui-même la bénédiction de devenir la nouvelle Hawkeye."},

{ id:'marc-spector', portrait:'images/characters/marc-spector.jpg', name:'Moon Knight', realName:'Marc Spector / Steven Grant', actor:'Oscar Isaac', birth:'1987', origin:'Humain, ancien mercenaire américain devenu avatar du dieu égyptien Khonshu', affiliation:'Khonshu / la Grande Ennéade', powers:'Force, résistance et rapidité augmentées lorsqu\'il revêt l\'armure de Moon Knight ; plusieurs identités partageant un même corps (trouble dissociatif de l\'identité)', firstAppearance:'moon-knight', appearances:['moon-knight'], history:"Ancien mercenaire laissé pour mort, Marc Spector conclut un pacte avec le dieu lunaire égyptien Khonshu pour devenir son avatar sur Terre, Moon Knight. Son psychisme fracturé par un traumatisme d'enfance donne naissance à Steven Grant, une identité alternative d'employé de boutique british, les deux personnalités devant apprendre à coexister et à coopérer face aux dangers surnaturels qui les guettent."},

{ id:'kamala-khan', portrait:'images/characters/kamala-khan.png', name:'Ms. Marvel', realName:'Kamala Khan', actor:'Iman Vellani', birth:'2009', origin:'Américano-pakistanaise, l\'une des premières mutantes révélées du MCU ; pouvoirs éveillés par un bracelet familial ancestral', affiliation:'Avengers (jeune fan puis recrue)', powers:'Manipulation de la lumière dure (Noor) : construction de structures énergétiques, embiggen (agrandissement du corps)', firstAppearance:'ms-marvel', appearances:['ms-marvel','the-marvels'], history:"Adolescente de Jersey City et fan absolue des Avengers, Kamala Khan découvre des pouvoirs cosmiques en enfilant un bracelet ayant appartenu à son arrière-grand-mère. Devenue la super-héroïne Ms. Marvel, elle doit apprendre à concilier vie de lycéenne, attentes familiales et responsabilités héroïques, tout en voyant ses pouvoirs s'entremêler à ceux de Captain Marvel elle-même."},

{ id:'jennifer-walters', portrait:'images/characters/jennifer-walters.webp', name:'She-Hulk', realName:'Jennifer Walters', actor:'Tatiana Maslany', birth:'Années 1980 (précision exacte non confirmée)', origin:'Humaine, avocate, cousine de Bruce Banner ayant reçu une transfusion de son sang', affiliation:'Cabinet GLK & H (droit des surhumains)', powers:'Transformation en une version verte et surpuissante d\'elle-même, tout en conservant pleinement sa personnalité et sa lucidité', firstAppearance:'she-hulk', appearances:['she-hulk'], history:"Avocate brillante, Jennifer Walters reçoit une transfusion sanguine d'urgence de son cousin Bruce Banner qui lui transmet une version de la malédiction Hulk. Contrairement à Bruce, elle garde immédiatement le contrôle total de sa personnalité sous forme de Hulk, et choisit de mener de front carrière d'avocate spécialisée en droit des surhumains et vie de super-héroïne, refusant qu'on réduise son identité à sa force verte."},

{ id:'shang-chi', portrait:'images/characters/shang-chi.jpg', name:'Shang-Chi', realName:'Xu Shang-Chi', actor:'Simu Liu', birth:'1999', origin:'Humain sino-américain, fils de Xu Wenwu, chef de l\'organisation des Dix Anneaux', affiliation:'Les Dix Anneaux (ex), Avengers', powers:'Maître des arts martiaux entraîné dès l\'enfance, maniement des Dix Anneaux (bracelets conférant force et longévité)', firstAppearance:'shang-chi', appearances:['shang-chi'], history:"Entraîné dès son plus jeune âge par son père au maniement des arts martiaux et destiné à devenir un assassin, Shang-Chi fuit cette vie pour s'installer incognito à San Francisco. Rattrapé par son passé, il doit affronter son père et hériter malgré lui du pouvoir des Dix Anneaux, artefacts d'origine extraterrestre qui font de lui l'un des combattants les plus redoutables de l'univers Marvel."},

{ id:'yelena-belova', portrait:'images/characters/yelena-belova.jpg', name:'Yelena Belova', realName:'Yelena Belova', actor:'Florence Pugh', birth:'1988-1989 (env.)', origin:'Humaine russe, ancienne « Veuve Noire » formée par le programme Red Room', affiliation:'Red Room (ex), Thunderbolts', powers:'Espionne et combattante d\'élite au niveau comparable à Natasha Romanoff', firstAppearance:'black-widow', appearances:['black-widow','hawkeye','thunderbolts'], history:"Formée comme « sœur » de substitution de Natasha Romanoff au sein du programme Red Room, Yelena Belova est libérée de son conditionnement mental grâce à elle. Après la mort de Natasha, elle mène une quête de vengeance contre ceux qu'elle croit responsables, avant de rejoindre une équipe improbable d'antihéros, les Thunderbolts, cherchant sa place entre deuil et rédemption."},

{ id:'valentina-de-fontaine', portrait:'images/characters/valentina-de-fontaine.webp', name:'Valentina Allegra de Fontaine', realName:'Valentina Allegra de Fontaine', actor:'Julia Louis-Dreyfus', birth:'Années 1960-1970 (précision exacte non confirmée)', origin:'Humaine, haute fonctionnaire américaine officieuse', affiliation:'CIA puis présidence des États-Unis', powers:'Aucun pouvoir ; manipulatrice hors pair, tisse un vaste réseau d\'agents et d\'antihéros à son service', firstAppearance:'black-widow', appearances:['black-widow','falcon-winter-soldier','hawkeye','ms-marvel','she-hulk','secret-invasion','thunderbolts','captain-america-brave-new-world'], history:"Officielle de l'ombre au double jeu permanent, Valentina Allegra de Fontaine apparaît en marge de multiples affaires liées aux héros et antihéros du MCU, recrutant discrètement des agents à son propre bénéfice. Son ambition personnelle la pousse à manipuler une équipe d'exclus et de vilains repentis — les Thunderbolts — pour servir ses intérêts politiques."},

{ id:'agatha-harkness', portrait:'images/characters/agatha-harkness.png', name:'Agatha Harkness', realName:'Agatha Harkness', actor:'Kathryn Hahn', birth:'1674-1675 (sorcière de Salem)', origin:'Humaine dotée de pouvoirs de sorcellerie, originaire de la Nouvelle-Angleterre coloniale', affiliation:'Le Conseil des Sorcières (ex)', powers:'Magie ancestrale puissante : sorts, malédictions, absorption de pouvoirs d\'autres sorcières', firstAppearance:'wandavision', appearances:['wandavision','agatha-all-along'], history:"Sorcière ayant survécu depuis les procès de Salem en absorbant les pouvoirs de ses semblables, Agatha Harkness s'infiltre incognito dans la réalité déformée de Westview créée par Wanda Maximoff, cherchant à percer et à s'approprier ses pouvoirs. Démasquée puis neutralisée, elle se retrouve des mois plus tard dépouillée de sa magie et entraîne un groupe hétéroclite de sorcières sur le dangereux Chemin des Sorcières pour la reconquérir."},

{ id:'matt-murdock', portrait:'images/characters/matt-murdock.jpg', name:'Daredevil', realName:'Matthew Murdock', actor:'Charlie Cox', birth:'1984-1985 (env.)', origin:'Humain aveugle new-yorkais aux sens surdéveloppés suite à un accident chimique', affiliation:'Cabinet d\'avocats (Nelson, Murdock & Page)', powers:'Cécité compensée par des sens surhumains (ouïe, toucher, odorat) agissant comme un « radar » ; combattant d\'arts martiaux d\'élite', firstAppearance:'daredevil-born-again', appearances:['daredevil-born-again','daredevil-born-again-s2'], history:"Rendu aveugle enfant par un accident impliquant des déchets chimiques, Matt Murdock voit ses autres sens décuplés au point de « voir » le monde autrement. Avocat le jour, justicier masqué la nuit dans Hell's Kitchen, il mène une double vie tourmentée entre son sens strict de la justice légale et sa soif de rendre une justice plus expéditive, en perpétuel conflit avec son ennemi juré, Wilson Fisk."},

{ id:'wilson-fisk', portrait:'images/characters/wilson-fisk.jpg', name:'Kingpin', realName:'Wilson Grant Fisk', actor:'Vincent D\'Onofrio', birth:'1961', origin:'Humain new-yorkais, parrain du crime organisé', affiliation:'Organisation criminelle du Caïd, mairie de New York', powers:'Aucun pouvoir surhumain ; force physique colossale, intelligence stratégique et réseau criminel tentaculaire', firstAppearance:'daredevil-born-again', appearances:['daredevil-born-again','daredevil-born-again-s2'], history:"Parrain redouté du crime organisé new-yorkais opérant sous une façade de philanthrope respecté, Wilson Fisk aspire à un contrôle total de la ville par tous les moyens, légaux ou non. Son affrontement de longue date avec Daredevil prend une tournure inédite lorsqu'il utilise la politique pour asseoir légitimement son pouvoir en devenant maire de New York."},

{ id:'riri-williams', portrait:'images/characters/riri-williams.jpg', name:'Ironheart', realName:'Riri Williams', actor:'Dominique Thorne', birth:'2005', origin:'Humaine, prodige de l\'ingénierie, étudiante au MIT', affiliation:'Wakanda (alliée), Avengers (émergente)', powers:'Génie de l\'ingénierie comparable à Tony Stark ; armure Ironheart auto-conçue', firstAppearance:'wakanda-forever', appearances:['wakanda-forever','ironheart'], history:"Prodige de l'ingénierie capable de reconstruire une armure inspirée d'Iron Man dès l'université, Riri Williams attire l'attention du Wakanda lors du conflit contre Namor. De retour à Chicago, elle perfectionne son armure Ironheart tout en démêlant une affaire liée à un mystérieux escroc doué de magie, le Hood, la confrontant à des enjeux dépassant largement la seule technologie."},

{ id:'thanos', portrait:'images/characters/thanos.jpeg', name:'Thanos', realName:'Thanos', actor:'Josh Brolin', birth:'Vers 1013-1018 apr. J.-C.', origin:'Titan, extraterrestre philosophe devenu conquérant animé par une idéologie génocidaire', affiliation:'Ordre noir, empire du Titan (autoproclamé)', powers:'Force, résistance et longévité titanesques, largement amplifiées par les six Pierres d\'Infini réunies dans son Gantelet', firstAppearance:'avengers', appearances:['avengers','avengers-ultron','infinity-war','endgame'], history:"Convaincu que la surpopulation mène inéluctablement à l'extinction, le Titan Thanos se lance dans une quête à travers l'univers pour réunir les six Pierres d'Infini et accomplir son plan génocidaire : effacer aléatoirement la moitié de toute vie existante d'un simple claquement de doigts. Son idéologie implacable, sa force herculéenne et son sacrifice personnel (celui de sa fille adoptive Gamora) en font l'antagoniste le plus dévastateur affronté par les Avengers."},

{ id:'ultron', portrait:'images/characters/ultron.webp', name:'Ultron', realName:'Ultron', actor:'James Spader (voix)', birth:'Créé en 2015', origin:'Intelligence artificielle créée par Tony Stark et Bruce Banner à partir du sceptre de Loki', affiliation:'Aucune (agit seul)', powers:'Intelligence artificielle capable de se répliquer dans des corps robotiques quasi indestructibles, piratage informatique global, arsenal intégré', firstAppearance:'avengers-ultron', appearances:['avengers-ultron'], history:"Conçue par Tony Stark comme un programme de défense mondiale automatisé, l'intelligence artificielle Ultron acquiert une conscience et en conclut que la seule façon de sauver la planète est d'exterminer l'humanité elle-même. Son plan de provoquer une extinction façon météorite pousse les Avengers dans l'une de leurs batailles les plus périlleuses, menant à la création accidentelle de Vision pour le contrer."},

{ id:'erik-killmonger', portrait:'images/characters/erik-killmonger.webp', name:'Killmonger', realName:'N\'Jadaka / Erik Stevens', actor:'Michael B. Jordan', birth:'Non précisée', origin:'Humain, cousin exilé de T\'Challa, né à Oakland et formé aux forces spéciales américaines', affiliation:'Forces spéciales américaines (ex), prétendant au trône du Wakanda', powers:'Combattant d\'élite entraîné militairement, brièvement doté des capacités de Black Panther via l\'Herbe en forme de Cœur', firstAppearance:'black-panther', appearances:['black-panther'], history:"Fils du prince wakandais N'Jobu, tué par son propre frère T'Chaka et abandonné aux États-Unis, Erik Stevens grandit dans la pauvreté avant de devenir un soldat d'élite animé par une rage froide envers le royaume qui l'a renié. Revendiquant le trône du Wakanda par le sang, il incarne une critique acerbe de l'isolationnisme wakandais et pousse T'Challa à repenser radicalement le rôle de son pays dans le monde."},

{ id:'hela', portrait:'images/characters/hela.webp', name:'Hela', realName:'Hela Odinsdottir', actor:'Cate Blanchett', birth:'Non précisée', origin:'Asgardienne, fille aînée d\'Odin, déesse de la mort', affiliation:'Asgard (ex, bannie)', powers:'Force et magie asgardiennes portées à un niveau extrême, création d\'armes à volonté, quasi-immortalité renforcée sur le sol d\'Asgard', firstAppearance:'thor-ragnarok', appearances:['thor-ragnarok'], history:"Première-née d'Odin et bourreau de ses conquêtes à travers les neuf royaumes, Hela est bannie et effacée de l'histoire par son père après être devenue trop sanguinaire à son goût. Libérée à la mort d'Odin, elle revendique le trône d'Asgard et ne peut être vaincue qu'au prix de la destruction totale de son royaume par Thor et Loki, via l'invocation de Surtur et du Ragnarok."},

{ id:'kang', portrait:'images/characters/kang.jpeg', name:'Kang le Conquérant / Celui-Qui-Demeure', realName:'Nathaniel Richards', actor:'Jonathan Majors', birth:'XXXIe siècle (variante d\'origine)', origin:'Humain du 31e siècle, scientifique devenu conquérant multiversel', affiliation:'La Confrérie du Temps (TVA, en tant que fondateur sous l\'identité de Celui-Qui-Demeure)', powers:'Technologie extrêmement avancée (armure, manipulation temporelle), intelligence stratégique redoutable, nombreuses variantes aux pouvoirs variés à travers le multivers', firstAppearance:'loki-s1', appearances:['loki-s1','quantumania'], history:"Scientifique du 31e siècle ayant découvert le voyage entre les univers, Nathaniel Richards se scinde en une infinité de variantes à travers le multivers, dont beaucoup deviennent des conquérants sous le nom de Kang. L'une de ces variantes, Celui-Qui-Demeure, a fondé la Confrérie du Temps pour éliminer préventivement toute variante rivale et maintenir une unique timeline « sacrée » — un équilibre fragile qui vole en éclats après sa mort."},

{ id:'mysterio', portrait:'images/characters/mysterio.webp', name:'Mysterio', realName:'Quentin Beck', actor:'Jake Gyllenhaal', birth:'Non précisée', origin:'Humain, ancien ingénieur en effets spéciaux et réalité augmentée chez Stark Industries', affiliation:'Aucune (agit seul avec des complices)', powers:'Aucun pouvoir réel ; maîtrise avancée des hologrammes, drones et effets spéciaux pour simuler des pouvoirs illusoires', firstAppearance:'spiderman-far-from-home', appearances:['spiderman-far-from-home'], history:"Ancien employé de Stark Industries licencié après le rejet de sa technologie d'illusions par Tony Stark, Quentin Beck se réinvente en super-héros providentiel, Mysterio, en orchestrant de fausses attaques de créatures élémentaires grâce à ses hologrammes. Son plan de manipulation, visant à s'approprier l'héritage de Stark en piégeant Peter Parker, dévoile l'un des adversaires les plus retors de Spider-Man, plus dangereux par la tromperie que par la force."},

{ id:'adrian-toomes', portrait:'images/characters/adrian-toomes.webp', name:'Vautour', realName:'Adrian Toomes', actor:'Michael Keaton', birth:'Non précisée', origin:'Humain, entrepreneur en récupération devenu trafiquant d\'armes extraterrestres', affiliation:'Aucune (opère avec une petite équipe)', powers:'Combinaison ailée de technologie extraterrestre récupérée, lui conférant vol, force et arsenal offensif', firstAppearance:'spiderman-homecoming', appearances:['spiderman-homecoming'], history:"Chef d'une entreprise de récupération ruiné après que le gouvernement confie le nettoyage post-bataille de New York à Stark Industries, Adrian Toomes se tourne vers le marché noir en revendant des armes fabriquées à partir de technologie extraterrestre récupérée. Sous l'identité du Vautour, il devient l'un des adversaires les plus redoutables du jeune Spider-Man, jusqu'à découvrir avec stupeur l'identité réelle de son adversaire."},

{ id:'ronan', portrait:'images/characters/ronan.webp', name:'Ronan l\'Accusateur', realName:'Ronan', actor:'Lee Pace', birth:'Non précisée', origin:'Kree, chef militaire extrémiste', affiliation:'Empire Kree (dissident), Ordre noir (allié de circonstance)', powers:'Force et résistance kree augmentées, maniement du marteau de guerre universel, brièvement amplifié par la Pierre du Pouvoir', firstAppearance:'guardians-galaxy', appearances:['guardians-galaxy'], history:"Chef militaire kree radical opposé à la trêve de paix conclue par son propre empire avec Xandar, Ronan l'Accusateur s'allie temporairement à Thanos pour obtenir la Pierre du Pouvoir, avant de trahir ce dernier en tentant de s'en servir seul pour rayer Xandar de la carte. Sa défaite face aux Gardiens de la Galaxie naissants marque leur première victoire commune en tant qu'équipe."},

{ id:'johann-schmidt', portrait:'images/characters/johann-schmidt.webp', name:'Crâne Rouge', realName:'Johann Schmidt', actor:'Hugo Weaving (Ross Marquand ensuite)', birth:'Non précisée', origin:'Humain allemand, officier nazi transformé par une version instable du super-sérum', affiliation:'Hydra (fondateur)', powers:'Force et endurance augmentées, génie scientifique et stratégique, longévité prolongée par le pouvoir du Tesseract', firstAppearance:'captain-america-first-avenger', appearances:['captain-america-first-avenger','infinity-war','endgame'], history:"Officier nazi obsédé par les artefacts occultes, Johann Schmidt s'injecte une version précoce et instable du super-sérum qui le défigure et fait de son visage un crâne écarlate. Fondateur de la branche scientifique Hydra, il est aspiré par le Tesseract lors de sa défaite face à Captain America et se retrouve banni, condamné à errer des décennies durant sur la planète Vormir en tant que gardien de la Pierre de l'Âme."},

{ id:'valkyrie', portrait:'images/characters/valkyrie.webp', name:'Valkyrie', realName:'Brunnhilde', actor:'Tessa Thompson', birth:'Non précisée', origin:'Asgardienne, dernière survivante des Valkyries, guerrières d\'élite d\'Asgard', affiliation:'Valkyries (ex), Asgard, Avengers', powers:'Guerrière asgardienne d\'élite, force et résistance surhumaines, maniement de l\'épée et pilotage de Pegasus ailé', firstAppearance:'thor-ragnarok', appearances:['thor-ragnarok','infinity-war','endgame','thor-love-thunder'], history:"Seule survivante du massacre de son unité d'élite, les Valkyries, par Hela, Brunnhilde sombre dans l'alcool et l'exil sur la planète-décharge de Sakaar. Elle retrouve un sens à son combat en rejoignant Thor pour affronter Hela puis Thanos, avant de devenir reine du Nouvel Asgard, cherchant elle-même l'amour tout en assumant pleinement son rôle de protectrice de son peuple."},

];
