// ============================================================================
// MARVEL_DATA — base de données du site
// Chaque entrée = une fiche (film ou série).
// franchise: 'mcu' | 'xmen' | 'sony' | 'netflix' | 'classic'
// releaseOrder : ordre de sortie réel dans sa franchise
// chronoOrder  : position dans l'ORDRE DE VISIONNAGE CONSEILLÉ POUR SUIVRE
//                L'HISTOIRE (chronologie interne, pas les dates de sortie).
//                Pour le MCU, cet ordre reproduit tel quel l'ordre chronologique
//                OFFICIEL publié par Marvel/Disney+ (page "See the Complete MCU
//                Timeline on Disney+", marvel.com, mise à jour le 02/06/2026),
//                qui entrelace désormais les séries Netflix avec les films —
//                d'où franchise:'netflix' MAIS un chronoOrder sur la même
//                échelle que 'mcu'. Les 4 titres non encore placés par Disney+
//                (à venir ou animés hors continuité officielle) sont ajoutés
//                à la suite, avec une note dans FRANCHISE_NOTES.
// upcoming     : true si l'œuvre n'est pas encore sortie (au 22/08/2026)
// wikiTitle    : titre EXACT de la page Wikipédia en anglais, utilisé pour
//                aller chercher l'affiche via l'API et faire le lien externe.
//                Chaque wikiTitle de ce fichier a été vérifié individuellement
//                contre l'API Wikipédia (aucune redirection vers une page
//                d'homonymie, aucune 404).
// ============================================================================

const MARVEL_DATA = [

// ------------------------------------------------------------------ MCU ---
// Ordre 1 à 79 : reproduit l'ordre chronologique officiel Marvel/Disney+.
{ id:'eyes-of-wakanda', animated:true, poster:'images/posters/eyes-of-wakanda.jpg', title:'Eyes of Wakanda', year:2025, type:'Série', franchise:'mcu', saga:'Phase 6 (2025-2027)', releaseOrder:58, chronoOrder:1, chronoNote:"à travers l'histoire du Wakanda", director:'Todd Harris (showrunner)', cast:['Voix multiples (Marvel Animation)'], duration:'1 saison, 4 épisodes (animation)', synopsis:"Anthologie retraçant, à différentes époques de l'histoire du Wakanda, les missions de guerriers d'élite envoyés à travers le monde pour récupérer des reliques en vibranium dérobées.", wikiTitle:'Eyes of Wakanda'},
{ id:'captain-america-first-avenger', poster:'images/posters/captain-america-first-avenger.jpg', title:'Captain America: First Avenger', year:2011, type:'Film', franchise:'mcu', saga:'Phase 1 (2008-2012)', releaseOrder:5, chronoOrder:2, chronoNote:'1942-1945', director:'Joe Johnston', cast:['Chris Evans','Hayley Atwell','Sebastian Stan','Tommy Lee Jones','Hugo Weaving'], duration:'124 min', synopsis:"Retour sur les débuts de l'univers Marvel, lorsque Steve Rogers se porte volontaire pour participer à un programme expérimental qui le transforme en super-soldat sous le nom de Captain America.", wikiTitle:'Captain America: The First Avenger'},
{ id:'oneshot-agent-carter', poster:'images/posters/oneshot-agent-carter.jpg', title:'Marvel One-Shot: Agent Carter', year:2013, type:'Court-métrage', franchise:'mcu', saga:'One-Shots', releaseOrder:67, chronoOrder:3, chronoNote:'1946', director:'Louis D\'Esposito', cast:['Hayley Atwell','Dominic Cooper'], duration:'~15 min (bonus du Blu-ray Iron Man 3)', synopsis:"Reléguée à des tâches administratives par ses collègues masculins du SSR, Peggy Carter part en mission solo pour prouver sa valeur — court-métrage qui posera les bases de la série Agent Carter.", wikiTitle:'Agent Carter (film)'},
{ id:'captain-marvel', poster:'images/posters/captain-marvel.jpg', title:'Captain Marvel', year:2019, type:'Film', franchise:'mcu', saga:'Phase 3 (2016-2019)', releaseOrder:21, chronoOrder:4, chronoNote:'1995', director:'Anna Boden, Ryan Fleck', cast:['Brie Larson','Samuel L. Jackson','Ben Mendelsohn'], duration:'123 min', synopsis:"En 1995, Carol Danvers, pilote devenue guerrière kree, découvre son passé terrien et son véritable pouvoir.", wikiTitle:'Captain Marvel (film)'},
{ id:'iron-man', poster:'images/posters/iron-man.jpg', title:'Iron Man', year:2008, type:'Film', franchise:'mcu', saga:'Phase 1 (2008-2012)', releaseOrder:1, chronoOrder:5, chronoNote:'2010', director:'Jon Favreau', cast:['Robert Downey Jr.','Gwyneth Paltrow','Terrence Howard','Jeff Bridges'], duration:'126 min', synopsis:"Tony Stark, milliardaire industriel et inventeur de génie, est enlevé et forcé de construire une arme dévastatrice. Grâce à son intelligence et son ingéniosité, il construit à la place une armure high-tech et s'échappe. En découvrant un complot aux implications mondiales, il endosse sa puissante armure et fait le serment de protéger le monde sous le nom d'Iron Man.", wikiTitle:'Iron Man (2008 film)'},
{ id:'iron-man-2', poster:'images/posters/iron-man-2.jpg', title:'Iron Man 2', year:2010, type:'Film', franchise:'mcu', saga:'Phase 1 (2008-2012)', releaseOrder:3, chronoOrder:6, chronoNote:'2011', director:'Jon Favreau', cast:['Robert Downey Jr.','Gwyneth Paltrow','Don Cheadle','Scarlett Johansson','Mickey Rourke'], duration:'124 min', synopsis:"Le monde sait désormais que Tony Stark est Iron Man, et le milliardaire inventeur subit une pression croissante pour partager sa technologie avec l'armée. Réticent à en dévoiler les secrets par peur qu'ils tombent entre de mauvaises mains, il doit, aux côtés de Pepper Potts et de « Rhodey » Rhodes, forger de nouvelles alliances et affronter un puissant nouvel ennemi.", wikiTitle:'Iron Man 2'},
{ id:'incredible-hulk', poster:'images/posters/incredible-hulk.jpg', title:'L\'Incroyable Hulk', year:2008, type:'Film', franchise:'mcu', saga:'Phase 1 (2008-2012)', releaseOrder:2, chronoOrder:7, chronoNote:'2011', director:'Louis Leterrier', cast:['Edward Norton','Liv Tyler','Tim Roth','William Hurt'], duration:'112 min', synopsis:"Le scientifique Bruce Banner cherche désespérément un remède aux radiations gamma qui ont empoisonné ses cellules et libèrent en lui une force de rage incontrôlable : Hulk. Vivant dans l'ombre, coupé de la vie qu'il connaissait et de la femme qu'il aime, Betty Ross, Banner tente d'échapper à la traque obsessionnelle du général Thunderbolt Ross et de la machine militaire qui veut le capturer pour exploiter brutalement son pouvoir. Tous trois se retrouvent confrontés à un adversaire monstrueux, l'Abomination, dont la force destructrice dépasse même celle de Hulk.", wikiTitle:'The Incredible Hulk (film)'},
{ id:'oneshot-funny-thing-thor-hammer', poster:'images/posters/oneshot-funny-thing-thor-hammer.png', title:'Marvel One-Shot: A Funny Thing Happened on the Way to Thor\'s Hammer', year:2011, type:'Court-métrage', franchise:'mcu', saga:'One-Shots', releaseOrder:68, chronoOrder:8, chronoNote:'2011', director:'Leythum', cast:['Clark Gregg'], duration:'~4 min (bonus du Blu-ray Captain America: First Avenger)', synopsis:"En patientant pour récupérer le marteau de Thor tombé au Nouveau-Mexique, l'agent Coulson use de son sens de la repartie face à une administration tatillonne.", wikiTitle:'Marvel One-Shots'},
{ id:'thor', poster:'images/posters/thor.jpg', title:'Thor', year:2011, type:'Film', franchise:'mcu', saga:'Phase 1 (2008-2012)', releaseOrder:4, chronoOrder:9, chronoNote:'2011', director:'Kenneth Branagh', cast:['Chris Hemsworth','Natalie Portman','Tom Hiddleston','Anthony Hopkins'], duration:'115 min', synopsis:"Fils d'Odin, roi des dieux nordiques, Thor doit bientôt hériter du trône d'Asgard. Mais le jour de son couronnement, il réagit avec brutalité lorsque les Géants des Glaces, ennemis jurés des Asgardiens, violent leur traité de paix. En punition, Odin bannit Thor sur Terre. Pendant que Loki, son frère, complote à Asgard, Thor, désormais dépourvu de ses pouvoirs, doit affronter sa plus grande menace.", wikiTitle:'Thor (film)'},
{ id:'oneshot-the-consultant', poster:'images/posters/oneshot-the-consultant.png', title:'Marvel One-Shot: The Consultant', year:2011, type:'Court-métrage', franchise:'mcu', saga:'One-Shots', releaseOrder:69, chronoOrder:10, chronoNote:'2011', director:'Leythum', cast:['Clark Gregg','Maximiliano Hernández'], duration:'~4 min (bonus du Blu-ray Thor)', synopsis:"Coulson et l'agent Sitwell manigancent pour faire libérer un général et éviter que le S.H.I.E.L.D. n'ait à collaborer avec Tony Stark.", wikiTitle:'Marvel One-Shots'},
{ id:'avengers', poster:'images/posters/avengers.jpg', title:'Avengers', year:2012, type:'Film', franchise:'mcu', saga:'Phase 1 (2008-2012)', releaseOrder:6, chronoOrder:11, chronoNote:'2012', director:'Joss Whedon', cast:['Robert Downey Jr.','Chris Evans','Scarlett Johansson','Chris Hemsworth','Mark Ruffalo','Jeremy Renner'], duration:'143 min', synopsis:"Lorsqu'un ennemi inattendu menace la sécurité mondiale, Nick Fury, directeur de l'agence de maintien de la paix S.H.I.E.L.D., se retrouve contraint de rassembler une équipe pour éviter la catastrophe. Direction les quatre coins du globe pour un audacieux effort de recrutement réunissant Iron Man, Hulk, Thor, Captain America, Hawkeye et Black Widow.", wikiTitle:'The Avengers (2012 film)'},
{ id:'oneshot-item-47', poster:'images/posters/oneshot-item-47.jpg', title:'Marvel One-Shot: Item 47', year:2012, type:'Court-métrage', franchise:'mcu', saga:'One-Shots', releaseOrder:70, chronoOrder:12, chronoNote:'2012', director:'Louis D\'Esposito', cast:['Lizzy Caplan','Jesse Bradford'], duration:'~12 min (bonus du Blu-ray Avengers)', synopsis:"Un jeune couple de braqueurs met la main sur une arme chitauri abandonnée après la bataille de New York — jusqu'à attirer l'attention du S.H.I.E.L.D.", wikiTitle:'Item 47'},
{ id:'thor-dark-world', poster:'images/posters/thor-dark-world.jpg', title:'Thor: Le Monde des ténèbres', year:2013, type:'Film', franchise:'mcu', saga:'Phase 2 (2013-2015)', releaseOrder:8, chronoOrder:13, chronoNote:'2013', director:'Alan Taylor', cast:['Chris Hemsworth','Natalie Portman','Tom Hiddleston'], duration:'112 min', synopsis:"Après les événements de Thor et Avengers, Thor lutte pour restaurer l'ordre à travers le cosmos... mais une race ancienne menée par le vengeur Malekith revient plonger l'univers dans les ténèbres. Face à un ennemi que même Odin et Asgard ne peuvent contenir, Thor doit entreprendre le voyage le plus périlleux et personnel de sa vie, qui le réunira avec Jane Foster et l'obligera à tout sacrifier pour tous nous sauver.", wikiTitle:'Thor: The Dark World'},
{ id:'iron-man-3', poster:'images/posters/iron-man-3.jpg', title:'Iron Man 3', year:2013, type:'Film', franchise:'mcu', saga:'Phase 2 (2013-2015)', releaseOrder:7, chronoOrder:14, chronoNote:'2013', director:'Shane Black', cast:['Robert Downey Jr.','Gwyneth Paltrow','Ben Kingsley','Guy Pearce'], duration:'130 min', synopsis:"Iron Man 3 oppose l'industriel aussi arrogant que brillant Tony Stark à un ennemi dont la portée ne connaît aucune limite. Quand Stark voit son monde personnel détruit par les mains de son adversaire, il se lance dans une quête acharnée pour retrouver les responsables. Acculé, il doit survivre grâce à sa seule ingéniosité pour protéger ceux qui lui sont chers, et découvre enfin la réponse à la question qui le hante en secret : est-ce l'homme qui fait l'armure, ou l'armure qui fait l'homme ?", wikiTitle:'Iron Man 3'},
{ id:'oneshot-all-hail-the-king', poster:'images/posters/oneshot-all-hail-the-king.png', title:'Marvel One-Shot: All Hail the King', year:2014, type:'Court-métrage', franchise:'mcu', saga:'One-Shots', releaseOrder:71, chronoOrder:15, chronoNote:'2014', director:'Drew Pearce', cast:['Ben Kingsley'], duration:'~15 min (bonus du Blu-ray Thor: Le Monde des ténèbres)', synopsis:"Un journaliste interviewe en prison Trevor Slattery, le faux Mandarin d'Iron Man 3 — un épilogue qui sème aussi les graines du vrai Mandarin.", wikiTitle:'Marvel One-Shots'},
{ id:'captain-america-winter-soldier', poster:'images/posters/captain-america-winter-soldier.jpg', title:'Captain America: Le Soldat de l\'hiver', year:2014, type:'Film', franchise:'mcu', saga:'Phase 2 (2013-2015)', releaseOrder:9, chronoOrder:16, chronoNote:'2014', director:'Anthony et Joe Russo', cast:['Chris Evans','Scarlett Johansson','Sebastian Stan','Samuel L. Jackson'], duration:'136 min', synopsis:"Après les événements cataclysmiques de New York avec les Avengers, Steve Rogers, alias Captain America, vit discrètement à Washington D.C. et tente de s'adapter au monde moderne. Mais lorsqu'un collègue du S.H.I.E.L.D. est attaqué, Steve se retrouve pris dans une toile d'intrigues qui menace de mettre le monde en danger. Avec l'aide de Black Widow, il doit dénoncer un complot toujours plus vaste tout en échappant à des assassins professionnels envoyés pour le réduire au silence. Lorsque l'ampleur du complot est révélée, Captain America et Black Widow font appel à un nouvel allié, le Faucon — mais se retrouvent bientôt face à un ennemi aussi inattendu que redoutable : le Soldat de l'Hiver.", wikiTitle:'Captain America: The Winter Soldier'},
{ id:'guardians-galaxy', poster:'images/posters/guardians-galaxy.jpg', title:'Les Gardiens de la Galaxie', year:2014, type:'Film', franchise:'mcu', saga:'Phase 2 (2013-2015)', releaseOrder:10, chronoOrder:17, chronoNote:'2014', director:'James Gunn', cast:['Chris Pratt','Zoe Saldana','Dave Bautista','Vin Diesel','Bradley Cooper'], duration:'121 min', synopsis:"Dans cette épopée spatiale qui étend l'univers Marvel jusqu'au cosmos, l'aventurier téméraire Peter Quill devient la cible d'une chasse à l'homme impitoyable après avoir volé un mystérieux orbe convoité par Ronan, un puissant vilain dont les ambitions menacent l'univers tout entier. Pour échapper à Ronan, Quill est contraint à une alliance de circonstance avec un quatuor de marginaux dépareillés : Rocket, un raton laveur armé jusqu'aux dents, Groot, un humanoïde arborescent, l'énigmatique et redoutable Gamora, et Drax le Destructeur, animé par sa soif de vengeance. Mais quand Quill découvre le véritable pouvoir de l'orbe et la menace qu'il représente pour le cosmos, il doit rallier ses rivaux de fortune pour un ultime baroud d'honneur, le destin de la galaxie en jeu.", wikiTitle:'Guardians of the Galaxy (film)'},
{ id:'guardians-galaxy-2', poster:'images/posters/guardians-galaxy-2.jpg', title:'Les Gardiens de la Galaxie Vol. 2', year:2017, type:'Film', franchise:'mcu', saga:'Phase 3 (2016-2019)', releaseOrder:15, chronoOrder:18, chronoNote:'2014', director:'James Gunn', cast:['Chris Pratt','Zoe Saldana','Dave Bautista','Kurt Russell'], duration:'137 min', synopsis:"Sur fond de la fameuse « Awesome Mixtape #2 », les Gardiens de la Galaxie poursuivent leurs aventures aux confins du cosmos. L'équipe doit se battre pour préserver sa nouvelle famille tout en perçant les mystères des véritables origines de Peter Quill. D'anciens ennemis deviennent des alliés inattendus, et des personnages cultes des comics viennent prêter main-forte à nos héros.", wikiTitle:'Guardians of the Galaxy Vol. 2'},
{ id:'i-am-groot', animated:true, poster:'images/posters/i-am-groot.jpeg', title:'I Am Groot', year:2022, type:'Série', franchise:'mcu', saga:'Phase 4 (2021-2022)', releaseOrder:53, chronoOrder:19, chronoNote:'entre Vol. 2 et Vol. 3', director:'Kirsten Lepore (superviseure)', cast:['Vin Diesel (voix de Groot)'], duration:'2 saisons, 10 courts épisodes (animation)', synopsis:"Pas moyen de garder la galaxie face à ce bambin espiègle ! Bébé Groot est à l'honneur dans sa toute première collection de courts métrages, qui explore ses jeunes années insouciantes — et ses bêtises — au milieu des étoiles.", wikiTitle:'I Am Groot'},
{ id:'daredevil-nf-s1', poster:'images/posters/daredevil-nf-s1.jpg', title:'Daredevil (Saison 1)', year:2015, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:1, chronoOrder:20, chronoNote:'2015', director:'Drew Goddard (créateur), Steven S. DeKnight (showrunner)', cast:['Charlie Cox','Vincent D\'Onofrio','Deborah Ann Woll','Elden Henson'], duration:'1 saison, 13 épisodes', synopsis:"Matt Murdock endosse pour la première fois le costume de Daredevil pour nettoyer Hell's Kitchen, tandis que Wilson Fisk bâtit patiemment son emprise criminelle sur la ville.", wikiTitle:'Daredevil (season 1)'},
{ id:'jessica-jones-s1', poster:'images/posters/jessica-jones-s1.jpg', title:'Jessica Jones (Saison 1)', year:2015, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:2, chronoOrder:21, chronoNote:'2015', director:'Melissa Rosenberg (showrunneuse)', cast:['Krysten Ritter','David Tennant','Rachael Taylor','Mike Colter'], duration:'1 saison, 13 épisodes', synopsis:"Détective privée à la force surhumaine et au passé traumatique, Jessica Jones affronte Kilgrave, un homme doté d'un pouvoir de contrôle mental qui a fait d'elle sa marionnette.", wikiTitle:'Jessica Jones (season 1)'},
{ id:'avengers-ultron', poster:'images/posters/avengers-ultron.jpg', title:'Avengers: L\'Ère d\'Ultron', year:2015, type:'Film', franchise:'mcu', saga:'Phase 2 (2013-2015)', releaseOrder:11, chronoOrder:22, chronoNote:'2015', director:'Joss Whedon', cast:['Robert Downey Jr.','Chris Evans','Chris Hemsworth','Elizabeth Olsen','Paul Bettany'], duration:'141 min', synopsis:"Quand Tony Stark tente de relancer un programme de maintien de la paix resté en sommeil, tout tourne mal, et les plus puissants héros de la Terre — Iron Man, Captain America, Thor, Hulk, Black Widow et Hawkeye — sont mis à l'épreuve ultime, l'avenir de la planète étant en jeu. Face à l'émergence du redoutable Ultron, les Avengers doivent l'empêcher de mettre en œuvre ses terribles plans, et des alliances aussi fragiles qu'inattendues ouvrent la voie à une aventure mondiale hors du commun.", wikiTitle:'Avengers: Age of Ultron'},
{ id:'ant-man', poster:'images/posters/ant-man.jpg', title:'Ant-Man', year:2015, type:'Film', franchise:'mcu', saga:'Phase 2 (2013-2015)', releaseOrder:12, chronoOrder:23, chronoNote:'2015', director:'Peyton Reed', cast:['Paul Rudd','Evangeline Lilly','Michael Douglas','Corey Stoll'], duration:'117 min', synopsis:"Un membre fondateur des Avengers arrive pour la première fois sur grand écran : maître voleur doté de la stupéfiante capacité de rétrécir tout en gagnant en force, Scott Lang doit embrasser son héros intérieur et aider son mentor, le Dr Hank Pym, à protéger le secret de sa spectaculaire combinaison Ant-Man face à une nouvelle génération de menaces titanesques. Contre des obstacles en apparence insurmontables, Pym et Lang doivent planifier et exécuter un casse qui sauvera le monde.", wikiTitle:'Ant-Man (film)'},
{ id:'daredevil-nf-s2', poster:'images/posters/daredevil-nf-s2.jpg', title:'Daredevil (Saison 2)', year:2016, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:3, chronoOrder:24, chronoNote:'2016', director:'Doug Petrie, Marco Ramirez (showrunners)', cast:['Charlie Cox','Jon Bernthal','Élodie Yung','Deborah Ann Woll'], duration:'1 saison, 13 épisodes', synopsis:"L'arrivée du Punisher, justicier expéditif, bouleverse le code moral de Daredevil, tandis que le retour d'Elektra Natchios le ramène vers son passé et l'organisation de la Main.", wikiTitle:'Daredevil (season 2)'},
{ id:'luke-cage-s1', poster:'images/posters/luke-cage-s1.jpeg', title:'Luke Cage (Saison 1)', year:2016, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:4, chronoOrder:25, chronoNote:'2016', director:'Cheo Hodari Coker (showrunner)', cast:['Mike Colter','Mahershala Ali','Alfre Woodard','Simone Missick'], duration:'1 saison, 13 épisodes', synopsis:"Doté d'une peau incassable, Luke Cage devient malgré lui le protecteur de Harlem face à Cornell « Cottonmouth » Stokes et Mariah Dillard.", wikiTitle:'Luke Cage (season 1)'},
{ id:'iron-fist-s1', poster:'images/posters/iron-fist-s1.jpg', title:'Iron Fist (Saison 1)', year:2017, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:5, chronoOrder:26, chronoNote:'2017', director:'Scott Buck (showrunner)', cast:['Finn Jones','Jessica Henwick','Jessica Stroup','Tom Pelphrey'], duration:'1 saison, 13 épisodes', synopsis:"Daniel Rand revient à New York après des années de disparition. Il combat les éléments criminels qui gangrènent la ville grâce à sa maîtrise du kung-fu et à sa capacité à invoquer le pouvoir ardent du Poing de Fer.", wikiTitle:'Iron Fist (season 1)'},
{ id:'defenders', poster:'images/posters/defenders.jpg', title:'The Defenders', year:2017, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:6, chronoOrder:27, chronoNote:'2017', director:'S.J. Clarkson (showrunneuse)', cast:['Charlie Cox','Krysten Ritter','Mike Colter','Finn Jones'], duration:'1 saison, 8 épisodes', synopsis:"Daredevil, Jessica Jones, Luke Cage et Iron Fist, quatuor de héros singuliers, partagent un seul et même objectif : sauver New York. C'est l'histoire de quatre figures solitaires, chacune accablée par ses propres épreuves, qui réalisent à contrecœur qu'elles pourraient bien être plus fortes réunies.", wikiTitle:'The Defenders (miniseries)'},
{ id:'civil-war', poster:'images/posters/civil-war.jpg', title:'Captain America: Civil War', year:2016, type:'Film', franchise:'mcu', saga:'Phase 3 (2016-2019)', releaseOrder:13, chronoOrder:28, chronoNote:'2016', director:'Anthony et Joe Russo', cast:['Chris Evans','Robert Downey Jr.','Scarlett Johansson','Sebastian Stan','Chadwick Boseman'], duration:'147 min', synopsis:"Steve Rogers dirige la toute nouvelle équipe des Avengers dans ses efforts continus pour protéger l'humanité. Mais après un incident impliquant les Avengers et causant des dommages collatéraux, la pression politique s'intensifie pour mettre en place un système de responsabilisation, encadré par un organe de contrôle chargé de superviser l'équipe. Ce nouveau statu quo fracture les Avengers en deux camps : celui de Steve Rogers, qui souhaite que les Avengers restent libres de défendre l'humanité sans ingérence gouvernementale, et celui de Tony Stark, qui choisit de soutenir la supervision et la responsabilisation par le gouvernement.", wikiTitle:'Captain America: Civil War'},
{ id:'black-widow', poster:'images/posters/black-widow.jpg', title:'Black Widow', year:2021, type:'Film', franchise:'mcu', saga:'Phase 4 (2021-2022)', releaseOrder:24, chronoOrder:29, chronoNote:'2016 (après Civil War)', director:'Cate Shortland', cast:['Scarlett Johansson','Florence Pugh','David Harbour','Rachel Weisz'], duration:'134 min', synopsis:"Dans ce thriller d'espionnage haletant, Natasha Romanoff, alias Black Widow, doit affronter les parts les plus sombres de son passé lorsqu'une dangereuse conspiration liée à son histoire refait surface. Traquée par une force prête à tout pour l'abattre, Natasha doit composer avec son passé d'espionne et les relations brisées qu'elle a laissées derrière elle, bien avant de devenir une Avenger.", wikiTitle:'Black Widow (2021 film)'},
{ id:'black-panther', poster:'images/posters/black-panther.jpg', title:'Black Panther', year:2018, type:'Film', franchise:'mcu', saga:'Phase 3 (2016-2019)', releaseOrder:18, chronoOrder:30, chronoNote:'2017-18', director:'Ryan Coogler', cast:['Chadwick Boseman','Michael B. Jordan','Lupita Nyong\'o','Danai Gurira'], duration:'134 min', synopsis:"Après la mort de son père, le roi du Wakanda, T'Challa rentre dans cette nation africaine isolée et technologiquement avancée pour succéder au trône et devenir roi à son tour. Mais quand un puissant ennemi du passé refait surface, la valeur de T'Challa en tant que roi — et en tant que Black Panther — est mise à l'épreuve dans un conflit qui met en péril le destin du Wakanda et du monde entier. Face à la trahison et au danger, le jeune roi doit rallier ses alliés et déployer toute la puissance de Black Panther pour vaincre ses ennemis et assurer la sécurité de son peuple.", wikiTitle:'Black Panther (film)'},
{ id:'spiderman-homecoming', poster:'images/posters/spiderman-homecoming.jpg', title:'Spider-Man: Homecoming', year:2017, type:'Film', franchise:'mcu', saga:'Phase 3 (2016-2019)', releaseOrder:16, chronoOrder:31, chronoNote:'2016', director:'Jon Watts', cast:['Tom Holland','Michael Keaton','Robert Downey Jr.','Zendaya'], duration:'133 min', synopsis:"Peter Parker, jeune Spider-Man qui a fait ses débuts remarqués dans Captain America: Civil War, commence à apprivoiser sa nouvelle identité de super-héros tisseur de toiles. Grisé par son expérience aux côtés des Avengers, Peter rentre chez lui, où il vit avec sa Tante May sous l'œil attentif de son nouveau mentor, Tony Stark. Il tente de reprendre le cours normal de sa vie de lycéen — obsédé par l'idée de prouver qu'il est plus qu'un simple Spider-Man de quartier — mais l'apparition d'un nouveau vilain, le Vautour, va menacer tout ce qu'il a de plus cher.", wikiTitle:'Spider-Man: Homecoming'},
{ id:'punisher-s1', poster:'images/posters/punisher-s1.jpg', title:'The Punisher (Saison 1)', year:2017, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:7, chronoOrder:32, chronoNote:'2017', director:'Steve Lightfoot (showrunner)', cast:['Jon Bernthal','Ben Barnes','Ebon Moss-Bachrach','Amber Rose Revah'], duration:'1 saison, 13 épisodes', synopsis:"Après le meurtre de sa famille, Frank Castle est à la fois hanté et traqué. Dans les bas-fonds du crime, on le connaîtra bientôt sous le nom du Punisher.", wikiTitle:'The Punisher (season 1)'},
{ id:'doctor-strange', poster:'images/posters/doctor-strange.jpg', title:'Doctor Strange', year:2016, type:'Film', franchise:'mcu', saga:'Phase 3 (2016-2019)', releaseOrder:14, chronoOrder:33, chronoNote:'2016', director:'Scott Derrickson', cast:['Benedict Cumberbatch','Tilda Swinton','Chiwetel Ejiofor'], duration:'115 min', synopsis:"L'histoire du célèbre neurochirurgien Dr Stephen Strange, dont la vie bascule à jamais après un terrible accident de voiture qui lui fait perdre l'usage de ses mains. Quand la médecine traditionnelle échoue à le guérir, il doit chercher la guérison — et l'espoir — dans un lieu improbable : une mystérieuse enclave nommée Kamar-Taj. Bientôt, Strange, désormais doté de nouveaux pouvoirs magiques, doit choisir entre retourner à sa vie de fortune et de prestige, ou tout abandonner pour défendre le monde en tant que sorcier le plus puissant qui soit.", wikiTitle:'Doctor Strange (2016 film)'},
{ id:'jessica-jones-s2', poster:'images/posters/jessica-jones-s2.jpg', title:'Jessica Jones (Saison 2)', year:2018, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:8, chronoOrder:34, chronoNote:'2018', director:'Melissa Rosenberg (showrunneuse)', cast:['Krysten Ritter','Rachael Taylor','Janet McTeer'], duration:'1 saison, 13 épisodes', synopsis:"Jessica enquête sur les origines de ses pouvoirs et sur l'organisation IGH, ce qui la mène jusqu'à une mère qu'elle croyait morte.", wikiTitle:'Jessica Jones (season 2)'},
{ id:'luke-cage-s2', poster:'images/posters/luke-cage-s2.jpg', title:'Luke Cage (Saison 2)', year:2018, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:9, chronoOrder:35, chronoNote:'2018', director:'Cheo Hodari Coker (showrunner)', cast:['Mike Colter','Alfre Woodard','Mustafa Shakir'], duration:'1 saison, 13 épisodes', synopsis:"Luke Cage doit affronter Bushmaster, un rival venu de Jamaïque, tout en luttant contre la tentation du pouvoir qui a corrompu tant d'autres avant lui.", wikiTitle:'Luke Cage (season 2)'},
{ id:'iron-fist-s2', poster:'images/posters/iron-fist-s2.jpg', title:'Iron Fist (Saison 2)', year:2018, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:10, chronoOrder:36, chronoNote:'2018', director:'M. Raven Metzner (showrunner)', cast:['Finn Jones','Jessica Henwick'], duration:'1 saison, 10 épisodes', synopsis:"Danny Rand et Colleen Wing tentent de maintenir la paix parmi les nombreux gangs rivaux. Avec l'aide de Misty Knight, ils découvrent que le crime organisé de la ville va bien plus loin qu'ils ne l'imaginaient, et raccrocher les épées n'est plus une option. Davos revient à New York après avoir découvert la disparition de K'un-Lun, sa cité natale. Tenant Danny pour responsable de ce destin tragique, Davos jure de venger leur cité perdue et ravive une rivalité fraternelle autour du fardeau lié au Poing de Fer.", wikiTitle:'Iron Fist (season 2)'},
{ id:'daredevil-nf-s3', poster:'images/posters/daredevil-nf-s3.jpg', title:'Daredevil (Saison 3)', year:2018, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:11, chronoOrder:37, chronoNote:'2018', director:'Erik Oleson (showrunner)', cast:['Charlie Cox','Vincent D\'Onofrio','Deborah Ann Woll','Wilson Bethel'], duration:'1 saison, 13 épisodes', synopsis:"Disparu pendant des mois, Matt Murdock refait surface brisé, remettant en question son avenir en tant que justicier Daredevil et avocat. Mais lorsque son ennemi juré Wilson Fisk sort de prison, Matt doit choisir entre se cacher du monde ou embrasser pleinement son destin de héros.", wikiTitle:'Daredevil (season 3)'},
{ id:'thor-ragnarok', poster:'images/posters/thor-ragnarok.jpg', title:'Thor: Ragnarok', year:2017, type:'Film', franchise:'mcu', saga:'Phase 3 (2016-2019)', releaseOrder:17, chronoOrder:38, chronoNote:'2017', director:'Taika Waititi', cast:['Chris Hemsworth','Tom Hiddleston','Cate Blanchett','Mark Ruffalo'], duration:'130 min', synopsis:"Emprisonné de l'autre côté de l'univers sans son puissant marteau, Thor se retrouve dans une course contre la montre pour retourner à Asgard et empêcher le Ragnarok — la destruction de son monde natal et la fin de la civilisation asgardienne — orchestré par une toute-puissante nouvelle menace, l'impitoyable Hela. Mais il doit d'abord survivre à un combat de gladiateurs mortel qui l'oppose à un ancien allié et membre des Avengers : l'Incroyable Hulk !", wikiTitle:'Thor: Ragnarok'},
{ id:'punisher-s2', poster:'images/posters/punisher-s2.jpg', title:'The Punisher (Saison 2)', year:2019, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:12, chronoOrder:39, chronoNote:'2019', director:'Steve Lightfoot (showrunner)', cast:['Jon Bernthal','Ben Barnes','Amy Rutberg','Josh Stewart'], duration:'1 saison, 13 épisodes', synopsis:"L'ancien marine devenu justicier Frank Castle mène une vie tranquille sur les routes, jusqu'à ce qu'il se retrouve soudain mêlé à la tentative de meurtre d'une jeune fille. En cherchant à percer le mystère qui l'entoure et à échapper à ceux qui la traquent, Castle redevient une cible, tandis que d'anciens comme de nouveaux ennemis le forcent à se demander s'il doit accepter son destin et endosser pleinement le rôle du Punisher.", wikiTitle:'The Punisher (season 2)'},
{ id:'jessica-jones-s3', poster:'images/posters/jessica-jones-s3.jpg', title:'Jessica Jones (Saison 3)', year:2019, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:13, chronoOrder:40, chronoNote:'2019', director:'Melissa Rosenberg (showrunneuse)', cast:['Krysten Ritter','Rachael Taylor','Jeremy Bobb'], duration:'1 saison, 13 épisodes', synopsis:"Dernière saison : Jessica traque un tueur en série méthodique tandis que sa relation avec Trish, en quête de super-pouvoirs, se dégrade dangereusement.", wikiTitle:'Jessica Jones (season 3)'},
{ id:'ant-man-wasp', poster:'images/posters/ant-man-wasp.jpg', title:'Ant-Man et la Guêpe', year:2018, type:'Film', franchise:'mcu', saga:'Phase 3 (2016-2019)', releaseOrder:20, chronoOrder:41, chronoNote:'2018 (avant Infinity War)', director:'Peyton Reed', cast:['Paul Rudd','Evangeline Lilly','Michael Douglas','Michelle Pfeiffer'], duration:'118 min', synopsis:"Un nouveau chapitre met en scène des héros dotés de l'étonnante capacité de rétrécir. Après les événements de Captain America: Civil War, Scott Lang doit composer avec les conséquences de ses choix, à la fois comme super-héros et comme père. Alors qu'il peine à concilier vie de famille et responsabilités en tant qu'Ant-Man, Hope van Dyne et le Dr Hank Pym le rattrapent avec une mission urgente : il doit à nouveau enfiler la combinaison et apprendre à combattre aux côtés de la Guêpe, tandis qu'ensemble ils percent les secrets de leur passé.", wikiTitle:'Ant-Man and the Wasp'},
{ id:'infinity-war', poster:'images/posters/infinity-war.jpg', title:'Avengers: Infinity War', year:2018, type:'Film', franchise:'mcu', saga:'Phase 3 (2016-2019)', releaseOrder:19, chronoOrder:42, chronoNote:'2018', director:'Anthony et Joe Russo', cast:['Robert Downey Jr.','Chris Hemsworth','Chris Evans','Josh Brolin'], duration:'149 min', synopsis:"Voyage cinématographique sans précédent, mûri pendant dix ans à travers tout l'univers Marvel, Avengers: Infinity War porte à l'écran l'affrontement ultime et le plus meurtrier de tous les temps. Alors que les Avengers et leurs alliés continuent de protéger le monde de menaces trop grandes pour un seul héros, un nouveau danger émerge de l'ombre cosmique : Thanos. Despote tristement célèbre à l'échelle intergalactique, il cherche à réunir les six Pierres d'Infini, artefacts d'un pouvoir inimaginable, pour imposer sa volonté tordue à la réalité tout entière. Tout ce pour quoi les Avengers se sont battus mène à cet instant — jamais le sort de la Terre et de l'existence même n'a été aussi incertain.", wikiTitle:'Avengers: Infinity War'},
{ id:'endgame', poster:'images/posters/endgame.jpg', title:'Avengers: Endgame', year:2019, type:'Film', franchise:'mcu', saga:'Phase 3 (2016-2019)', releaseOrder:22, chronoOrder:43, chronoNote:'2018-2023', director:'Anthony et Joe Russo', cast:['Robert Downey Jr.','Chris Evans','Scarlett Johansson','Chris Hemsworth'], duration:'181 min', synopsis:"Le cours funeste des événements déclenché par Thanos, qui a anéanti la moitié de l'univers et fracturé les rangs des Avengers, pousse les survivants à mener un dernier combat dans cette grande conclusion à vingt-deux films du Marvel Cinematic Universe.", wikiTitle:'Avengers: Endgame'},
{ id:'loki-s1', poster:'images/posters/loki-s1.png', title:'Loki (Saison 1)', year:2021, type:'Série', franchise:'mcu', saga:'Phase 4 (2021-2022)', releaseOrder:40, chronoOrder:44, chronoNote:'après le casse temporel d\'Endgame', director:'Kate Herron', cast:['Tom Hiddleston','Owen Wilson','Sophia Di Martino'], duration:'1 saison, 6 épisodes', synopsis:"Arrêté par la Confrérie du Temps (TVA) pour avoir altéré la timeline, Loki est recruté pour traquer une version variante de lui-même.", wikiTitle:'Loki (TV series)'},
{ id:'what-if-s1', animated:true, poster:'images/posters/what-if-s1.png', title:'What If...? (Saison 1)', year:2021, type:'Série', franchise:'mcu', saga:'Phase 4 (2021-2022)', releaseOrder:41, chronoOrder:45, chronoNote:'multivers', director:'Bryan Andrews', cast:['Jeffrey Wright (narrateur)'], duration:'1 saison, 9 épisodes (animation)', synopsis:"Le Gardien explore des univers alternatifs où un simple événement modifié bouleverse tout le destin des héros Marvel.", wikiTitle:'What If...? (TV series)'},
{ id:'marvel-zombies', animated:true, poster:'images/posters/marvel-zombies.png', title:'Marvel Zombies', year:2025, type:'Série', franchise:'mcu', saga:'Phase 6 (2025-2027)', releaseOrder:59, chronoOrder:46, chronoNote:'réalité alternative issue de What If...?', director:'Bryan Andrews', cast:['Elizabeth Olsen','Iman Vellani','Simu Liu','Florence Pugh','David Harbour','Hailee Steinfeld'], duration:'1 saison, 4 épisodes (animation, déconseillé aux plus jeunes)', synopsis:"Dans une réalité ravagée par une infection zombie, une poignée de héros et de vilains survivants tente de sauver ce qu'il reste de l'humanité.", wikiTitle:'Marvel Zombies (TV series)'},
{ id:'wandavision', poster:'images/posters/wandavision.png', title:'WandaVision', year:2021, type:'Série', franchise:'mcu', saga:'Phase 4 (2021-2022)', releaseOrder:38, chronoOrder:47, chronoNote:'3 semaines après Endgame', director:'Matt Shakman', cast:['Elizabeth Olsen','Paul Bettany','Kathryn Hahn'], duration:'1 saison, 9 épisodes', synopsis:"Un mélange de sitcom classique et d'univers Marvel : Wanda Maximoff et Vision, deux êtres surpuissants menant une vie de banlieue idéalisée, commencent à soupçonner que tout n'est pas exactement ce qu'il paraît être.", wikiTitle:'WandaVision'},
{ id:'shang-chi', poster:'images/posters/shang-chi.jpeg', title:'Shang-Chi et la Légende des Dix Anneaux', year:2021, type:'Film', franchise:'mcu', saga:'Phase 4 (2021-2022)', releaseOrder:25, chronoOrder:48, chronoNote:'2024', director:'Destin Daniel Cretton', cast:['Simu Liu','Awkwafina','Tony Leung','Michelle Yeoh'], duration:'132 min', synopsis:"Simu Liu incarne Shang-Chi, qui doit affronter le passé qu'il pensait avoir laissé derrière lui lorsqu'il se retrouve happé par la toile de la mystérieuse organisation des Dix Anneaux. Le film réunit également Tony Leung dans le rôle de Wenwu, Awkwafina dans celui de Katy, l'amie de Shang-Chi, et Michelle Yeoh dans celui de Jiang Nan.", wikiTitle:'Shang-Chi and the Legend of the Ten Rings'},
{ id:'falcon-winter-soldier', poster:'images/posters/falcon-winter-soldier.png', title:'Falcon et le Soldat de l\'hiver', year:2021, type:'Série', franchise:'mcu', saga:'Phase 4 (2021-2022)', releaseOrder:39, chronoOrder:49, chronoNote:'6 mois après WandaVision', director:'Kari Skogland', cast:['Anthony Mackie','Sebastian Stan','Wyatt Russell'], duration:'1 saison, 6 épisodes', synopsis:"Après les événements d'Avengers: Endgame, Sam Wilson/Falcon et Bucky Barnes/le Soldat de l'Hiver font équipe pour une aventure mondiale qui met à l'épreuve leurs capacités — et leur patience.", wikiTitle:'The Falcon and the Winter Soldier'},
{ id:'spiderman-far-from-home', poster:'images/posters/spiderman-far-from-home.jpg', title:'Spider-Man: Far From Home', year:2019, type:'Film', franchise:'mcu', saga:'Phase 3 (2016-2019)', releaseOrder:23, chronoOrder:50, chronoNote:'2024 (temps du film)', director:'Jon Watts', cast:['Tom Holland','Jake Gyllenhaal','Zendaya','Samuel L. Jackson'], duration:'129 min', synopsis:"Peter Parker revient dans le prochain chapitre de la saga entamée avec Homecoming ! Notre super-héros de quartier décide de rejoindre ses meilleurs amis Ned, MJ et le reste de la bande pour des vacances en Europe. Mais son projet de laisser ses activités héroïques de côté pendant quelques semaines tombe rapidement à l'eau lorsqu'il accepte, à contrecœur, d'aider Nick Fury à percer le mystère de plusieurs attaques de créatures élémentaires semant le chaos à travers le continent.", wikiTitle:'Spider-Man: Far From Home'},
{ id:'eternals', poster:'images/posters/eternals.jpeg', title:'Eternals', year:2021, type:'Film', franchise:'mcu', saga:'Phase 4 (2021-2022)', releaseOrder:26, chronoOrder:51, chronoNote:'depuis 5000 av. J.-C., jusqu\'à nos jours', director:'Chloé Zhao', cast:['Gemma Chan','Richard Madden','Angelina Jolie','Salma Hayek'], duration:'157 min', synopsis:"Une nouvelle et fascinante équipe de super-héros rejoint le Marvel Cinematic Universe : des extraterrestres ancestraux qui vivent en secret sur Terre depuis des millénaires. À la suite des événements d'Avengers: Endgame, une tragédie inattendue les force à sortir de l'ombre pour se réunir contre l'ennemi le plus ancien de l'humanité : les Déviants.", wikiTitle:'Eternals (film)'},
{ id:'no-way-home', poster:'images/posters/no-way-home.jpg', title:'Spider-Man: No Way Home', year:2021, type:'Film', franchise:'mcu', saga:'Phase 4 (2021-2022)', releaseOrder:27, chronoOrder:52, chronoNote:'2024-25', director:'Jon Watts', cast:['Tom Holland','Zendaya','Willem Dafoe','Alfred Molina'], duration:'148 min', synopsis:"Un sort du Docteur Strange qui tourne mal déchire le multivers, ramenant des méchants d'autres Spider-Man face à Peter Parker.", wikiTitle:'Spider-Man: No Way Home'},
{ id:'doctor-strange-multiverse', poster:'images/posters/doctor-strange-multiverse.jpg', title:'Doctor Strange in the Multiverse of Madness', year:2022, type:'Film', franchise:'mcu', saga:'Phase 4 (2021-2022)', releaseOrder:28, chronoOrder:53, chronoNote:'2025', director:'Sam Raimi', cast:['Benedict Cumberbatch','Elizabeth Olsen','Xochitl Gomez'], duration:'126 min', synopsis:"Un voyage palpitant à travers le Multivers en compagnie de Doctor Strange, de son fidèle ami Wong et de Wanda Maximoff, alias la Sorcière Rouge.", wikiTitle:'Doctor Strange in the Multiverse of Madness'},
{ id:'hawkeye', poster:'images/posters/hawkeye.png', title:'Hawkeye', year:2021, type:'Série', franchise:'mcu', saga:'Phase 4 (2021-2022)', releaseOrder:42, chronoOrder:54, chronoNote:'Noël, après Endgame', director:'Rhys Thomas', cast:['Jeremy Renner','Hailee Steinfeld','Vera Farmiga'], duration:'1 saison, 6 épisodes', synopsis:"Clint Barton fait équipe avec la jeune archère Kate Bishop pour démêler une affaire liée à son passé de Ronin.", wikiTitle:'Hawkeye (miniseries)'},
{ id:'moon-knight', poster:'images/posters/moon-knight.jpg', title:'Moon Knight', year:2022, type:'Série', franchise:'mcu', saga:'Phase 4 (2021-2022)', releaseOrder:43, chronoOrder:55, chronoNote:'contemporain', director:'Mohamed Diab', cast:['Oscar Isaac','May Calamawy','Ethan Hawke'], duration:'1 saison, 6 épisodes', synopsis:"Moon Knight suit Steven Grant, discret employé de boutique de souvenirs, en proie à des absences et à des souvenirs d'une autre vie. Steven découvre qu'il souffre de trouble dissociatif de l'identité et partage son corps avec le mercenaire Marc Spector. Alors que les ennemis de Steven/Marc convergent vers eux, ils doivent naviguer entre leurs identités complexes tout en étant précipités au cœur d'un mystère mortel parmi les puissants dieux d'Égypte.", wikiTitle:'Moon Knight (miniseries)'},
{ id:'wakanda-forever', poster:'images/posters/wakanda-forever.jpg', title:'Black Panther: Wakanda Forever', year:2022, type:'Film', franchise:'mcu', saga:'Phase 4 (2021-2022)', releaseOrder:30, chronoOrder:56, chronoNote:'2025-26', director:'Ryan Coogler', cast:['Letitia Wright','Lupita Nyong\'o','Danai Gurira','Tenoch Huerta'], duration:'161 min', synopsis:"La reine Ramonda, Shuri, M'Baku, Okoye et les Dora Milaje luttent pour protéger leur nation des puissances mondiales qui cherchent à intervenir après la mort du roi T'Challa. Alors que les Wakandais s'efforcent d'embrasser ce nouveau chapitre, les héros doivent s'unir, avec l'aide de la War Dog Nakia et d'Everett Ross, pour tracer une nouvelle voie pour le royaume du Wakanda.", wikiTitle:'Black Panther: Wakanda Forever'},
{ id:'echo', poster:'images/posters/echo.jpg', title:'Echo', year:2024, type:'Série', franchise:'mcu', saga:'Phase 5 (2023-2025)', releaseOrder:48, chronoOrder:57, chronoNote:'après Hawkeye', director:'Sydney Freeland', cast:['Alaqua Cox','Vincent D\'Onofrio','Chaske Spencer'], duration:'1 saison, 5 épisodes', synopsis:"L'histoire des origines d'Echo retrouve Maya Lopez, dont le comportement impitoyable à New York la rattrape dans sa ville natale. Elle doit affronter son passé, renouer avec ses racines amérindiennes et embrasser le sens de la famille et de la communauté si elle espère aller de l'avant.", wikiTitle:'Echo (TV series)'},
{ id:'she-hulk', poster:'images/posters/she-hulk.jpg', title:'She-Hulk: Avocate', year:2022, type:'Série', franchise:'mcu', saga:'Phase 4 (2021-2022)', releaseOrder:45, chronoOrder:58, chronoNote:'contemporain', director:'Kat Coiro', cast:['Tatiana Maslany','Mark Ruffalo','Tim Roth'], duration:'1 saison, 9 épisodes', synopsis:"Jennifer Walters, avocate spécialisée dans les affaires juridiques liées aux surhumains, doit jongler avec la vie compliquée d'une célibataire trentenaire qui se trouve aussi être une surpuissante hulk verte de deux mètres.", wikiTitle:'She-Hulk: Attorney at Law'},
{ id:'ms-marvel', poster:'images/posters/ms-marvel.jpg', title:'Ms. Marvel', year:2022, type:'Série', franchise:'mcu', saga:'Phase 4 (2021-2022)', releaseOrder:44, chronoOrder:59, chronoNote:'contemporain', director:'Adil El Arbi, Bilall Fallah', cast:['Iman Vellani','Matt Lintz','Yasmeen Fletcher'], duration:'1 saison, 6 épisodes', synopsis:"Kamala Khan, ado fan des Avengers à Jersey City, découvre des pouvoirs cosmiques qui vont bouleverser sa vie.", wikiTitle:'Ms. Marvel (TV series)'},
{ id:'thor-love-thunder', poster:'images/posters/thor-love-thunder.jpeg', title:'Thor: Love and Thunder', year:2022, type:'Film', franchise:'mcu', saga:'Phase 4 (2021-2022)', releaseOrder:29, chronoOrder:60, chronoNote:'2025', director:'Taika Waititi', cast:['Chris Hemsworth','Natalie Portman','Christian Bale','Tessa Thompson'], duration:'119 min', synopsis:"Le dieu du tonnerre se lance dans un voyage inédit pour lui : celui de la découverte de soi. Mais ses efforts sont interrompus par un tueur galactique de dieux, Gorr le Boucher de Dieux, qui cherche l'extinction de tous les panthéons. Pour combattre cette menace, Thor s'allie à la reine Valkyrie, à Korg et à son ex-petite amie Jane Foster qui, à sa grande surprise, manie désormais son marteau magique Mjolnir sous le nom de Mighty Thor. Ensemble, ils se lancent dans une périlleuse aventure cosmique pour percer le mystère de la vengeance de Gorr et l'arrêter avant qu'il ne soit trop tard.", wikiTitle:'Thor: Love and Thunder'},
{ id:'ironheart', poster:'images/posters/ironheart.png', title:'Ironheart', year:2025, type:'Série', franchise:'mcu', saga:'Phase 5 (2023-2025)', releaseOrder:57, chronoOrder:61, chronoNote:'après Wakanda Forever', director:'Sam Bailey', cast:['Dominique Thorne','Anthony Ramos','Manny Montana','Alden Ehrenreich','Sacha Baron Cohen'], duration:'1 saison, 6 épisodes', synopsis:"De retour à Chicago après son passage au Wakanda, la surdouée Riri Williams perfectionne son armure Ironheart et croise la route d'un mystérieux escroc, le Hood.", wikiTitle:'Ironheart (miniseries)'},
{ id:'werewolf-by-night', poster:'images/posters/werewolf-by-night.jpg', title:'Werewolf by Night', year:2022, type:'Série', franchise:'mcu', saga:'Phase 4 (2021-2022)', releaseOrder:51, chronoOrder:62, chronoNote:'fin 2025', director:'Michael Giacchino', cast:['Gael García Bernal','Laura Donnelly','Harriet Sansom Harris'], duration:'1 spécial, 53 min (noir et blanc)', synopsis:"À la mort du chasseur de monstres Ulysses Bloodstone, un groupe de chasseurs rivaux s'affronte lors d'une chasse macabre organisée par sa veuve — jusqu'à ce qu'un invité au sang maudit change la donne.", wikiTitle:'Werewolf by Night (TV special)'},
{ id:'guardians-holiday-special', poster:'images/posters/guardians-holiday-special.jpg', title:'The Guardians of the Galaxy Holiday Special', year:2022, type:'Série', franchise:'mcu', saga:'Phase 4 (2021-2022)', releaseOrder:52, chronoOrder:63, chronoNote:'décembre 2025', director:'James Gunn', cast:['Kevin Bacon','Chris Pratt','Dave Bautista','Karen Gillan','Pom Klementieff'], duration:'1 spécial, 44 min', synopsis:"En mission pour rendre Noël inoubliable pour Quill, les Gardiens de la Galaxie se rendent sur Terre à la recherche du cadeau parfait.", wikiTitle:'The Guardians of the Galaxy Holiday Special'},
{ id:'quantumania', poster:'images/posters/quantumania.jpg', title:'Ant-Man et la Guêpe: Quantumania', year:2023, type:'Film', franchise:'mcu', saga:'Phase 5 (2023-2025)', releaseOrder:31, chronoOrder:64, chronoNote:'2026', director:'Peyton Reed', cast:['Paul Rudd','Evangeline Lilly','Jonathan Majors','Michelle Pfeiffer'], duration:'125 min', synopsis:"Officiellement le coup d'envoi de la Phase 5 du MCU : les partenaires super-héroïques Scott Lang et Hope Van Dyne reprennent leurs aventures d'Ant-Man et la Guêpe. Avec les parents de Hope, Hank Pym et Janet Van Dyne, la famille se retrouve à explorer le Royaume Quantique, à croiser d'étranges nouvelles créatures et à vivre une aventure qui les poussera au-delà de ce qu'ils croyaient possible. Jonathan Majors rejoint l'aventure dans le rôle de Kang.", wikiTitle:'Ant-Man and the Wasp: Quantumania'},
{ id:'guardians-galaxy-3', poster:'images/posters/guardians-galaxy-3.jpg', title:'Les Gardiens de la Galaxie Vol. 3', year:2023, type:'Film', franchise:'mcu', saga:'Phase 5 (2023-2025)', releaseOrder:32, chronoOrder:65, chronoNote:'2026', director:'James Gunn', cast:['Chris Pratt','Zoe Saldana','Dave Bautista','Karen Gillan'], duration:'150 min', synopsis:"Notre bande de marginaux préférée a un peu changé, ces derniers temps. Peter Quill, toujours sous le choc de la perte de Gamora, doit rallier son équipe pour défendre l'univers tout en protégeant l'un des leurs — une mission qui, si elle échoue, pourrait bien signer la fin des Gardiens tels qu'on les connaît.", wikiTitle:'Guardians of the Galaxy Vol. 3'},
{ id:'secret-invasion', poster:'images/posters/secret-invasion.jpg', title:'Secret Invasion', year:2023, type:'Série', franchise:'mcu', saga:'Phase 5 (2023-2025)', releaseOrder:46, chronoOrder:66, chronoNote:'contemporain', director:'Ali Selim', cast:['Samuel L. Jackson','Ben Mendelsohn','Kingsley Ben-Adir'], duration:'1 saison, 6 épisodes', synopsis:"La série événement met en scène une faction de Skrulls métamorphes qui infiltrent la Terre depuis des années.", wikiTitle:'Secret Invasion (TV series)'},
{ id:'the-marvels', poster:'images/posters/the-marvels.jpg', title:'The Marvels', year:2023, type:'Film', franchise:'mcu', saga:'Phase 5 (2023-2025)', releaseOrder:33, chronoOrder:67, chronoNote:'2026', director:'Nia DaCosta', cast:['Brie Larson','Teyonah Parris','Iman Vellani'], duration:'105 min', synopsis:"Carol Danvers, alias Captain Marvel, a repris son identité aux Krees tyranniques et s'est vengée de l'Intelligence Suprême. Mais les conséquences inattendues de ses actes la voient désormais porter le poids d'un univers déstabilisé. Lorsque ses fonctions l'envoient vers un trou de ver anormal lié à une révolutionnaire kree, ses pouvoirs s'entremêlent avec ceux de Kamala Khan, super-fan de Jersey City alias Ms. Marvel, et de sa nièce éloignée, désormais astronaute du S.A.B.E.R., la capitaine Monica Rambeau. Ce trio improbable doit apprendre à faire équipe pour sauver l'univers.", wikiTitle:'The Marvels'},
{ id:'loki-s2', poster:'images/posters/loki-s2.jpg', title:'Loki (Saison 2)', year:2023, type:'Série', franchise:'mcu', saga:'Phase 5 (2023-2025)', releaseOrder:47, chronoOrder:68, chronoNote:'suite immédiate', director:'Justin Benson, Aaron Moorhead', cast:['Tom Hiddleston','Owen Wilson','Sophia Di Martino'], duration:'1 saison, 6 épisodes', synopsis:"Loki reprend juste après le final choc de la première saison : le voilà plongé dans une bataille pour l'âme de la Confrérie du Temps. Avec Mobius, Hunter B-15 et une équipe de personnages nouveaux comme familiers, Loki doit naviguer dans un Multivers toujours plus vaste et dangereux, à la recherche de Sylvie, de la Juge Renslayer, de Mademoiselle Minute — et de la vérité sur ce que signifie posséder un libre arbitre et un « dessein glorieux ».", wikiTitle:'Loki season 2'},
{ id:'what-if-s2', animated:true, poster:'images/posters/what-if-s2.jpeg', title:'What If...? (Saison 2)', year:2023, type:'Série', franchise:'mcu', saga:'Phase 5 (2023-2025)', releaseOrder:54, chronoOrder:69, chronoNote:'multivers', director:'Bryan Andrews', cast:['Jeffrey Wright (narrateur)'], duration:'1 saison, 9 épisodes (animation)', synopsis:"De nouvelles explorations d'univers alternatifs, dans la continuité directe de la première saison.", wikiTitle:'What If...? season 2'},
{ id:'deadpool-wolverine', poster:'images/posters/deadpool-wolverine.jpg', title:'Deadpool & Wolverine', year:2024, type:'Film', franchise:'mcu', saga:'Phase 5 (2023-2025)', releaseOrder:34, chronoOrder:70, chronoNote:'multivers', director:'Shawn Levy', cast:['Ryan Reynolds','Hugh Jackman','Emma Corrin'], duration:'128 min', synopsis:"Wade Wilson a laissé derrière lui son passé de Deadpool aux principes moraux flexibles — jusqu'à ce qu'il se retrouve soudain à devoir se battre pour la survie de son monde, et doive à nouveau enfiler le costume, tout en convainquant un Wolverine réticent de l'aider.", wikiTitle:'Deadpool & Wolverine'},
{ id:'agatha-all-along', poster:'images/posters/agatha-all-along.jpg', title:'Agatha All Along', year:2024, type:'Série', franchise:'mcu', saga:'Phase 5 (2023-2025)', releaseOrder:49, chronoOrder:71, chronoNote:'après WandaVision', director:'Jac Schaeffer', cast:['Kathryn Hahn','Joe Locke','Aubrey Plaza'], duration:'1 saison, 9 épisodes', synopsis:"La tristement célèbre Agatha Harkness se retrouve dépouillée de ses pouvoirs après qu'un mystérieux adolescent gothique l'aide à se libérer d'un sortilège déformé. Son intérêt s'éveille lorsqu'il la supplie de l'emmener sur le légendaire Chemin des Sorcières, un parcours d'épreuves magique qui, s'il est surmonté, récompense une sorcière avec ce qui lui manque. Ensemble, Agatha et cet énigmatique adolescent rassemblent un coven de fortune et s'enfoncent sur le Chemin...", wikiTitle:'Agatha All Along'},
{ id:'what-if-s3', animated:true, poster:'images/posters/what-if-s3.jpeg', title:'What If...? (Saison 3)', year:2024, type:'Série', franchise:'mcu', saga:'Phase 5 (2023-2025)', releaseOrder:55, chronoOrder:72, chronoNote:'multivers', director:'Bryan Andrews', cast:['Jeffrey Wright (narrateur)'], duration:'1 saison, 8 épisodes (animation)', synopsis:"Une nouvelle salve d'histoires alternatives, entre nouveaux visages et retour de personnages du multivers.", wikiTitle:'What If...? season 3'},
{ id:'daredevil-born-again', poster:'images/posters/daredevil-born-again.jpeg', title:'Daredevil: Born Again (Saison 1)', year:2025, type:'Série', franchise:'mcu', saga:'Phase 5 (2023-2025)', releaseOrder:50, chronoOrder:73, chronoNote:'contemporain', director:'Various', cast:['Charlie Cox','Vincent D\'Onofrio','Ayelet Zurer'], duration:'1 saison, 9 épisodes', synopsis:"Matt Murdock, avocat aveugle aux capacités décuplées, se bat pour la justice à travers son cabinet en pleine expansion, tandis que l'ancien parrain du crime Wilson Fisk poursuit ses propres ambitions politiques à New York. Quand leurs identités passées commencent à refaire surface, les deux hommes se retrouvent sur une trajectoire de collision inévitable.", wikiTitle:'Daredevil: Born Again'},
{ id:'captain-america-brave-new-world', poster:'images/posters/captain-america-brave-new-world.jpg', title:'Captain America: Brave New World', year:2025, type:'Film', franchise:'mcu', saga:'Phase 5 (2023-2025)', releaseOrder:35, chronoOrder:74, chronoNote:'2027', director:'Julius Onah', cast:['Anthony Mackie','Harrison Ford','Danny Ramirez'], duration:'118 min', synopsis:"Après une rencontre avec le président américain nouvellement élu, Thaddeus Ross, Sam Wilson se retrouve au cœur d'un incident international. Il doit découvrir la raison d'un complot mondial machiavélique avant que le véritable cerveau de l'opération ne mette le monde entier à feu et à sang.", wikiTitle:'Captain America: Brave New World'},
{ id:'thunderbolts', poster:'images/posters/thunderbolts.jpg', title:'Thunderbolts*', year:2025, type:'Film', franchise:'mcu', saga:'Phase 5 (2023-2025)', releaseOrder:36, chronoOrder:75, chronoNote:'2027', director:'Jake Schreier', cast:['Florence Pugh','Sebastian Stan','David Harbour','Julia Louis-Dreyfus'], duration:'126 min', synopsis:"Marvel Studios réunit une équipe peu conventionnelle d'antihéros — Yelena Belova, Bucky Barnes, Red Guardian, Ghost, Taskmaster et John Walker. Pris au piège dans un traquenard mortel tendu par Valentina Allegra de Fontaine, ces exclus désabusés doivent se lancer dans une mission dangereuse qui les forcera à affronter les recoins les plus sombres de leur passé. Ce groupe dysfonctionnel va-t-il se déchirer, ou trouver la rédemption et s'unir en quelque chose de bien plus grand avant qu'il ne soit trop tard ?", wikiTitle:'Thunderbolts*'},
{ id:'fantastic-four-first-steps', poster:'images/posters/fantastic-four-first-steps.jpg', title:'Fantastic Four: First Steps', year:2025, type:'Film', franchise:'mcu', saga:'Phase 6 (2025-2027)', releaseOrder:37, chronoOrder:76, chronoNote:'Terre-828, années 1960 rétrofuturistes', director:'Matt Shakman', cast:['Pedro Pascal','Vanessa Kirby','Joseph Quinn','Ebon Moss-Bachrach'], duration:'115 min', synopsis:"Dans le décor chatoyant d'un monde rétrofuturiste inspiré des années 1960, la première famille de Marvel — Reed Richards/Mister Fantastic, Sue Storm/la Femme Invisible, Johnny Storm/la Torche Humaine et Ben Grimm/la Chose — affronte son défi le plus redoutable.", wikiTitle:'The Fantastic Four: First Steps'},
{ id:'wonder-man', title:'Wonder Man', year:2026, type:'Série', franchise:'mcu', saga:'Phase 6 (2025-2027)', releaseOrder:60, chronoOrder:77, chronoNote:'contemporain', director:'Destin Daniel Cretton (showrunner)', cast:['Yahya Abdul-Mateen II','Ben Kingsley'], duration:'1 saison, 8 épisodes', synopsis:"Simon Williams, acteur hollywoodien en devenir, peine à faire décoller sa carrière. Lors d'une rencontre fortuite avec Trevor Slattery, un acteur dont les plus grands rôles sont peut-être derrière lui, Simon apprend que le légendaire réalisateur Von Kovak prépare un remake du film de super-héros « Wonder Man ». Ces deux acteurs, à des extrémités opposées de leur carrière, poursuivent avec acharnement des rôles qui pourraient changer leur vie, tandis que le public découvre les coulisses de l'industrie du divertissement.", wikiTitle:'Wonder Man (TV series)'},
{ id:'daredevil-born-again-s2', poster:'images/posters/daredevil-born-again-s2.jpeg', title:'Daredevil: Born Again (Saison 2)', year:2026, type:'Série', franchise:'mcu', saga:'Phase 6 (2025-2027)', releaseOrder:61, chronoOrder:78, chronoNote:'suite immédiate', director:'Various', cast:['Charlie Cox','Vincent D\'Onofrio'], duration:'1 saison, 8 épisodes', synopsis:"Le maire Wilson Fisk écrase New York sous sa botte alors qu'il traque l'ennemi public numéro un : le justicier masqué de Hell's Kitchen, Daredevil. Mais sous le masque à cornes, Matt Murdock va tenter de riposter depuis l'ombre pour démanteler l'empire corrompu du Caïd et racheter sa ville. Résister. Se rebeller. Reconstruire.", wikiTitle:'Daredevil: Born Again season 2'},
{ id:'punisher-one-last-kill', poster:'images/posters/punisher-one-last-kill.jpg', title:'The Punisher: One Last Kill', year:2026, type:'Série', franchise:'mcu', saga:'Phase 6 (2025-2027)', releaseOrder:62, chronoOrder:79, chronoNote:'contemporain', director:'Reinaldo Marcus Green', cast:['Jon Bernthal'], duration:'1 spécial', synopsis:"Alors que Frank Castle cherche un sens à sa vie au-delà de la vengeance, une force inattendue le ramène dans le combat.", wikiTitle:'The Punisher: One Last Kill'},

// --- Pas encore placés dans l'ordre officiel Disney+ (animés hors continuité
//     confirmée, ou pas encore sortis au 22/08/2026) — voir FRANCHISE_NOTES.
{ id:'your-friendly-neighborhood-spiderman', animated:true, poster:'images/posters/your-friendly-neighborhood-spiderman.png', title:'Your Friendly Neighborhood Spider-Man', year:2025, type:'Série', franchise:'mcu', saga:'Phase 6 (2025-2027)', releaseOrder:56, chronoOrder:80, chronoNote:'contemporain, débuts de Peter Parker', director:'Jeff Trammell (showrunner)', cast:['Hudson Thames','Eugene Byrd','Grace Song','Zeno Robinson','Hugh Dancy','Charlie Cox'], duration:'1 saison, 10 épisodes (animation)', synopsis:"Suit Peter Parker sur le chemin qui fait de lui un héros, avec un parcours inédit et un style qui célèbre les racines du personnage dans ses premiers comics.", wikiTitle:'Your Friendly Neighborhood Spider-Man'},
{ id:'visionquest', poster:'images/posters/visionquest.jpg', title:'VisionQuest', year:2026, type:'Série', franchise:'mcu', saga:'Phase 6 (2025-2027)', releaseOrder:64, chronoOrder:81, chronoNote:'suite de WandaVision et Agatha All Along', director:'Terry Matalas e.a.', cast:['Paul Bettany','James Spader','Emily Hampshire','James D\'Arcy'], duration:'1 saison, 8 épisodes', synopsis:"Vision, redevenu lui-même mais dépourvu de ses souvenirs avec Wanda, part en quête de son identité — et croise la route d'un vieil ennemi, Ultron.", wikiTitle:'VisionQuest', upcoming:true},
{ id:'spiderman-brand-new-day', poster:'images/posters/spiderman-brand-new-day.jpg', title:'Spider-Man: Brand New Day', year:2026, type:'Film', franchise:'mcu', saga:'Phase 6 (2025-2027)', releaseOrder:63, chronoOrder:82, chronoNote:'plusieurs années après No Way Home', director:'Destin Daniel Cretton', cast:['Tom Holland','Zendaya','Sadie Sink','Jacob Batalon','Jon Bernthal','Florence Pugh','Marisa Tomei','Mark Ruffalo'], duration:'non communiquée', synopsis:"C'est un TOUT NOUVEAU JOUR pour Peter Parker. Combattre le crime à plein temps en tant que Spider-Man dans un monde qui ne se souvient plus de lui — et la pression de voir ses anciens amis avancer sans lui — provoque chez Peter un changement qu'il n'est peut-être pas en mesure de contrôler. Mais cette transformation pourrait aussi être la seule chose capable d'arrêter une nouvelle menace choquante pour la ville et ceux qu'il aime : un puissant vilain que personne ne peut même voir.", wikiTitle:'Spider-Man: Brand New Day'},
{ id:'avengers-doomsday', poster:'images/posters/avengers-doomsday.jpg', title:'Avengers: Doomsday', year:2026, type:'Film', franchise:'mcu', saga:'Phase 6 (2025-2027)', releaseOrder:65, chronoOrder:83, chronoNote:'culmination de la Saga du Multivers', director:'Anthony et Joe Russo', cast:['Robert Downey Jr. (Docteur Fatalis)','vaste casting multivers encore tenu secret'], duration:'non communiquée', synopsis:"Le retour des frères Russo aux commandes d'un nouvel Avengers réunissant un casting multivers tentaculaire — avec Robert Downey Jr. de retour dans la peau du Docteur Fatalis.", wikiTitle:'Avengers: Doomsday', upcoming:true},
{ id:'avengers-secret-wars', title:'Avengers: Secret Wars', year:2027, type:'Film', franchise:'mcu', saga:'Phase 6 (2025-2027)', releaseOrder:66, chronoOrder:84, chronoNote:'aboutissement de la Saga du Multivers', director:'Anthony et Joe Russo', cast:['Casting non officiellement dévoilé'], duration:'non communiquée', synopsis:"Le film censé clore la « Saga du Multivers » sous la direction des frères Russo — l'intrigue reste, à ce jour, tenue secrète.", wikiTitle:'Avengers: Secret Wars', upcoming:true},

// --------------------------------------------------------------- X-MEN ---
{ id:'xmen-first-class', poster:'images/posters/xmen-first-class.jpg', title:'X-Men: First Class', year:2011, type:'Film', franchise:'xmen', saga:'Trilogie First Class', releaseOrder:5, chronoOrder:1, chronoNote:'1962', director:'Matthew Vaughn', cast:['James McAvoy','Michael Fassbender','Jennifer Lawrence','Kevin Bacon'], duration:'132 min', synopsis:"En pleine Guerre froide, Charles Xavier et Erik Lensherr forment la première équipe de mutants, avant que leurs idéaux ne les séparent à jamais.", wikiTitle:'X-Men: First Class'},
{ id:'xmen-days-future-past', poster:'images/posters/xmen-days-future-past.jpg', title:'X-Men: Days of Future Past', year:2014, type:'Film', franchise:'xmen', saga:'Trilogie First Class', releaseOrder:7, chronoOrder:2, chronoNote:'1973 / 2023', director:'Bryan Singer', cast:['Hugh Jackman','James McAvoy','Michael Fassbender','Patrick Stewart'], duration:'132 min', synopsis:"Wolverine est envoyé dans le passé pour empêcher un événement qui mènera à un futur dystopique où les Sentinelles exterminent les mutants.", wikiTitle:'X-Men: Days of Future Past'},
{ id:'xmen-apocalypse', poster:'images/posters/xmen-apocalypse.jpg', title:'X-Men: Apocalypse', year:2016, type:'Film', franchise:'xmen', saga:'Trilogie First Class', releaseOrder:9, chronoOrder:3, chronoNote:'1983', director:'Bryan Singer', cast:['James McAvoy','Michael Fassbender','Jennifer Lawrence','Oscar Isaac'], duration:'144 min', synopsis:"Le tout premier mutant, En Sabah Nur, se réveille après des millénaires et recrute quatre cavaliers pour raser la civilisation moderne.", wikiTitle:'X-Men: Apocalypse'},
{ id:'dark-phoenix', poster:'images/posters/dark-phoenix.png', title:'Dark Phoenix', year:2019, type:'Film', franchise:'xmen', saga:'Trilogie First Class', releaseOrder:12, chronoOrder:4, chronoNote:'1992', director:'Simon Kinberg', cast:['Sophie Turner','James McAvoy','Michael Fassbender','Jennifer Lawrence'], duration:'113 min', synopsis:"Jean Grey est submergée par une force cosmique qui réveille ses pouvoirs les plus destructeurs et la fait basculer du côté obscur.", wikiTitle:'Dark Phoenix (film)'},
{ id:'new-mutants', poster:'images/posters/new-mutants.jpeg', title:'The New Mutants', year:2020, type:'Film', franchise:'xmen', saga:'Spin-off', releaseOrder:13, chronoOrder:5, chronoNote:'ambigu, proche du présent', director:'Josh Boone', cast:['Maisie Williams','Anya Taylor-Joy','Charlie Heaton'], duration:'98 min', synopsis:"Cinq jeunes mutants internés dans un hôpital psychiatrique isolé découvrent que leurs pouvoirs pourraient bien être la clé de leur perte.", wikiTitle:'The New Mutants (film)'},
{ id:'xmen-origins-wolverine', poster:'images/posters/xmen-origins-wolverine.jpg', title:'X-Men Origins: Wolverine', year:2009, type:'Film', franchise:'xmen', saga:'Wolverine', releaseOrder:4, chronoOrder:6, chronoNote:'de la guerre de Sécession à 1979', director:'Gavin Hood', cast:['Hugh Jackman','Liev Schreiber','Ryan Reynolds'], duration:'107 min', synopsis:"Retour sur le passé tourmenté de Logan, sa relation fraternelle avec Victor Creed et le programme Arme X qui lui a donné son squelette d'adamantium.", wikiTitle:'X-Men Origins: Wolverine'},
{ id:'xmen', poster:'images/posters/xmen.jpg', title:'X-Men', year:2000, type:'Film', franchise:'xmen', saga:'Trilogie originale', releaseOrder:1, chronoOrder:7, chronoNote:'2000', director:'Bryan Singer', cast:['Hugh Jackman','Patrick Stewart','Ian McKellen','Halle Berry'], duration:'104 min', synopsis:"Wolverine et Rogue rejoignent l'école du Professeur Xavier, alors qu'Erik Lensherr (Magnéto) prépare un plan pour « muter » les dirigeants mondiaux.", wikiTitle:'X-Men (film)'},
{ id:'xmen-2', poster:'images/posters/xmen-2.jpg', title:'X2', year:2003, type:'Film', franchise:'xmen', saga:'Trilogie originale', releaseOrder:2, chronoOrder:8, chronoNote:'2003', director:'Bryan Singer', cast:['Hugh Jackman','Patrick Stewart','Ian McKellen','Alan Cumming'], duration:'134 min', synopsis:"Le colonel Stryker, animé par une haine viscérale des mutants, attaque l'école de Xavier et force alliés et ennemis à s'unir.", wikiTitle:'X2 (film)'},
{ id:'xmen-last-stand', poster:'images/posters/xmen-last-stand.jpg', title:'X-Men: L\'Affrontement final', year:2006, type:'Film', franchise:'xmen', saga:'Trilogie originale', releaseOrder:3, chronoOrder:9, chronoNote:'2006', director:'Brett Ratner', cast:['Hugh Jackman','Halle Berry','Ian McKellen','Famke Janssen'], duration:'104 min', synopsis:"Un « remède » censé annuler la mutation divise la communauté mutante, tandis que Jean Grey renaît sous la forme dévastatrice de Phoenix.", wikiTitle:'X-Men: The Last Stand'},
{ id:'deadpool', poster:'images/posters/deadpool.png', title:'Deadpool', year:2016, type:'Film', franchise:'xmen', saga:'Deadpool', releaseOrder:8, chronoOrder:10, chronoNote:'contemporain (avec ruptures du 4e mur)', director:'Tim Miller', cast:['Ryan Reynolds','Morena Baccarin','Ed Skrein'], duration:'108 min', synopsis:"Wade Wilson, mercenaire cynique, devient le régénérant et irrévérencieux Deadpool après une expérience clandestine qui dérape.", wikiTitle:'Deadpool (film)'},
{ id:'deadpool-2', poster:'images/posters/deadpool-2.jpg', title:'Deadpool 2', year:2018, type:'Film', franchise:'xmen', saga:'Deadpool', releaseOrder:11, chronoOrder:11, chronoNote:'contemporain', director:'David Leitch', cast:['Ryan Reynolds','Josh Brolin','Zazie Beetz'], duration:'119 min', synopsis:"Deadpool forme la X-Force pour protéger un jeune mutant menacé par Cable, un soldat venu du futur.", wikiTitle:'Deadpool 2'},
{ id:'the-wolverine', poster:'images/posters/the-wolverine.jpg', title:'Wolverine: Le Combat de l\'immortel', year:2013, type:'Film', franchise:'xmen', saga:'Wolverine', releaseOrder:6, chronoOrder:12, chronoNote:'2013', director:'James Mangold', cast:['Hugh Jackman','Tao Okamoto','Rila Fukushima'], duration:'126 min', synopsis:"Invité au Japon par un homme qu'il a sauvé jadis, Logan se retrouve mêlé à un complot autour d'un procédé pouvant le rendre mortel.", wikiTitle:'The Wolverine (film)'},
{ id:'logan', poster:'images/posters/logan.jpg', title:'Logan', year:2017, type:'Film', franchise:'xmen', saga:'Wolverine', releaseOrder:10, chronoOrder:13, chronoNote:'2029', director:'James Mangold', cast:['Hugh Jackman','Patrick Stewart','Dafne Keen'], duration:'137 min', synopsis:"En 2029, un Logan vieilli et affaibli s'occupe d'un Charles Xavier malade, jusqu'à ce qu'une jeune mutante traquée bouleverse leur exil.", wikiTitle:'Logan (film)'},
{ id:'xmen-97-s1', animated:true, poster:'images/posters/xmen-97-s1.png', title:'X-Men \'97 (Saison 1)', year:2024, type:'Série', franchise:'xmen', saga:"X-Men '97 (animation)", releaseOrder:14, chronoOrder:100, chronoNote:'continuité animée distincte, suite directe de 1992', director:'Jake Castorena (réalisateur superviseur), Beau DeMayo (scénariste, saison 1)', cast:['Ray Chase','Jennifer Hale','Cal Dodd','Alison Sealy-Smith','Lenore Zann','George Buza'], duration:'1 saison, 10 épisodes (animation)', synopsis:"Suite directe de « X-Men : la Série animée » des années 1990 : le rêve de Charles Xavier est mis à rude épreuve après sa disparition, forçant les X-Men à se redéfinir.", wikiTitle:"X-Men '97"},
{ id:'xmen-97-s2', animated:true, poster:'images/posters/xmen-97-s2.png', title:'X-Men \'97 (Saison 2)', year:2026, type:'Série', franchise:'xmen', saga:"X-Men '97 (animation)", releaseOrder:15, chronoOrder:101, chronoNote:'suite immédiate', director:'Jake Castorena (réalisateur superviseur)', cast:['Ray Chase','Jennifer Hale','Cal Dodd','Alison Sealy-Smith','Lenore Zann','George Buza'], duration:'1 saison (animation)', synopsis:"Dispersés à travers le temps après le season finale de la saison 1, les X-Men doivent retrouver le chemin du présent tout en affrontant le retour d'Apocalypse.", wikiTitle:"X-Men '97"},

// ------------------------------------------------------- SPIDER-MAN (Sony) ---
{ id:'spiderman-2002', poster:'images/posters/spiderman-2002.jpg', title:'Spider-Man', year:2002, type:'Film', franchise:'sony', saga:'Trilogie Raimi', releaseOrder:1, chronoOrder:1, chronoNote:'2002', director:'Sam Raimi', cast:['Tobey Maguire','Kirsten Dunst','Willem Dafoe'], duration:'121 min', synopsis:"Mordu par une araignée génétiquement modifiée, le lycéen Peter Parker acquiert des pouvoirs et doit affronter le Bouffon Vert.", wikiTitle:'Spider-Man (2002 film)'},
{ id:'spiderman-2-2004', poster:'images/posters/spiderman-2-2004.jpg', title:'Spider-Man 2', year:2004, type:'Film', franchise:'sony', saga:'Trilogie Raimi', releaseOrder:2, chronoOrder:2, chronoNote:'2004', director:'Sam Raimi', cast:['Tobey Maguire','Kirsten Dunst','Alfred Molina'], duration:'127 min', synopsis:"Épuisé par le poids de sa double vie, Peter Parker envisage d'abandonner le costume, jusqu'à l'apparition du Docteur Octopus.", wikiTitle:'Spider-Man 2'},
{ id:'spiderman-3-2007', poster:'images/posters/spiderman-3-2007.jpg', title:'Spider-Man 3', year:2007, type:'Film', franchise:'sony', saga:'Trilogie Raimi', releaseOrder:3, chronoOrder:3, chronoNote:'2007', director:'Sam Raimi', cast:['Tobey Maguire','Kirsten Dunst','Topher Grace','Thomas Haden Church'], duration:'139 min', synopsis:"Un symbiote extraterrestre s'attache à Peter Parker et exacerbe ses pires travers, tandis qu'Harry Osborn et l'Homme-Sable entrent en scène.", wikiTitle:'Spider-Man 3'},
{ id:'amazing-spiderman', poster:'images/posters/amazing-spiderman.jpg', title:'The Amazing Spider-Man', year:2012, type:'Film', franchise:'sony', saga:'Trilogie Amazing', releaseOrder:4, chronoOrder:4, chronoNote:'2012', director:'Marc Webb', cast:['Andrew Garfield','Emma Stone','Rhys Ifans'], duration:'136 min', synopsis:"Peter Parker enquête sur la disparition de son père et affronte le Lézard, ancien collègue devenu monstrueux, au sein d'Oscorp.", wikiTitle:'The Amazing Spider-Man (2012 film)'},
{ id:'amazing-spiderman-2', poster:'images/posters/amazing-spiderman-2.jpg', title:'The Amazing Spider-Man 2: Le Destin d\'un héros', year:2014, type:'Film', franchise:'sony', saga:'Trilogie Amazing', releaseOrder:5, chronoOrder:5, chronoNote:'2014', director:'Marc Webb', cast:['Andrew Garfield','Emma Stone','Jamie Foxx','Dane DeHaan'], duration:'142 min', synopsis:"Spider-Man doit affronter Electro et un Harry Osborn devenu Bouffon Vert, tout en portant le poids d'une prophétie funeste.", wikiTitle:'The Amazing Spider-Man 2'},
{ id:'venom', poster:'images/posters/venom.png', title:'Venom', year:2018, type:'Film', franchise:'sony', saga:'Sony\'s Spider-Man Universe', releaseOrder:6, chronoOrder:6, chronoNote:'2018', director:'Ruben Fleischer', cast:['Tom Hardy','Michelle Williams','Riz Ahmed'], duration:'112 min', synopsis:"Le journaliste Eddie Brock fusionne avec un symbiote extraterrestre et devient Venom, une créature aussi dangereuse que protectrice.", wikiTitle:'Venom (2018 film)'},
{ id:'venom-carnage', poster:'images/posters/venom-carnage.jpg', title:'Venom: Let There Be Carnage', year:2021, type:'Film', franchise:'sony', saga:'Sony\'s Spider-Man Universe', releaseOrder:7, chronoOrder:7, chronoNote:'2021', director:'Andy Serkis', cast:['Tom Hardy','Woody Harrelson','Michelle Williams'], duration:'97 min', synopsis:"Eddie Brock doit affronter Cletus Kasady, tueur en série devenu hôte du symbiote Carnage, encore plus violent que Venom.", wikiTitle:'Venom: Let There Be Carnage'},
{ id:'morbius', poster:'images/posters/morbius.jpg', title:'Morbius', year:2022, type:'Film', franchise:'sony', saga:'Sony\'s Spider-Man Universe', releaseOrder:8, chronoOrder:8, chronoNote:'2022', director:'Daniel Espinosa', cast:['Jared Leto','Matt Smith','Adria Arjona'], duration:'104 min', synopsis:"Atteint d'une maladie rare, le biochimiste Michael Morbius s'inflige un traitement expérimental qui le transforme en vampire vivant.", wikiTitle:'Morbius (film)'},
{ id:'madame-web', poster:'images/posters/madame-web.png', title:'Madame Web', year:2024, type:'Film', franchise:'sony', saga:'Sony\'s Spider-Man Universe', releaseOrder:9, chronoOrder:9, chronoNote:'2003', director:'S.J. Clarkson', cast:['Dakota Johnson','Sydney Sweeney','Isabela Merced'], duration:'116 min', synopsis:"Une ambulancière de New York développe des pouvoirs de précognition et se lance dans la protection de trois jeunes femmes qu'elle voit menacées.", wikiTitle:'Madame Web'},
{ id:'kraven', poster:'images/posters/kraven.jpg', title:'Kraven the Hunter', year:2024, type:'Film', franchise:'sony', saga:'Sony\'s Spider-Man Universe', releaseOrder:10, chronoOrder:10, chronoNote:'origine, plusieurs décennies', director:'J.C. Chandor', cast:['Aaron Taylor-Johnson','Russell Crowe','Ariana DeBose'], duration:'127 min', synopsis:"Sergei Kravinoff devient le chasseur le plus redouté du monde après une expérience surnaturelle qui décuple ses capacités.", wikiTitle:'Kraven the Hunter (film)'},
{ id:'venom-last-dance', poster:'images/posters/venom-last-dance.jpg', title:'Venom: The Last Dance', year:2024, type:'Film', franchise:'sony', saga:'Sony\'s Spider-Man Universe', releaseOrder:11, chronoOrder:11, chronoNote:'2024', director:'Kelly Marcel', cast:['Tom Hardy','Chiwetel Ejiofor','Juno Temple'], duration:'109 min', synopsis:"Traqués par les forces terrestres et un ennemi venu de la planète des symbiotes, Eddie et Venom vivent leur dernière danse.", wikiTitle:'Venom: The Last Dance'},
{ id:'spiderman-into-spiderverse', animated:true, poster:'images/posters/spiderman-into-spiderverse.png', title:'Spider-Man: Into the Spider-Verse', year:2018, type:'Film', franchise:'sony', saga:'Spider-Verse (animation)', releaseOrder:12, chronoOrder:12, chronoNote:'2018 (Terre-1610)', director:'Bob Persichetti, Peter Ramsey, Rodney Rothman', cast:['Shameik Moore','Jake Johnson','Hailee Steinfeld','Mahershala Ali','Liev Schreiber'], duration:'117 min (animation)', synopsis:"Miles Morales, jeune lycéen de Brooklyn mordu par une araignée radioactive, doit apprendre à devenir Spider-Man aux côtés de variantes du héros venues d'autres dimensions.", wikiTitle:'Spider-Man: Into the Spider-Verse'},
{ id:'spiderman-across-spiderverse', animated:true, poster:'images/posters/spiderman-across-spiderverse.jpg', title:'Spider-Man: Across the Spider-Verse', year:2023, type:'Film', franchise:'sony', saga:'Spider-Verse (animation)', releaseOrder:13, chronoOrder:13, chronoNote:'peu après le premier film', director:'Joaquim Dos Santos, Kemp Powers, Justin K. Thompson', cast:['Shameik Moore','Hailee Steinfeld','Jake Johnson','Oscar Isaac','Issa Rae'], duration:'140 min (animation)', synopsis:"Miles Morales est propulsé à travers le multivers et rencontre une société secrète de Spider-Héros, la Société de l'Araignée, dont les règles s'opposent radicalement à sa vision de l'héroïsme.", wikiTitle:'Spider-Man: Across the Spider-Verse'},
{ id:'spiderman-beyond-spiderverse', animated:true, poster:'images/posters/spiderman-beyond-spiderverse.jpg', title:'Spider-Man: Beyond the Spider-Verse', year:2027, type:'Film', franchise:'sony', saga:'Spider-Verse (animation)', releaseOrder:14, chronoOrder:14, chronoNote:'suite directe', director:'Joaquim Dos Santos, Kemp Powers, Justin K. Thompson (attendu)', cast:['Shameik Moore','Hailee Steinfeld'], duration:'non communiquée', synopsis:"Conclusion annoncée de la trilogie Spider-Verse, plusieurs fois repoussée depuis 2024 — les réalisateurs assurent vouloir prendre le temps de faire de ce film la conclusion que la saga mérite.", wikiTitle:'Spider-Man: Beyond the Spider-Verse', upcoming:true},

// ------------------------------------------------------- PRÉ-MCU (classic) ---
{ id:'blade-1998', poster:'images/posters/blade-1998.jpg', title:'Blade', year:1998, type:'Film', franchise:'classic', saga:'Trilogie Blade', releaseOrder:1, chronoOrder:1, chronoNote:'1998', director:'Stephen Norrington', cast:['Wesley Snipes','Stephen Dorff','Kris Kristofferson',"N'Bushe Wright"], duration:'120 min', synopsis:"Mi-homme mi-vampire, Blade traque et extermine les vampires qui infestent les grandes villes, bien décidé à venger sa mère mordue avant sa naissance.", wikiTitle:'Blade (1998 film)'},
{ id:'blade-2', poster:'images/posters/blade-2.jpg', title:'Blade II', year:2002, type:'Film', franchise:'classic', saga:'Trilogie Blade', releaseOrder:2, chronoOrder:2, chronoNote:'2002', director:'Guillermo del Toro', cast:['Wesley Snipes','Kris Kristofferson','Ron Perlman','Leonor Varela'], duration:'117 min', synopsis:"Blade s'allie temporairement à ses ennemis vampires pour affronter une menace commune : les Reapers, une souche mutante et incontrôlable.", wikiTitle:'Blade II'},
{ id:'blade-trinity', poster:'images/posters/blade-trinity.jpg', title:'Blade: Trinity', year:2004, type:'Film', franchise:'classic', saga:'Trilogie Blade', releaseOrder:3, chronoOrder:3, chronoNote:'2004', director:'David S. Goyer', cast:['Wesley Snipes','Kris Kristofferson','Jessica Biel','Ryan Reynolds'], duration:'113 min', synopsis:"Traqué et accusé de meurtre, Blade doit s'allier à une nouvelle génération de chasseurs de vampires pour affronter Dracula lui-même, réveillé par ses ennemis.", wikiTitle:'Blade: Trinity'},
{ id:'daredevil-2003', poster:'images/posters/daredevil-2003.jpg', title:'Daredevil', year:2003, type:'Film', franchise:'classic', saga:'Daredevil / Elektra', releaseOrder:4, chronoOrder:4, chronoNote:'2003', director:'Mark Steven Johnson', cast:['Ben Affleck','Jennifer Garner','Colin Farrell','Michael Clarke Duncan'], duration:'103 min', synopsis:"Avocat aveugle de jour, justicier acrobate de nuit, Matt Murdock affronte le tueur à gages Bullseye et l'énigmatique Kingpin dans les rues de New York.", wikiTitle:'Daredevil (film)'},
{ id:'elektra-2005', poster:'images/posters/elektra-2005.jpg', title:'Elektra', year:2005, type:'Film', franchise:'classic', saga:'Daredevil / Elektra', releaseOrder:5, chronoOrder:5, chronoNote:'2005', director:'Rob Bowman', cast:['Jennifer Garner','Goran Višnjić','Kirsten Prout'], duration:'97 min', synopsis:"Ressuscitée après sa mort dans Daredevil, la tueuse à gages Elektra Natchios est chargée d'un contrat qui va la pousser à protéger, plutôt qu'éliminer, sa cible.", wikiTitle:'Elektra (2005 film)'},
{ id:'fantastic-four-2005', poster:'images/posters/fantastic-four-2005.jpg', title:'Fantastic Four', year:2005, type:'Film', franchise:'classic', saga:'Fantastic Four (Fox, années 2000)', releaseOrder:6, chronoOrder:6, chronoNote:'2005', director:'Tim Story', cast:['Ioan Gruffudd','Jessica Alba','Chris Evans','Michael Chiklis'], duration:'106 min', synopsis:"Une exposition à une tempête cosmique dote quatre astronautes de pouvoirs extraordinaires, qu'ils devront apprendre à maîtriser pour affronter leur ancien collègue devenu Docteur Fatalis.", wikiTitle:'Fantastic Four (2005 film)'},
{ id:'fantastic-four-silver-surfer', poster:'images/posters/fantastic-four-silver-surfer.jpg', title:'Fantastic Four: Rise of the Silver Surfer', year:2007, type:'Film', franchise:'classic', saga:'Fantastic Four (Fox, années 2000)', releaseOrder:7, chronoOrder:7, chronoNote:'2007', director:'Tim Story', cast:['Ioan Gruffudd','Jessica Alba','Chris Evans','Michael Chiklis','Doug Jones'], duration:'92 min', synopsis:"L'arrivée sur Terre du mystérieux Silver Surfer, héraut d'une menace planétaire nommée Galactus, contraint les Quatre Fantastiques à faire équipe avec Docteur Fatalis.", wikiTitle:'Fantastic Four: Rise of the Silver Surfer'},
{ id:'ghost-rider-2007', poster:'images/posters/ghost-rider-2007.jpg', title:'Ghost Rider', year:2007, type:'Film', franchise:'classic', saga:'Ghost Rider', releaseOrder:8, chronoOrder:8, chronoNote:'2007', director:'Mark Steven Johnson', cast:['Nicolas Cage','Eva Mendes','Wes Bentley'], duration:'114 min', synopsis:"Le cascadeur Johnny Blaze, ayant vendu son âme au diable, se transforme la nuit en Ghost Rider, un justicier au crâne enflammé chargé de traquer les âmes damnées.", wikiTitle:'Ghost Rider (2007 film)'},
{ id:'ghost-rider-spirit-vengeance', poster:'images/posters/ghost-rider-spirit-vengeance.jpg', title:'Ghost Rider: L\'Esprit de vengeance', year:2012, type:'Film', franchise:'classic', saga:'Ghost Rider', releaseOrder:9, chronoOrder:9, chronoNote:'2012', director:'Mark Neveldine, Brian Taylor', cast:['Nicolas Cage','Idris Elba','Violante Placido'], duration:'96 min', synopsis:"Réfugié en Europe de l'Est pour échapper à sa malédiction, Johnny Blaze est recruté par une secte pour protéger un jeune garçon convoité par le diable en personne.", wikiTitle:'Ghost Rider: Spirit of Vengeance'},
{ id:'punisher-2004', poster:'images/posters/punisher-2004.jpg', title:'The Punisher', year:2004, type:'Film', franchise:'classic', saga:'Punisher', releaseOrder:10, chronoOrder:10, chronoNote:'2004', director:'Jonathan Hensleigh', cast:['Thomas Jane','John Travolta','Rebecca Romijn'], duration:'124 min', synopsis:"Après le massacre de toute sa famille sur ordre d'un parrain de la mafia, l'agent du FBI Frank Castle abandonne tout pour devenir le Punisher et se venger méthodiquement.", wikiTitle:'The Punisher (2004 film)'},
{ id:'punisher-war-zone', poster:'images/posters/punisher-war-zone.jpg', title:'Punisher: War Zone', year:2008, type:'Film', franchise:'classic', saga:'Punisher', releaseOrder:11, chronoOrder:11, chronoNote:'2008 (reboot, non lié au film de 2004)', director:'Lexi Alexander', cast:['Ray Stevenson','Dominic West','Doug Hutchison'], duration:'107 min', synopsis:"Nouveau reboot du personnage : Frank Castle, devenu un redoutable justicier, doit affronter Jigsaw, un ancien mafieux défiguré bien décidé à se venger.", wikiTitle:'Punisher: War Zone'},
{ id:'fantastic-four-2015', poster:'images/posters/fantastic-four-2015.jpg', title:'Les 4 Fantastiques', year:2015, type:'Film', franchise:'classic', saga:'Fantastic Four (reboot 2015)', releaseOrder:12, chronoOrder:12, chronoNote:'2015 (continuité indépendante)', director:'Josh Trank', cast:['Miles Teller','Kate Mara','Michael B. Jordan','Jamie Bell'], duration:'100 min', synopsis:"Reboot sombre à la production chaotique : quatre jeunes scientifiques acquièrent des pouvoirs après un accident survenu lors d'un voyage vers une dimension parallèle.", wikiTitle:'Fantastic Four (2015 film)'},

];

// Libellés lisibles pour chaque franchise
const FRANCHISE_LABELS = {
  mcu: 'MCU',
  xmen: 'X-Men (Fox)',
  sony: 'Spider-Man (Sony)',
  netflix: 'Netflix',
  classic: 'Pré-MCU (1998-2015)'
};

// Pour l'onglet "MCU" de la page Chronologie : quelles franchises afficher
// ensemble sur la même échelle de chronoOrder (Netflix y est fusionné,
// conformément à l'ordre officiel Disney+). Les autres onglets restent
// filtrés sur leur seule franchise.
const CHRONO_GROUPS = {
  mcu: ['mcu', 'netflix'],
  xmen: ['xmen'],
  sony: ['sony'],
  netflix: ['netflix'],
  classic: ['classic']
};

const FRANCHISE_NOTES = {
  mcu: "Univers cinématographique Marvel porté par Marvel Studios depuis 2008. Cet ordre reproduit tel quel L'ORDRE CHRONOLOGIQUE OFFICIEL publié par Marvel/Disney+ (« See the Complete MCU Timeline on Disney+ », marvel.com, mis à jour le 02/06/2026) : films, séries, spéciaux ET les 5 courts-métrages « One-Shot » — et il entrelace désormais les séries Netflix (badge « Netflix » conservé sur chaque fiche). Les 5 derniers titres de la liste (Your Friendly Neighborhood Spider-Man, VisionQuest, Spider-Man: Brand New Day, Avengers: Doomsday, Avengers: Secret Wars) ne figurent pas encore dans le « Complete Timeline » officiel — soit parce qu'ils ne sont pas encore sortis au 22/08/2026, soit parce que leur statut de continuité (cas de la série animée) reste incertain — et sont donc placés à la suite par déduction.",
  xmen: "Continuité lancée par la Fox en 2000, largement indépendante du MCU jusqu'à sa fusion via Deadpool & Wolverine (2024). La chronologie interne est notoirement incohérente d'un film à l'autre (âges des personnages, événements contradictoires) : l'ordre proposé est celui généralement admis par les fans. X-Men '97, bien que produit par Marvel Animation, est une continuité animée à part — suite directe de la série des années 1990 — non reliée aux films : elle apparaît volontairement à la fin de la liste.",
  sony: "Univers cinématographique de Sony autour de Spider-Man : QUATRE blocs bien distincts et non reliés entre eux — la trilogie Raimi, la duologie Amazing, le « Sony's Spider-Man Universe » centré sur Venom, et la trilogie animée Spider-Verse (sa propre continuité multivers). L'ordre proposé suit la chronologie interne au sein de chaque bloc, dans l'ordre où les blocs sont apparus.",
  netflix: "Séries produites par Marvel Television pour Netflix (2015-2019), partageant un même univers new-yorkais culminant dans le crossover The Defenders. Officiellement, Disney+ les entrelace désormais avec les films du MCU (voir l'onglet MCU) ; cette vue isolée reprend le même ordre, mais filtré aux seules séries Netflix, pratique pour qui veut juste enchaîner le « coin » new-yorkais.",
  classic: "Avant même la création de Marvel Studios (2005), plusieurs héros Marvel ont eu droit à leurs propres films chez d'autres studios (New Line, 20th Century Fox, Sony/Columbia, Lionsgate/Artisan), sans aucun lien entre eux. Regroupés ici par commodité : ce sont en réalité une demi-douzaine de mini-continuités totalement indépendantes (Blade, Daredevil/Elektra, Fantastic Four 2005-2007, Ghost Rider, Punisher, et le reboot Fantastic Four de 2015)."
};
