// ============================================================================
// MARVEL_DATA — base de données du site
// Chaque entrée = une fiche (film ou série).
// franchise: 'mcu' | 'xmen' | 'sony' | 'netflix' | 'classic'
// releaseOrder : ordre de sortie réel dans sa franchise
// chronoOrder  : position dans l'ORDRE DE VISIONNAGE CONSEILLÉ POUR SUIVRE
//                L'HISTOIRE (chronologie interne, pas les dates de sortie).
//                Pour le MCU, cet ordre reproduit tel quel l'ordre chronologique
//                OFFICIEL publié par Marvel/Disney+ (page "See the Complete MCU
//                Timeline on Disney+", marvel.com, mise à jour le 02/06/2026),
//                qui entrelace désormais les séries Netflix avec les films —
//                d'où franchise:'netflix' MAIS un chronoOrder sur la même
//                échelle que 'mcu'. Les 4 titres non encore placés par Disney+
//                (à venir ou animés hors continuité officielle) sont ajoutés
//                à la suite, avec une note dans FRANCHISE_NOTES.
// upcoming     : true si l'œuvre n'est pas encore sortie (au 22/08/2026)
// wikiTitle    : titre EXACT de la page Wikipédia en anglais, utilisé pour
//                aller chercher l'affiche via l'API et faire le lien externe.
//                Chaque wikiTitle de ce fichier a été vérifié individuellement
//                contre l'API Wikipédia (aucune redirection vers une page
//                d'homonymie, aucune 404).
// ============================================================================

const MARVEL_DATA = [

// ------------------------------------------------------------------ MCU ---
// Ordre 1 à 79 : reproduit l'ordre chronologique officiel Marvel/Disney+.
{ id:'eyes-of-wakanda', poster:'images/posters/eyes-of-wakanda.jpg', title:'Eyes of Wakanda', year:2025, type:'Série', franchise:'mcu', saga:'Phase 6', releaseOrder:58, chronoOrder:1, chronoNote:"à travers l'histoire du Wakanda", director:'Todd Harris (showrunner)', cast:['Voix multiples (Marvel Animation)'], duration:'1 saison, 4 épisodes (animation)', synopsis:"Anthologie retraçant, à différentes époques de l'histoire du Wakanda, les missions de guerriers d'élite envoyés à travers le monde pour récupérer des reliques en vibranium dérobées.", wikiTitle:'Eyes of Wakanda'},
{ id:'captain-america-first-avenger', poster:'images/posters/captain-america-first-avenger.jpg', title:'Captain America: First Avenger', year:2011, type:'Film', franchise:'mcu', saga:'Phase 1', releaseOrder:5, chronoOrder:2, chronoNote:'1942-1945', director:'Joe Johnston', cast:['Chris Evans','Hayley Atwell','Sebastian Stan','Tommy Lee Jones','Hugo Weaving'], duration:'124 min', synopsis:"Pendant la Seconde Guerre mondiale, Steve Rogers, jeune homme frêle mais courageux, devient le super-soldat Captain America pour combattre Hydra, la branche scientifique nazie.", wikiTitle:'Captain America: The First Avenger'},
{ id:'oneshot-agent-carter', poster:'images/posters/oneshot-agent-carter.jpg', title:'Marvel One-Shot: Agent Carter', year:2013, type:'Court-métrage', franchise:'mcu', saga:'One-Shots', releaseOrder:67, chronoOrder:3, chronoNote:'1946', director:'Louis D\'Esposito', cast:['Hayley Atwell','Dominic Cooper'], duration:'~15 min (bonus du Blu-ray Iron Man 3)', synopsis:"Reléguée à des tâches administratives par ses collègues masculins du SSR, Peggy Carter part en mission solo pour prouver sa valeur — court-métrage qui posera les bases de la série Agent Carter.", wikiTitle:'Agent Carter (film)'},
{ id:'captain-marvel', poster:'images/posters/captain-marvel.jpg', title:'Captain Marvel', year:2019, type:'Film', franchise:'mcu', saga:'Phase 3', releaseOrder:21, chronoOrder:4, chronoNote:'1995', director:'Anna Boden, Ryan Fleck', cast:['Brie Larson','Samuel L. Jackson','Ben Mendelsohn'], duration:'123 min', synopsis:"En 1995, Carol Danvers, pilote devenue guerrière kree, découvre son passé terrien et son véritable pouvoir.", wikiTitle:'Captain Marvel (film)'},
{ id:'iron-man', poster:'images/posters/iron-man.jpg', title:'Iron Man', year:2008, type:'Film', franchise:'mcu', saga:'Phase 1', releaseOrder:1, chronoOrder:5, chronoNote:'2010', director:'Jon Favreau', cast:['Robert Downey Jr.','Gwyneth Paltrow','Terrence Howard','Jeff Bridges'], duration:'126 min', synopsis:"Tony Stark, industriel et inventeur, est capturé par un groupe terroriste en Afghanistan. Il construit une armure blindée pour s'échapper et devient Iron Man, décidant de mettre son génie au service du bien.", wikiTitle:'Iron Man (2008 film)'},
{ id:'iron-man-2', poster:'images/posters/iron-man-2.jpg', title:'Iron Man 2', year:2010, type:'Film', franchise:'mcu', saga:'Phase 1', releaseOrder:3, chronoOrder:6, chronoNote:'2011', director:'Jon Favreau', cast:['Robert Downey Jr.','Gwyneth Paltrow','Don Cheadle','Scarlett Johansson','Mickey Rourke'], duration:'124 min', synopsis:"Sous la pression du gouvernement et rongé par la technologie qui le maintient en vie, Tony Stark doit affronter un nouvel ennemi armé de fouets électriques.", wikiTitle:'Iron Man 2'},
{ id:'incredible-hulk', poster:'images/posters/incredible-hulk.jpg', title:'L\'Incroyable Hulk', year:2008, type:'Film', franchise:'mcu', saga:'Phase 1', releaseOrder:2, chronoOrder:7, chronoNote:'2011', director:'Louis Leterrier', cast:['Edward Norton','Liv Tyler','Tim Roth','William Hurt'], duration:'112 min', synopsis:"Bruce Banner, traqué par l'armée américaine, tente de maîtriser la créature qui sommeille en lui tout en cherchant un remède à sa condition.", wikiTitle:'The Incredible Hulk (film)'},
{ id:'oneshot-funny-thing-thor-hammer', poster:'images/posters/oneshot-funny-thing-thor-hammer.png', title:'Marvel One-Shot: A Funny Thing Happened on the Way to Thor\'s Hammer', year:2011, type:'Court-métrage', franchise:'mcu', saga:'One-Shots', releaseOrder:68, chronoOrder:8, chronoNote:'2011', director:'Leythum', cast:['Clark Gregg'], duration:'~4 min (bonus du Blu-ray Captain America: First Avenger)', synopsis:"En patientant pour récupérer le marteau de Thor tombé au Nouveau-Mexique, l'agent Coulson use de son sens de la repartie face à une administration tatillonne.", wikiTitle:'Marvel One-Shots'},
{ id:'thor', poster:'images/posters/thor.jpg', title:'Thor', year:2011, type:'Film', franchise:'mcu', saga:'Phase 1', releaseOrder:4, chronoOrder:9, chronoNote:'2011', director:'Kenneth Branagh', cast:['Chris Hemsworth','Natalie Portman','Tom Hiddleston','Anthony Hopkins'], duration:'115 min', synopsis:"Banni d'Asgard par son père Odin pour son arrogance, le dieu du tonnerre Thor doit apprendre l'humilité sur Terre tandis que son frère Loki complote pour le trône.", wikiTitle:'Thor (film)'},
{ id:'oneshot-the-consultant', poster:'images/posters/oneshot-the-consultant.png', title:'Marvel One-Shot: The Consultant', year:2011, type:'Court-métrage', franchise:'mcu', saga:'One-Shots', releaseOrder:69, chronoOrder:10, chronoNote:'2011', director:'Leythum', cast:['Clark Gregg','Maximiliano Hernández'], duration:'~4 min (bonus du Blu-ray Thor)', synopsis:"Coulson et l'agent Sitwell manigancent pour faire libérer un général et éviter que le S.H.I.E.L.D. n'ait à collaborer avec Tony Stark.", wikiTitle:'Marvel One-Shots'},
{ id:'avengers', poster:'images/posters/avengers.jpg', title:'Avengers', year:2012, type:'Film', franchise:'mcu', saga:'Phase 1', releaseOrder:6, chronoOrder:11, chronoNote:'2012', director:'Joss Whedon', cast:['Robert Downey Jr.','Chris Evans','Scarlett Johansson','Chris Hemsworth','Mark Ruffalo','Jeremy Renner'], duration:'143 min', synopsis:"Loki revient sur Terre avec l'armée des Chitauris. Nick Fury réunit Iron Man, Captain America, Thor, Hulk, Black Widow et Hawkeye pour former les Avengers et sauver la planète.", wikiTitle:'The Avengers (2012 film)'},
{ id:'oneshot-item-47', poster:'images/posters/oneshot-item-47.jpg', title:'Marvel One-Shot: Item 47', year:2012, type:'Court-métrage', franchise:'mcu', saga:'One-Shots', releaseOrder:70, chronoOrder:12, chronoNote:'2012', director:'Louis D\'Esposito', cast:['Lizzy Caplan','Jesse Bradford'], duration:'~12 min (bonus du Blu-ray Avengers)', synopsis:"Un jeune couple de braqueurs met la main sur une arme chitauri abandonnée après la bataille de New York — jusqu'à attirer l'attention du S.H.I.E.L.D.", wikiTitle:'Item 47'},
{ id:'thor-dark-world', poster:'images/posters/thor-dark-world.jpg', title:'Thor: Le Monde des ténèbres', year:2013, type:'Film', franchise:'mcu', saga:'Phase 2', releaseOrder:8, chronoOrder:13, chronoNote:'2013', director:'Alan Taylor', cast:['Chris Hemsworth','Natalie Portman','Tom Hiddleston'], duration:'112 min', synopsis:"Thor doit sauver les neuf royaumes d'une race ancienne menée par Malekith, décidée à plonger l'univers dans les ténèbres.", wikiTitle:'Thor: The Dark World'},
{ id:'iron-man-3', poster:'images/posters/iron-man-3.jpg', title:'Iron Man 3', year:2013, type:'Film', franchise:'mcu', saga:'Phase 2', releaseOrder:7, chronoOrder:14, chronoNote:'2013', director:'Shane Black', cast:['Robert Downey Jr.','Gwyneth Paltrow','Ben Kingsley','Guy Pearce'], duration:'130 min', synopsis:"Traumatisé par les événements de New York, Tony Stark doit affronter le terroriste Mandarin alors que son empire technologique est menacé.", wikiTitle:'Iron Man 3'},
{ id:'oneshot-all-hail-the-king', poster:'images/posters/oneshot-all-hail-the-king.png', title:'Marvel One-Shot: All Hail the King', year:2014, type:'Court-métrage', franchise:'mcu', saga:'One-Shots', releaseOrder:71, chronoOrder:15, chronoNote:'2014', director:'Drew Pearce', cast:['Ben Kingsley'], duration:'~15 min (bonus du Blu-ray Thor: Le Monde des ténèbres)', synopsis:"Un journaliste interviewe en prison Trevor Slattery, le faux Mandarin d'Iron Man 3 — un épilogue qui sème aussi les graines du vrai Mandarin.", wikiTitle:'Marvel One-Shots'},
{ id:'captain-america-winter-soldier', poster:'images/posters/captain-america-winter-soldier.jpg', title:'Captain America: Le Soldat de l\'hiver', year:2014, type:'Film', franchise:'mcu', saga:'Phase 2', releaseOrder:9, chronoOrder:16, chronoNote:'2014', director:'Anthony et Joe Russo', cast:['Chris Evans','Scarlett Johansson','Sebastian Stan','Samuel L. Jackson'], duration:'136 min', synopsis:"Steve Rogers découvre qu'Hydra a infiltré le S.H.I.E.L.D. de l'intérieur et doit affronter un mystérieux assassin, le Soldat de l'Hiver.", wikiTitle:'Captain America: The Winter Soldier'},
{ id:'guardians-galaxy', poster:'images/posters/guardians-galaxy.jpg', title:'Les Gardiens de la Galaxie', year:2014, type:'Film', franchise:'mcu', saga:'Phase 2', releaseOrder:10, chronoOrder:17, chronoNote:'2014', director:'James Gunn', cast:['Chris Pratt','Zoe Saldana','Dave Bautista','Vin Diesel','Bradley Cooper'], duration:'121 min', synopsis:"Peter Quill, pilleur d'épaves galactique, s'allie à un groupe de renégats pour empêcher le fanatique Ronan de s'emparer d'un puissant orbe.", wikiTitle:'Guardians of the Galaxy (film)'},
{ id:'guardians-galaxy-2', poster:'images/posters/guardians-galaxy-2.jpg', title:'Les Gardiens de la Galaxie Vol. 2', year:2017, type:'Film', franchise:'mcu', saga:'Phase 3', releaseOrder:15, chronoOrder:18, chronoNote:'2014', director:'James Gunn', cast:['Chris Pratt','Zoe Saldana','Dave Bautista','Kurt Russell'], duration:'137 min', synopsis:"Peter Quill fait la rencontre de son véritable père, Ego, un être céleste aux intentions troubles.", wikiTitle:'Guardians of the Galaxy Vol. 2'},
{ id:'i-am-groot', poster:'images/posters/i-am-groot.jpeg', title:'I Am Groot', year:2022, type:'Série', franchise:'mcu', saga:'Phase 4', releaseOrder:53, chronoOrder:19, chronoNote:'entre Vol. 2 et Vol. 3', director:'Kirsten Lepore (superviseure)', cast:['Vin Diesel (voix de Groot)'], duration:'2 saisons, 10 courts épisodes (animation)', synopsis:"Une série de courts métrages suivant les mésaventures espiègles de Groot adolescent, entre deux missions des Gardiens de la Galaxie.", wikiTitle:'I Am Groot'},
{ id:'daredevil-nf-s1', poster:'images/posters/daredevil-nf-s1.jpg', title:'Daredevil (Saison 1)', year:2015, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:1, chronoOrder:20, chronoNote:'2015', director:'Drew Goddard (créateur), Steven S. DeKnight (showrunner)', cast:['Charlie Cox','Vincent D\'Onofrio','Deborah Ann Woll','Elden Henson'], duration:'1 saison, 13 épisodes', synopsis:"Matt Murdock endosse pour la première fois le costume de Daredevil pour nettoyer Hell's Kitchen, tandis que Wilson Fisk bâtit patiemment son emprise criminelle sur la ville.", wikiTitle:'Daredevil (season 1)'},
{ id:'jessica-jones-s1', poster:'images/posters/jessica-jones-s1.jpg', title:'Jessica Jones (Saison 1)', year:2015, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:2, chronoOrder:21, chronoNote:'2015', director:'Melissa Rosenberg (showrunneuse)', cast:['Krysten Ritter','David Tennant','Rachael Taylor','Mike Colter'], duration:'1 saison, 13 épisodes', synopsis:"Détective privée à la force surhumaine et au passé traumatique, Jessica Jones affronte Kilgrave, un homme doté d'un pouvoir de contrôle mental qui a fait d'elle sa marionnette.", wikiTitle:'Jessica Jones (season 1)'},
{ id:'avengers-ultron', poster:'images/posters/avengers-ultron.jpg', title:'Avengers: L\'Ère d\'Ultron', year:2015, type:'Film', franchise:'mcu', saga:'Phase 2', releaseOrder:11, chronoOrder:22, chronoNote:'2015', director:'Joss Whedon', cast:['Robert Downey Jr.','Chris Evans','Chris Hemsworth','Elizabeth Olsen','Paul Bettany'], duration:'141 min', synopsis:"Tony Stark crée Ultron, une IA censée protéger le monde, qui se retourne contre l'humanité entière.", wikiTitle:'Avengers: Age of Ultron'},
{ id:'ant-man', poster:'images/posters/ant-man.jpg', title:'Ant-Man', year:2015, type:'Film', franchise:'mcu', saga:'Phase 2', releaseOrder:12, chronoOrder:23, chronoNote:'2015', director:'Peyton Reed', cast:['Paul Rudd','Evangeline Lilly','Michael Douglas','Corey Stoll'], duration:'117 min', synopsis:"Scott Lang, ex-cambrioleur, endosse le costume rétrécissant du Dr Hank Pym pour déjouer un plan menaçant l'existence même de l'humanité.", wikiTitle:'Ant-Man (film)'},
{ id:'daredevil-nf-s2', poster:'images/posters/daredevil-nf-s2.jpg', title:'Daredevil (Saison 2)', year:2016, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:3, chronoOrder:24, chronoNote:'2016', director:'Doug Petrie, Marco Ramirez (showrunners)', cast:['Charlie Cox','Jon Bernthal','Élodie Yung','Deborah Ann Woll'], duration:'1 saison, 13 épisodes', synopsis:"L'arrivée du Punisher, justicier expéditif, bouleverse le code moral de Daredevil, tandis que le retour d'Elektra Natchios le ramène vers son passé et l'organisation de la Main.", wikiTitle:'Daredevil (season 2)'},
{ id:'luke-cage-s1', poster:'images/posters/luke-cage-s1.jpeg', title:'Luke Cage (Saison 1)', year:2016, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:4, chronoOrder:25, chronoNote:'2016', director:'Cheo Hodari Coker (showrunner)', cast:['Mike Colter','Mahershala Ali','Alfre Woodard','Simone Missick'], duration:'1 saison, 13 épisodes', synopsis:"Doté d'une peau incassable, Luke Cage devient malgré lui le protecteur de Harlem face à Cornell « Cottonmouth » Stokes et Mariah Dillard.", wikiTitle:'Luke Cage (season 1)'},
{ id:'iron-fist-s1', poster:'images/posters/iron-fist-s1.jpg', title:'Iron Fist (Saison 1)', year:2017, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:5, chronoOrder:26, chronoNote:'2017', director:'Scott Buck (showrunner)', cast:['Finn Jones','Jessica Henwick','Jessica Stroup','Tom Pelphrey'], duration:'1 saison, 13 épisodes', synopsis:"De retour à New York après quinze ans disparu, Danny Rand doit reprendre le contrôle de l'entreprise familiale tout en affrontant l'organisation mystique de la Main.", wikiTitle:'Iron Fist (season 1)'},
{ id:'defenders', poster:'images/posters/defenders.jpg', title:'The Defenders', year:2017, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:6, chronoOrder:27, chronoNote:'2017', director:'S.J. Clarkson (showrunneuse)', cast:['Charlie Cox','Krysten Ritter','Mike Colter','Finn Jones'], duration:'1 saison, 8 épisodes', synopsis:"Daredevil, Jessica Jones, Luke Cage et Iron Fist unissent leurs forces pour empêcher l'organisation de la Main de raser New York.", wikiTitle:'The Defenders (miniseries)'},
{ id:'civil-war', poster:'images/posters/civil-war.jpg', title:'Captain America: Civil War', year:2016, type:'Film', franchise:'mcu', saga:'Phase 3', releaseOrder:13, chronoOrder:28, chronoNote:'2016', director:'Anthony et Joe Russo', cast:['Chris Evans','Robert Downey Jr.','Scarlett Johansson','Sebastian Stan','Chadwick Boseman'], duration:'147 min', synopsis:"Les Avengers se déchirent sur la question d'un contrôle gouvernemental des super-héros, opposant Captain America à Iron Man.", wikiTitle:'Captain America: Civil War'},
{ id:'black-widow', poster:'images/posters/black-widow.jpg', title:'Black Widow', year:2021, type:'Film', franchise:'mcu', saga:'Phase 4', releaseOrder:24, chronoOrder:29, chronoNote:'2016 (après Civil War)', director:'Cate Shortland', cast:['Scarlett Johansson','Florence Pugh','David Harbour','Rachel Weisz'], duration:'134 min', synopsis:"Traquée par son passé d'espionne, Natasha Romanoff doit affronter une organisation qui a créé des veuves noires comme elle.", wikiTitle:'Black Widow (2021 film)'},
{ id:'black-panther', poster:'images/posters/black-panther.jpg', title:'Black Panther', year:2018, type:'Film', franchise:'mcu', saga:'Phase 3', releaseOrder:18, chronoOrder:30, chronoNote:'2017-18', director:'Ryan Coogler', cast:['Chadwick Boseman','Michael B. Jordan','Lupita Nyong\'o','Danai Gurira'], duration:'134 min', synopsis:"T'Challa retourne au Wakanda pour devenir roi, mais un rival venu du passé menace son trône et l'isolationnisme de la nation.", wikiTitle:'Black Panther (film)'},
{ id:'spiderman-homecoming', poster:'images/posters/spiderman-homecoming.jpg', title:'Spider-Man: Homecoming', year:2017, type:'Film', franchise:'mcu', saga:'Phase 3', releaseOrder:16, chronoOrder:31, chronoNote:'2016', director:'Jon Watts', cast:['Tom Holland','Michael Keaton','Robert Downey Jr.','Zendaya'], duration:'133 min', synopsis:"Peter Parker, sous l'aile de Tony Stark, tente de concilier vie de lycéen et lutte contre le trafiquant d'armes Vautour.", wikiTitle:'Spider-Man: Homecoming'},
{ id:'punisher-s1', poster:'images/posters/punisher-s1.jpg', title:'The Punisher (Saison 1)', year:2017, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:7, chronoOrder:32, chronoNote:'2017', director:'Steve Lightfoot (showrunner)', cast:['Jon Bernthal','Ben Barnes','Ebon Moss-Bachrach','Amber Rose Revah'], duration:'1 saison, 13 épisodes', synopsis:"Après avoir vengé sa famille, Frank Castle découvre que la conspiration militaire à l'origine de leur mort est bien plus vaste qu'il ne le pensait.", wikiTitle:'The Punisher (season 1)'},
{ id:'doctor-strange', poster:'images/posters/doctor-strange.jpg', title:'Doctor Strange', year:2016, type:'Film', franchise:'mcu', saga:'Phase 3', releaseOrder:14, chronoOrder:33, chronoNote:'2016', director:'Scott Derrickson', cast:['Benedict Cumberbatch','Tilda Swinton','Chiwetel Ejiofor'], duration:'115 min', synopsis:"Après un accident qui détruit ses mains, le brillant chirurgien Stephen Strange découvre les arts mystiques auprès de l'Ancienne.", wikiTitle:'Doctor Strange (2016 film)'},
{ id:'jessica-jones-s2', poster:'images/posters/jessica-jones-s2.jpg', title:'Jessica Jones (Saison 2)', year:2018, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:8, chronoOrder:34, chronoNote:'2018', director:'Melissa Rosenberg (showrunneuse)', cast:['Krysten Ritter','Rachael Taylor','Janet McTeer'], duration:'1 saison, 13 épisodes', synopsis:"Jessica enquête sur les origines de ses pouvoirs et sur l'organisation IGH, ce qui la mène jusqu'à une mère qu'elle croyait morte.", wikiTitle:'Jessica Jones (season 2)'},
{ id:'luke-cage-s2', poster:'images/posters/luke-cage-s2.jpg', title:'Luke Cage (Saison 2)', year:2018, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:9, chronoOrder:35, chronoNote:'2018', director:'Cheo Hodari Coker (showrunner)', cast:['Mike Colter','Alfre Woodard','Mustafa Shakir'], duration:'1 saison, 13 épisodes', synopsis:"Luke Cage doit affronter Bushmaster, un rival venu de Jamaïque, tout en luttant contre la tentation du pouvoir qui a corrompu tant d'autres avant lui.", wikiTitle:'Luke Cage (season 2)'},
{ id:'iron-fist-s2', poster:'images/posters/iron-fist-s2.jpg', title:'Iron Fist (Saison 2)', year:2018, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:10, chronoOrder:36, chronoNote:'2018', director:'M. Raven Metzner (showrunner)', cast:['Finn Jones','Jessica Henwick'], duration:'1 saison, 10 épisodes', synopsis:"Danny Rand et Colleen Wing protègent Chinatown des ambitions de Davos, un ancien frère d'armes devenu ennemi juré.", wikiTitle:'Iron Fist (season 2)'},
{ id:'daredevil-nf-s3', poster:'images/posters/daredevil-nf-s3.jpg', title:'Daredevil (Saison 3)', year:2018, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:11, chronoOrder:37, chronoNote:'2018', director:'Erik Oleson (showrunner)', cast:['Charlie Cox','Vincent D\'Onofrio','Deborah Ann Woll','Wilson Bethel'], duration:'1 saison, 13 épisodes', synopsis:"Affaibli après les événements de The Defenders, Matt Murdock doit affronter un Wilson Fisk relâché et infiltré au sein du FBI, ainsi qu'un nouvel ennemi masqué, Bullseye.", wikiTitle:'Daredevil (season 3)'},
{ id:'thor-ragnarok', poster:'images/posters/thor-ragnarok.jpg', title:'Thor: Ragnarok', year:2017, type:'Film', franchise:'mcu', saga:'Phase 3', releaseOrder:17, chronoOrder:38, chronoNote:'2017', director:'Taika Waititi', cast:['Chris Hemsworth','Tom Hiddleston','Cate Blanchett','Mark Ruffalo'], duration:'130 min', synopsis:"Emprisonné de l'autre côté de l'univers, Thor doit rentrer à Asgard à temps pour empêcher Hela de détruire son peuple.", wikiTitle:'Thor: Ragnarok'},
{ id:'punisher-s2', poster:'images/posters/punisher-s2.jpg', title:'The Punisher (Saison 2)', year:2019, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:12, chronoOrder:39, chronoNote:'2019', director:'Steve Lightfoot (showrunner)', cast:['Jon Bernthal','Ben Barnes','Amy Rutberg','Josh Stewart'], duration:'1 saison, 13 épisodes', synopsis:"Frank Castle protège une jeune femme traquée par un mystérieux tueur, tout en réglant définitivement ses comptes avec Billy Russo, devenu Jigsaw.", wikiTitle:'The Punisher (season 2)'},
{ id:'jessica-jones-s3', poster:'images/posters/jessica-jones-s3.jpg', title:'Jessica Jones (Saison 3)', year:2019, type:'Série', franchise:'netflix', saga:'Defenders Saga', releaseOrder:13, chronoOrder:40, chronoNote:'2019', director:'Melissa Rosenberg (showrunneuse)', cast:['Krysten Ritter','Rachael Taylor','Jeremy Bobb'], duration:'1 saison, 13 épisodes', synopsis:"Dernière saison : Jessica traque un tueur en série méthodique tandis que sa relation avec Trish, en quête de super-pouvoirs, se dégrade dangereusement.", wikiTitle:'Jessica Jones (season 3)'},
{ id:'ant-man-wasp', poster:'images/posters/ant-man-wasp.jpg', title:'Ant-Man et la Guêpe', year:2018, type:'Film', franchise:'mcu', saga:'Phase 3', releaseOrder:20, chronoOrder:41, chronoNote:'2018 (avant Infinity War)', director:'Peyton Reed', cast:['Paul Rudd','Evangeline Lilly','Michael Douglas','Michelle Pfeiffer'], duration:'118 min', synopsis:"Scott Lang s'allie à Hope van Dyne, devenue la Guêpe, pour percer les mystères du monde quantique.", wikiTitle:'Ant-Man and the Wasp'},
{ id:'infinity-war', poster:'images/posters/infinity-war.jpg', title:'Avengers: Infinity War', year:2018, type:'Film', franchise:'mcu', saga:'Phase 3', releaseOrder:19, chronoOrder:42, chronoNote:'2018', director:'Anthony et Joe Russo', cast:['Robert Downey Jr.','Chris Hemsworth','Chris Evans','Josh Brolin'], duration:'149 min', synopsis:"Thanos entame sa quête des six Pierres d'Infini. Les héros de la Terre s'unissent pour tenter de l'arrêter.", wikiTitle:'Avengers: Infinity War'},
{ id:'endgame', poster:'images/posters/endgame.jpg', title:'Avengers: Endgame', year:2019, type:'Film', franchise:'mcu', saga:'Phase 3', releaseOrder:22, chronoOrder:43, chronoNote:'2018-2023', director:'Anthony et Joe Russo', cast:['Robert Downey Jr.','Chris Evans','Scarlett Johansson','Chris Hemsworth'], duration:'181 min', synopsis:"Les survivants des Avengers organisent un ultime affrontement contre Thanos en remontant le temps pour récupérer les Pierres d'Infini.", wikiTitle:'Avengers: Endgame'},
{ id:'loki-s1', poster:'images/posters/loki-s1.png', title:'Loki (Saison 1)', year:2021, type:'Série', franchise:'mcu', saga:'Phase 4', releaseOrder:40, chronoOrder:44, chronoNote:'après le casse temporel d\'Endgame', director:'Kate Herron', cast:['Tom Hiddleston','Owen Wilson','Sophia Di Martino'], duration:'1 saison, 6 épisodes', synopsis:"Arrêté par la Confrérie du Temps (TVA) pour avoir altéré la timeline, Loki est recruté pour traquer une version variante de lui-même.", wikiTitle:'Loki (TV series)'},
{ id:'what-if-s1', poster:'images/posters/what-if-s1.png', title:'What If...? (Saison 1)', year:2021, type:'Série', franchise:'mcu', saga:'Phase 4', releaseOrder:41, chronoOrder:45, chronoNote:'multivers', director:'Bryan Andrews', cast:['Jeffrey Wright (narrateur)'], duration:'1 saison, 9 épisodes (animation)', synopsis:"Le Gardien explore des univers alternatifs où un simple événement modifié bouleverse tout le destin des héros Marvel.", wikiTitle:'What If...? (TV series)'},
{ id:'marvel-zombies', poster:'images/posters/marvel-zombies.png', title:'Marvel Zombies', year:2025, type:'Série', franchise:'mcu', saga:'Phase 6', releaseOrder:59, chronoOrder:46, chronoNote:'réalité alternative issue de What If...?', director:'Bryan Andrews', cast:['Elizabeth Olsen','Iman Vellani','Simu Liu','Florence Pugh','David Harbour','Hailee Steinfeld'], duration:'1 saison, 4 épisodes (animation, déconseillé aux plus jeunes)', synopsis:"Dans une réalité ravagée par une infection zombie, une poignée de héros et de vilains survivants tente de sauver ce qu'il reste de l'humanité.", wikiTitle:'Marvel Zombies (TV series)'},
{ id:'wandavision', poster:'images/posters/wandavision.png', title:'WandaVision', year:2021, type:'Série', franchise:'mcu', saga:'Phase 4', releaseOrder:38, chronoOrder:47, chronoNote:'3 semaines après Endgame', director:'Matt Shakman', cast:['Elizabeth Olsen','Paul Bettany','Kathryn Hahn'], duration:'1 saison, 9 épisodes', synopsis:"Wanda Maximoff et Vision vivent une existence de sitcom idyllique à Westview — jusqu'à ce que les fissures dans cette réalité truquée commencent à apparaître.", wikiTitle:'WandaVision'},
{ id:'shang-chi', poster:'images/posters/shang-chi.jpeg', title:'Shang-Chi et la Légende des Dix Anneaux', year:2021, type:'Film', franchise:'mcu', saga:'Phase 4', releaseOrder:25, chronoOrder:48, chronoNote:'2024', director:'Destin Daniel Cretton', cast:['Simu Liu','Awkwafina','Tony Leung','Michelle Yeoh'], duration:'132 min', synopsis:"Shang-Chi est contraint d'affronter le passé qu'il pensait avoir laissé derrière lui, aux côtés de son père, chef de l'organisation des Dix Anneaux.", wikiTitle:'Shang-Chi and the Legend of the Ten Rings'},
{ id:'falcon-winter-soldier', poster:'images/posters/falcon-winter-soldier.png', title:'Falcon et le Soldat de l\'hiver', year:2021, type:'Série', franchise:'mcu', saga:'Phase 4', releaseOrder:39, chronoOrder:49, chronoNote:'6 mois après WandaVision', director:'Kari Skogland', cast:['Anthony Mackie','Sebastian Stan','Wyatt Russell'], duration:'1 saison, 6 épisodes', synopsis:"Sam Wilson et Bucky Barnes s'allient contre le groupe extrémiste des Flag Smashers, tandis qu'un nouveau Captain America est nommé.", wikiTitle:'The Falcon and the Winter Soldier'},
{ id:'spiderman-far-from-home', poster:'images/posters/spiderman-far-from-home.jpg', title:'Spider-Man: Far From Home', year:2019, type:'Film', franchise:'mcu', saga:'Phase 3', releaseOrder:23, chronoOrder:50, chronoNote:'2024 (temps du film)', director:'Jon Watts', cast:['Tom Holland','Jake Gyllenhaal','Zendaya','Samuel L. Jackson'], duration:'129 min', synopsis:"En voyage scolaire en Europe, Peter Parker est recruté par Nick Fury pour affronter les Élémentaux aux côtés de Mysterio.", wikiTitle:'Spider-Man: Far From Home'},
{ id:'eternals', poster:'images/posters/eternals.jpeg', title:'Eternals', year:2021, type:'Film', franchise:'mcu', saga:'Phase 4', releaseOrder:26, chronoOrder:51, chronoNote:'depuis 5000 av. J.-C., jusqu\'à nos jours', director:'Chloé Zhao', cast:['Gemma Chan','Richard Madden','Angelina Jolie','Salma Hayek'], duration:'157 min', synopsis:"Un groupe d'êtres immortels, présents sur Terre depuis des millénaires, sort de l'ombre pour affronter leurs monstrueux ennemis, les Déviants.", wikiTitle:'Eternals (film)'},
{ id:'no-way-home', poster:'images/posters/no-way-home.jpg', title:'Spider-Man: No Way Home', year:2021, type:'Film', franchise:'mcu', saga:'Phase 4', releaseOrder:27, chronoOrder:52, chronoNote:'2024-25', director:'Jon Watts', cast:['Tom Holland','Zendaya','Willem Dafoe','Alfred Molina'], duration:'148 min', synopsis:"Un sort du Docteur Strange qui tourne mal déchire le multivers, ramenant des méchants d'autres Spider-Man face à Peter Parker.", wikiTitle:'Spider-Man: No Way Home'},
{ id:'doctor-strange-multiverse', poster:'images/posters/doctor-strange-multiverse.jpg', title:'Doctor Strange in the Multiverse of Madness', year:2022, type:'Film', franchise:'mcu', saga:'Phase 4', releaseOrder:28, chronoOrder:53, chronoNote:'2025', director:'Sam Raimi', cast:['Benedict Cumberbatch','Elizabeth Olsen','Xochitl Gomez'], duration:'126 min', synopsis:"Stephen Strange voyage à travers le multivers avec l'aide d'une mystérieuse alliée pour affronter une menace bien plus puissante que prévu.", wikiTitle:'Doctor Strange in the Multiverse of Madness'},
{ id:'hawkeye', poster:'images/posters/hawkeye.png', title:'Hawkeye', year:2021, type:'Série', franchise:'mcu', saga:'Phase 4', releaseOrder:42, chronoOrder:54, chronoNote:'Noël, après Endgame', director:'Rhys Thomas', cast:['Jeremy Renner','Hailee Steinfeld','Vera Farmiga'], duration:'1 saison, 6 épisodes', synopsis:"Clint Barton fait équipe avec la jeune archère Kate Bishop pour démêler une affaire liée à son passé de Ronin.", wikiTitle:'Hawkeye (miniseries)'},
{ id:'moon-knight', poster:'images/posters/moon-knight.jpg', title:'Moon Knight', year:2022, type:'Série', franchise:'mcu', saga:'Phase 4', releaseOrder:43, chronoOrder:55, chronoNote:'contemporain', director:'Mohamed Diab', cast:['Oscar Isaac','May Calamawy','Ethan Hawke'], duration:'1 saison, 6 épisodes', synopsis:"Steven Grant découvre qu'il partage son corps avec Marc Spector, mercenaire et avatar du dieu égyptien Khonshu.", wikiTitle:'Moon Knight (miniseries)'},
{ id:'wakanda-forever', poster:'images/posters/wakanda-forever.jpg', title:'Black Panther: Wakanda Forever', year:2022, type:'Film', franchise:'mcu', saga:'Phase 4', releaseOrder:30, chronoOrder:56, chronoNote:'2025-26', director:'Ryan Coogler', cast:['Letitia Wright','Lupita Nyong\'o','Danai Gurira','Tenoch Huerta'], duration:'161 min', synopsis:"À la mort de T'Challa, le Wakanda doit se défendre contre une nouvelle puissance sous-marine menée par Namor.", wikiTitle:'Black Panther: Wakanda Forever'},
{ id:'echo', poster:'images/posters/echo.jpg', title:'Echo', year:2024, type:'Série', franchise:'mcu', saga:'Phase 5', releaseOrder:48, chronoOrder:57, chronoNote:'après Hawkeye', director:'Sydney Freeland', cast:['Alaqua Cox','Vincent D\'Onofrio','Chaske Spencer'], duration:'1 saison, 5 épisodes', synopsis:"Maya Lopez retourne dans sa communauté d'origine pour affronter son passé familial et son ancien mentor, le Caïd.", wikiTitle:'Echo (TV series)'},
{ id:'she-hulk', poster:'images/posters/she-hulk.jpg', title:'She-Hulk: Avocate', year:2022, type:'Série', franchise:'mcu', saga:'Phase 4', releaseOrder:45, chronoOrder:58, chronoNote:'contemporain', director:'Kat Coiro', cast:['Tatiana Maslany','Mark Ruffalo','Tim Roth'], duration:'1 saison, 9 épisodes', synopsis:"Jennifer Walters, avocate, hérite des pouvoirs de son cousin Bruce Banner et doit jongler entre carrière et vie de super-héroïne verte.", wikiTitle:'She-Hulk: Attorney at Law'},
{ id:'ms-marvel', poster:'images/posters/ms-marvel.jpg', title:'Ms. Marvel', year:2022, type:'Série', franchise:'mcu', saga:'Phase 4', releaseOrder:44, chronoOrder:59, chronoNote:'contemporain', director:'Adil El Arbi, Bilall Fallah', cast:['Iman Vellani','Matt Lintz','Yasmeen Fletcher'], duration:'1 saison, 6 épisodes', synopsis:"Kamala Khan, ado fan des Avengers à Jersey City, découvre des pouvoirs cosmiques qui vont bouleverser sa vie.", wikiTitle:'Ms. Marvel (TV series)'},
{ id:'thor-love-thunder', poster:'images/posters/thor-love-thunder.jpeg', title:'Thor: Love and Thunder', year:2022, type:'Film', franchise:'mcu', saga:'Phase 4', releaseOrder:29, chronoOrder:60, chronoNote:'2025', director:'Taika Waititi', cast:['Chris Hemsworth','Natalie Portman','Christian Bale','Tessa Thompson'], duration:'119 min', synopsis:"Thor tente de trouver la paix intérieure, mais doit reprendre les armes contre Gorr le Boucher de Dieux, aux côtés de Jane Foster devenue Mighty Thor.", wikiTitle:'Thor: Love and Thunder'},
{ id:'ironheart', poster:'images/posters/ironheart.png', title:'Ironheart', year:2025, type:'Série', franchise:'mcu', saga:'Phase 5', releaseOrder:57, chronoOrder:61, chronoNote:'après Wakanda Forever', director:'Sam Bailey', cast:['Dominique Thorne','Anthony Ramos','Manny Montana','Alden Ehrenreich','Sacha Baron Cohen'], duration:'1 saison, 6 épisodes', synopsis:"De retour à Chicago après son passage au Wakanda, la surdouée Riri Williams perfectionne son armure Ironheart et croise la route d'un mystérieux escroc, le Hood.", wikiTitle:'Ironheart (miniseries)'},
{ id:'werewolf-by-night', poster:'images/posters/werewolf-by-night.jpg', title:'Werewolf by Night', year:2022, type:'Série', franchise:'mcu', saga:'Phase 4', releaseOrder:51, chronoOrder:62, chronoNote:'fin 2025', director:'Michael Giacchino', cast:['Gael García Bernal','Laura Donnelly','Harriet Sansom Harris'], duration:'1 spécial, 53 min (noir et blanc)', synopsis:"À la mort du chasseur de monstres Ulysses Bloodstone, un groupe de chasseurs rivaux s'affronte lors d'une chasse macabre organisée par sa veuve — jusqu'à ce qu'un invité au sang maudit change la donne.", wikiTitle:'Werewolf by Night (TV special)'},
{ id:'guardians-holiday-special', poster:'images/posters/guardians-holiday-special.jpg', title:'The Guardians of the Galaxy Holiday Special', year:2022, type:'Série', franchise:'mcu', saga:'Phase 4', releaseOrder:52, chronoOrder:63, chronoNote:'décembre 2025', director:'James Gunn', cast:['Kevin Bacon','Chris Pratt','Dave Bautista','Karen Gillan','Pom Klementieff'], duration:'1 spécial, 44 min', synopsis:"Pour remonter le moral de Peter Quill après la perte de Gamora, Drax et Mantis se lancent dans une mission d'enlèvement... de Kevin Bacon, afin de lui offrir le Noël dont il a toujours rêvé.", wikiTitle:'The Guardians of the Galaxy Holiday Special'},
{ id:'quantumania', poster:'images/posters/quantumania.jpg', title:'Ant-Man et la Guêpe: Quantumania', year:2023, type:'Film', franchise:'mcu', saga:'Phase 5', releaseOrder:31, chronoOrder:64, chronoNote:'2026', director:'Peyton Reed', cast:['Paul Rudd','Evangeline Lilly','Jonathan Majors','Michelle Pfeiffer'], duration:'125 min', synopsis:"La famille Lang-Van Dyne est aspirée dans le Royaume Quantique et doit y affronter le redoutable conquérant Kang.", wikiTitle:'Ant-Man and the Wasp: Quantumania'},
{ id:'guardians-galaxy-3', poster:'images/posters/guardians-galaxy-3.jpg', title:'Les Gardiens de la Galaxie Vol. 3', year:2023, type:'Film', franchise:'mcu', saga:'Phase 5', releaseOrder:32, chronoOrder:65, chronoNote:'2026', director:'James Gunn', cast:['Chris Pratt','Zoe Saldana','Dave Bautista','Karen Gillan'], duration:'150 min', synopsis:"Les Gardiens doivent protéger Rocket dont le sombre passé, lié au High Evolutionary, refait surface.", wikiTitle:'Guardians of the Galaxy Vol. 3'},
{ id:'secret-invasion', poster:'images/posters/secret-invasion.jpg', title:'Secret Invasion', year:2023, type:'Série', franchise:'mcu', saga:'Phase 5', releaseOrder:46, chronoOrder:66, chronoNote:'contemporain', director:'Ali Selim', cast:['Samuel L. Jackson','Ben Mendelsohn','Kingsley Ben-Adir'], duration:'1 saison, 6 épisodes', synopsis:"Nick Fury découvre qu'une faction de Skrulls infiltre depuis des années les plus hautes sphères du pouvoir sur Terre.", wikiTitle:'Secret Invasion (TV series)'},
{ id:'the-marvels', poster:'images/posters/the-marvels.jpg', title:'The Marvels', year:2023, type:'Film', franchise:'mcu', saga:'Phase 5', releaseOrder:33, chronoOrder:67, chronoNote:'2026', director:'Nia DaCosta', cast:['Brie Larson','Teyonah Parris','Iman Vellani'], duration:'105 min', synopsis:"Carol Danvers voit ses pouvoirs se lier à ceux de Kamala Khan et Monica Rambeau, les forçant à échanger de place à chaque usage de leurs pouvoirs.", wikiTitle:'The Marvels'},
{ id:'loki-s2', poster:'images/posters/loki-s2.jpg', title:'Loki (Saison 2)', year:2023, type:'Série', franchise:'mcu', saga:'Phase 5', releaseOrder:47, chronoOrder:68, chronoNote:'suite immédiate', director:'Justin Benson, Aaron Moorhead', cast:['Tom Hiddleston','Owen Wilson','Sophia Di Martino'], duration:'1 saison, 6 épisodes', synopsis:"Loki, désormais capable de voyager dans le temps, tente de sauver la TVA de son effondrement après la mort de He Who Remains.", wikiTitle:'Loki season 2'},
{ id:'what-if-s2', poster:'images/posters/what-if-s2.jpeg', title:'What If...? (Saison 2)', year:2023, type:'Série', franchise:'mcu', saga:'Phase 5', releaseOrder:54, chronoOrder:69, chronoNote:'multivers', director:'Bryan Andrews', cast:['Jeffrey Wright (narrateur)'], duration:'1 saison, 9 épisodes (animation)', synopsis:"De nouvelles explorations d'univers alternatifs, dans la continuité directe de la première saison.", wikiTitle:'What If...? season 2'},
{ id:'deadpool-wolverine', poster:'images/posters/deadpool-wolverine.jpg', title:'Deadpool & Wolverine', year:2024, type:'Film', franchise:'mcu', saga:'Phase 5', releaseOrder:34, chronoOrder:70, chronoNote:'multivers', director:'Shawn Levy', cast:['Ryan Reynolds','Hugh Jackman','Emma Corrin'], duration:'128 min', synopsis:"Recruté par la TVA, Deadpool convainc un Wolverine d'une réalité alternative de l'aider à sauver son univers — fusionnant officiellement l'ancien univers X-Men Fox dans le MCU.", wikiTitle:'Deadpool & Wolverine'},
{ id:'agatha-all-along', poster:'images/posters/agatha-all-along.jpg', title:'Agatha All Along', year:2024, type:'Série', franchise:'mcu', saga:'Phase 5', releaseOrder:49, chronoOrder:71, chronoNote:'après WandaVision', director:'Jac Schaeffer', cast:['Kathryn Hahn','Joe Locke','Aubrey Plaza'], duration:'1 saison, 9 épisodes', synopsis:"Dépouillée de ses pouvoirs, la sorcière Agatha Harkness rassemble un groupe hétéroclite de sorcières pour parcourir le Chemin des Sorcières.", wikiTitle:'Agatha All Along'},
{ id:'what-if-s3', poster:'images/posters/what-if-s3.jpeg', title:'What If...? (Saison 3)', year:2024, type:'Série', franchise:'mcu', saga:'Phase 5', releaseOrder:55, chronoOrder:72, chronoNote:'multivers', director:'Bryan Andrews', cast:['Jeffrey Wright (narrateur)'], duration:'1 saison, 8 épisodes (animation)', synopsis:"Une nouvelle salve d'histoires alternatives, entre nouveaux visages et retour de personnages du multivers.", wikiTitle:'What If...? season 3'},
{ id:'daredevil-born-again', poster:'images/posters/daredevil-born-again.jpeg', title:'Daredevil: Born Again (Saison 1)', year:2025, type:'Série', franchise:'mcu', saga:'Phase 5', releaseOrder:50, chronoOrder:73, chronoNote:'contemporain', director:'Various', cast:['Charlie Cox','Vincent D\'Onofrio','Ayelet Zurer'], duration:'1 saison, 9 épisodes', synopsis:"Matt Murdock, retiré du costume, reprend le combat lorsque Wilson Fisk, devenu maire de New York, révèle sa véritable nature.", wikiTitle:'Daredevil: Born Again'},
{ id:'captain-america-brave-new-world', poster:'images/posters/captain-america-brave-new-world.jpg', title:'Captain America: Brave New World', year:2025, type:'Film', franchise:'mcu', saga:'Phase 5', releaseOrder:35, chronoOrder:74, chronoNote:'2027', director:'Julius Onah', cast:['Anthony Mackie','Harrison Ford','Danny Ramirez'], duration:'118 min', synopsis:"Devenu le nouveau Captain America, Sam Wilson se retrouve au cœur d'un complot international impliquant le président Ross.", wikiTitle:'Captain America: Brave New World'},
{ id:'thunderbolts', poster:'images/posters/thunderbolts.jpg', title:'Thunderbolts*', year:2025, type:'Film', franchise:'mcu', saga:'Phase 5', releaseOrder:36, chronoOrder:75, chronoNote:'2027', director:'Jake Schreier', cast:['Florence Pugh','Sebastian Stan','David Harbour','Julia Louis-Dreyfus'], duration:'126 min', synopsis:"Une équipe d'antihéros et de vilains repentis, manipulés par Valentina Allegra de Fontaine, est envoyée en mission suicide.", wikiTitle:'Thunderbolts*'},
{ id:'fantastic-four-first-steps', poster:'images/posters/fantastic-four-first-steps.jpg', title:'Fantastic Four: First Steps', year:2025, type:'Film', franchise:'mcu', saga:'Phase 6', releaseOrder:37, chronoOrder:76, chronoNote:'Terre-828, années 1960 rétrofuturistes', director:'Matt Shakman', cast:['Pedro Pascal','Vanessa Kirby','Joseph Quinn','Ebon Moss-Bachrach'], duration:'115 min', synopsis:"La première famille de super-héros de Marvel doit protéger la Terre-828 face à Galactus et à son héraut, Silver Surfer.", wikiTitle:'The Fantastic Four: First Steps'},
{ id:'wonder-man', title:'Wonder Man', year:2026, type:'Série', franchise:'mcu', saga:'Phase 6', releaseOrder:60, chronoOrder:77, chronoNote:'contemporain', director:'Destin Daniel Cretton (showrunner)', cast:['Yahya Abdul-Mateen II','Ben Kingsley'], duration:'1 saison, 8 épisodes', synopsis:"L'acteur cascadeur Simon Williams tente de décrocher le rôle de sa vie — celui du super-héros Wonder Man — dans une satire des coulisses d'Hollywood.", wikiTitle:'Wonder Man (TV series)'},
{ id:'daredevil-born-again-s2', poster:'images/posters/daredevil-born-again-s2.jpeg', title:'Daredevil: Born Again (Saison 2)', year:2026, type:'Série', franchise:'mcu', saga:'Phase 6', releaseOrder:61, chronoOrder:78, chronoNote:'suite immédiate', director:'Various', cast:['Charlie Cox','Vincent D\'Onofrio'], duration:'1 saison, 8 épisodes', synopsis:"Alors que Wilson Fisk resserre son emprise sur New York en tant que maire, Matt Murdock doit choisir jusqu'où aller pour l'arrêter.", wikiTitle:'Daredevil: Born Again season 2'},
{ id:'punisher-one-last-kill', poster:'images/posters/punisher-one-last-kill.jpg', title:'The Punisher: One Last Kill', year:2026, type:'Série', franchise:'mcu', saga:'Phase 6', releaseOrder:62, chronoOrder:79, chronoNote:'contemporain', director:'Reinaldo Marcus Green', cast:['Jon Bernthal'], duration:'1 spécial', synopsis:"Alors qu'il cherche un sens à sa vie au-delà de la vengeance, Frank Castle est rattrapé par une force qui le replonge dans la violence.", wikiTitle:'The Punisher: One Last Kill'},

// --- Pas encore placés dans l'ordre officiel Disney+ (animés hors continuité
//     confirmée, ou pas encore sortis au 22/08/2026) — voir FRANCHISE_NOTES.
{ id:'your-friendly-neighborhood-spiderman', poster:'images/posters/your-friendly-neighborhood-spiderman.png', title:'Your Friendly Neighborhood Spider-Man', year:2025, type:'Série', franchise:'mcu', saga:'Phase 6', releaseOrder:56, chronoOrder:80, chronoNote:'contemporain, débuts de Peter Parker', director:'Jeff Trammell (showrunner)', cast:['Hudson Thames','Eugene Byrd','Grace Song','Zeno Robinson','Hugh Dancy','Charlie Cox'], duration:'1 saison, 10 épisodes (animation)', synopsis:"Relecture animée des débuts de Peter Parker en super-héros à New York, entre lycée, premiers combats et rencontre avec Daredevil. Non listée (encore) dans le « Complete Timeline » officiel de Disney+.", wikiTitle:'Your Friendly Neighborhood Spider-Man'},
{ id:'visionquest', poster:'images/posters/visionquest.jpg', title:'VisionQuest', year:2026, type:'Série', franchise:'mcu', saga:'Phase 6', releaseOrder:64, chronoOrder:81, chronoNote:'suite de WandaVision et Agatha All Along', director:'Terry Matalas e.a.', cast:['Paul Bettany','James Spader','Emily Hampshire','James D\'Arcy'], duration:'1 saison, 8 épisodes', synopsis:"Vision, redevenu lui-même mais dépourvu de ses souvenirs avec Wanda, part en quête de son identité — et croise la route d'un vieil ennemi, Ultron.", wikiTitle:'VisionQuest', upcoming:true},
{ id:'spiderman-brand-new-day', poster:'images/posters/spiderman-brand-new-day.jpg', title:'Spider-Man: Brand New Day', year:2026, type:'Film', franchise:'mcu', saga:'Phase 6', releaseOrder:63, chronoOrder:82, chronoNote:'plusieurs années après No Way Home', director:'Destin Daniel Cretton', cast:['Tom Holland','Zendaya','Sadie Sink','Jacob Batalon','Jon Bernthal','Florence Pugh','Marisa Tomei','Mark Ruffalo'], duration:'non communiquée', synopsis:"Peter Parker mène seul son combat de super-héros dans un monde qui a oublié jusqu'à son existence, jusqu'à ce qu'une nouvelle menace invisible et le retour d'anciens visages ne le forcent à se réinventer.", wikiTitle:'Spider-Man: Brand New Day'},
{ id:'avengers-doomsday', poster:'images/posters/avengers-doomsday.jpg', title:'Avengers: Doomsday', year:2026, type:'Film', franchise:'mcu', saga:'Phase 6', releaseOrder:65, chronoOrder:83, chronoNote:'culmination de la Saga du Multivers', director:'Anthony et Joe Russo', cast:['Robert Downey Jr. (Docteur Fatalis)','vaste casting multivers encore tenu secret'], duration:'non communiquée', synopsis:"Le retour des frères Russo aux commandes d'un nouvel Avengers réunissant un casting multivers tentaculaire — avec Robert Downey Jr. de retour dans la peau du Docteur Fatalis.", wikiTitle:'Avengers: Doomsday', upcoming:true},
{ id:'avengers-secret-wars', title:'Avengers: Secret Wars', year:2027, type:'Film', franchise:'mcu', saga:'Phase 6', releaseOrder:66, chronoOrder:84, chronoNote:'aboutissement de la Saga du Multivers', director:'Anthony et Joe Russo', cast:['Casting non officiellement dévoilé'], duration:'non communiquée', synopsis:"Le film censé clore la « Saga du Multivers » sous la direction des frères Russo — l'intrigue reste, à ce jour, tenue secrète.", wikiTitle:'Avengers: Secret Wars', upcoming:true},

// --------------------------------------------------------------- X-MEN ---
{ id:'xmen-first-class', poster:'images/posters/xmen-first-class.jpg', title:'X-Men: First Class', year:2011, type:'Film', franchise:'xmen', saga:'Trilogie First Class', releaseOrder:5, chronoOrder:1, chronoNote:'1962', director:'Matthew Vaughn', cast:['James McAvoy','Michael Fassbender','Jennifer Lawrence','Kevin Bacon'], duration:'132 min', synopsis:"En pleine Guerre froide, Charles Xavier et Erik Lensherr forment la première équipe de mutants, avant que leurs idéaux ne les séparent à jamais.", wikiTitle:'X-Men: First Class'},
{ id:'xmen-days-future-past', poster:'images/posters/xmen-days-future-past.jpg', title:'X-Men: Days of Future Past', year:2014, type:'Film', franchise:'xmen', saga:'Trilogie First Class', releaseOrder:7, chronoOrder:2, chronoNote:'1973 / 2023', director:'Bryan Singer', cast:['Hugh Jackman','James McAvoy','Michael Fassbender','Patrick Stewart'], duration:'132 min', synopsis:"Wolverine est envoyé dans le passé pour empêcher un événement qui mènera à un futur dystopique où les Sentinelles exterminent les mutants.", wikiTitle:'X-Men: Days of Future Past'},
{ id:'xmen-apocalypse', poster:'images/posters/xmen-apocalypse.jpg', title:'X-Men: Apocalypse', year:2016, type:'Film', franchise:'xmen', saga:'Trilogie First Class', releaseOrder:9, chronoOrder:3, chronoNote:'1983', director:'Bryan Singer', cast:['James McAvoy','Michael Fassbender','Jennifer Lawrence','Oscar Isaac'], duration:'144 min', synopsis:"Le tout premier mutant, En Sabah Nur, se réveille après des millénaires et recrute quatre cavaliers pour raser la civilisation moderne.", wikiTitle:'X-Men: Apocalypse'},
{ id:'dark-phoenix', poster:'images/posters/dark-phoenix.png', title:'Dark Phoenix', year:2019, type:'Film', franchise:'xmen', saga:'Trilogie First Class', releaseOrder:12, chronoOrder:4, chronoNote:'1992', director:'Simon Kinberg', cast:['Sophie Turner','James McAvoy','Michael Fassbender','Jennifer Lawrence'], duration:'113 min', synopsis:"Jean Grey est submergée par une force cosmique qui réveille ses pouvoirs les plus destructeurs et la fait basculer du côté obscur.", wikiTitle:'Dark Phoenix (film)'},
{ id:'new-mutants', poster:'images/posters/new-mutants.jpeg', title:'The New Mutants', year:2020, type:'Film', franchise:'xmen', saga:'Spin-off', releaseOrder:13, chronoOrder:5, chronoNote:'ambigu, proche du présent', director:'Josh Boone', cast:['Maisie Williams','Anya Taylor-Joy','Charlie Heaton'], duration:'98 min', synopsis:"Cinq jeunes mutants internés dans un hôpital psychiatrique isolé découvrent que leurs pouvoirs pourraient bien être la clé de leur perte.", wikiTitle:'The New Mutants (film)'},
{ id:'xmen-origins-wolverine', poster:'images/posters/xmen-origins-wolverine.jpg', title:'X-Men Origins: Wolverine', year:2009, type:'Film', franchise:'xmen', saga:'Wolverine', releaseOrder:4, chronoOrder:6, chronoNote:'de la guerre de Sécession à 1979', director:'Gavin Hood', cast:['Hugh Jackman','Liev Schreiber','Ryan Reynolds'], duration:'107 min', synopsis:"Retour sur le passé tourmenté de Logan, sa relation fraternelle avec Victor Creed et le programme Arme X qui lui a donné son squelette d'adamantium.", wikiTitle:'X-Men Origins: Wolverine'},
{ id:'xmen', poster:'images/posters/xmen.jpg', title:'X-Men', year:2000, type:'Film', franchise:'xmen', saga:'Trilogie originale', releaseOrder:1, chronoOrder:7, chronoNote:'2000', director:'Bryan Singer', cast:['Hugh Jackman','Patrick Stewart','Ian McKellen','Halle Berry'], duration:'104 min', synopsis:"Wolverine et Rogue rejoignent l'école du Professeur Xavier, alors qu'Erik Lensherr (Magnéto) prépare un plan pour « muter » les dirigeants mondiaux.", wikiTitle:'X-Men (film)'},
{ id:'xmen-2', poster:'images/posters/xmen-2.jpg', title:'X2', year:2003, type:'Film', franchise:'xmen', saga:'Trilogie originale', releaseOrder:2, chronoOrder:8, chronoNote:'2003', director:'Bryan Singer', cast:['Hugh Jackman','Patrick Stewart','Ian McKellen','Alan Cumming'], duration:'134 min', synopsis:"Le colonel Stryker, animé par une haine viscérale des mutants, attaque l'école de Xavier et force alliés et ennemis à s'unir.", wikiTitle:'X2 (film)'},
{ id:'xmen-last-stand', poster:'images/posters/xmen-last-stand.jpg', title:'X-Men: L\'Affrontement final', year:2006, type:'Film', franchise:'xmen', saga:'Trilogie originale', releaseOrder:3, chronoOrder:9, chronoNote:'2006', director:'Brett Ratner', cast:['Hugh Jackman','Halle Berry','Ian McKellen','Famke Janssen'], duration:'104 min', synopsis:"Un « remède » censé annuler la mutation divise la communauté mutante, tandis que Jean Grey renaît sous la forme dévastatrice de Phoenix.", wikiTitle:'X-Men: The Last Stand'},
{ id:'deadpool', poster:'images/posters/deadpool.png', title:'Deadpool', year:2016, type:'Film', franchise:'xmen', saga:'Deadpool', releaseOrder:8, chronoOrder:10, chronoNote:'contemporain (avec ruptures du 4e mur)', director:'Tim Miller', cast:['Ryan Reynolds','Morena Baccarin','Ed Skrein'], duration:'108 min', synopsis:"Wade Wilson, mercenaire cynique, devient le régénérant et irrévérencieux Deadpool après une expérience clandestine qui dérape.", wikiTitle:'Deadpool (film)'},
{ id:'deadpool-2', poster:'images/posters/deadpool-2.jpg', title:'Deadpool 2', year:2018, type:'Film', franchise:'xmen', saga:'Deadpool', releaseOrder:11, chronoOrder:11, chronoNote:'contemporain', director:'David Leitch', cast:['Ryan Reynolds','Josh Brolin','Zazie Beetz'], duration:'119 min', synopsis:"Deadpool forme la X-Force pour protéger un jeune mutant menacé par Cable, un soldat venu du futur.", wikiTitle:'Deadpool 2'},
{ id:'the-wolverine', poster:'images/posters/the-wolverine.jpg', title:'Wolverine: Le Combat de l\'immortel', year:2013, type:'Film', franchise:'xmen', saga:'Wolverine', releaseOrder:6, chronoOrder:12, chronoNote:'2013', director:'James Mangold', cast:['Hugh Jackman','Tao Okamoto','Rila Fukushima'], duration:'126 min', synopsis:"Invité au Japon par un homme qu'il a sauvé jadis, Logan se retrouve mêlé à un complot autour d'un procédé pouvant le rendre mortel.", wikiTitle:'The Wolverine (film)'},
{ id:'logan', poster:'images/posters/logan.jpg', title:'Logan', year:2017, type:'Film', franchise:'xmen', saga:'Wolverine', releaseOrder:10, chronoOrder:13, chronoNote:'2029', director:'James Mangold', cast:['Hugh Jackman','Patrick Stewart','Dafne Keen'], duration:'137 min', synopsis:"En 2029, un Logan vieilli et affaibli s'occupe d'un Charles Xavier malade, jusqu'à ce qu'une jeune mutante traquée bouleverse leur exil.", wikiTitle:'Logan (film)'},
{ id:'xmen-97-s1', poster:'images/posters/xmen-97-s1.png', title:'X-Men \'97 (Saison 1)', year:2024, type:'Série', franchise:'xmen', saga:"X-Men '97 (animation)", releaseOrder:14, chronoOrder:100, chronoNote:'continuité animée distincte, suite directe de 1992', director:'Jake Castorena (réalisateur superviseur), Beau DeMayo (scénariste, saison 1)', cast:['Ray Chase','Jennifer Hale','Cal Dodd','Alison Sealy-Smith','Lenore Zann','George Buza'], duration:'1 saison, 10 épisodes (animation)', synopsis:"Suite directe de « X-Men : la Série animée » des années 1990 : le rêve de Charles Xavier est mis à rude épreuve après sa disparition, forçant les X-Men à se redéfinir.", wikiTitle:"X-Men '97"},
{ id:'xmen-97-s2', poster:'images/posters/xmen-97-s2.png', title:'X-Men \'97 (Saison 2)', year:2026, type:'Série', franchise:'xmen', saga:"X-Men '97 (animation)", releaseOrder:15, chronoOrder:101, chronoNote:'suite immédiate', director:'Jake Castorena (réalisateur superviseur)', cast:['Ray Chase','Jennifer Hale','Cal Dodd','Alison Sealy-Smith','Lenore Zann','George Buza'], duration:'1 saison (animation)', synopsis:"Dispersés à travers le temps après le season finale de la saison 1, les X-Men doivent retrouver le chemin du présent tout en affrontant le retour d'Apocalypse.", wikiTitle:"X-Men '97"},

// ------------------------------------------------------- SPIDER-MAN (Sony) ---
{ id:'spiderman-2002', poster:'images/posters/spiderman-2002.jpg', title:'Spider-Man', year:2002, type:'Film', franchise:'sony', saga:'Trilogie Raimi', releaseOrder:1, chronoOrder:1, chronoNote:'2002', director:'Sam Raimi', cast:['Tobey Maguire','Kirsten Dunst','Willem Dafoe'], duration:'121 min', synopsis:"Mordu par une araignée génétiquement modifiée, le lycéen Peter Parker acquiert des pouvoirs et doit affronter le Bouffon Vert.", wikiTitle:'Spider-Man (2002 film)'},
{ id:'spiderman-2-2004', poster:'images/posters/spiderman-2-2004.jpg', title:'Spider-Man 2', year:2004, type:'Film', franchise:'sony', saga:'Trilogie Raimi', releaseOrder:2, chronoOrder:2, chronoNote:'2004', director:'Sam Raimi', cast:['Tobey Maguire','Kirsten Dunst','Alfred Molina'], duration:'127 min', synopsis:"Épuisé par le poids de sa double vie, Peter Parker envisage d'abandonner le costume, jusqu'à l'apparition du Docteur Octopus.", wikiTitle:'Spider-Man 2'},
{ id:'spiderman-3-2007', poster:'images/posters/spiderman-3-2007.jpg', title:'Spider-Man 3', year:2007, type:'Film', franchise:'sony', saga:'Trilogie Raimi', releaseOrder:3, chronoOrder:3, chronoNote:'2007', director:'Sam Raimi', cast:['Tobey Maguire','Kirsten Dunst','Topher Grace','Thomas Haden Church'], duration:'139 min', synopsis:"Un symbiote extraterrestre s'attache à Peter Parker et exacerbe ses pires travers, tandis qu'Harry Osborn et l'Homme-Sable entrent en scène.", wikiTitle:'Spider-Man 3'},
{ id:'amazing-spiderman', poster:'images/posters/amazing-spiderman.jpg', title:'The Amazing Spider-Man', year:2012, type:'Film', franchise:'sony', saga:'Trilogie Amazing', releaseOrder:4, chronoOrder:4, chronoNote:'2012', director:'Marc Webb', cast:['Andrew Garfield','Emma Stone','Rhys Ifans'], duration:'136 min', synopsis:"Peter Parker enquête sur la disparition de son père et affronte le Lézard, ancien collègue devenu monstrueux, au sein d'Oscorp.", wikiTitle:'The Amazing Spider-Man (2012 film)'},
{ id:'amazing-spiderman-2', poster:'images/posters/amazing-spiderman-2.jpg', title:'The Amazing Spider-Man 2: Le Destin d\'un héros', year:2014, type:'Film', franchise:'sony', saga:'Trilogie Amazing', releaseOrder:5, chronoOrder:5, chronoNote:'2014', director:'Marc Webb', cast:['Andrew Garfield','Emma Stone','Jamie Foxx','Dane DeHaan'], duration:'142 min', synopsis:"Spider-Man doit affronter Electro et un Harry Osborn devenu Bouffon Vert, tout en portant le poids d'une prophétie funeste.", wikiTitle:'The Amazing Spider-Man 2'},
{ id:'venom', poster:'images/posters/venom.png', title:'Venom', year:2018, type:'Film', franchise:'sony', saga:'Sony\'s Spider-Man Universe', releaseOrder:6, chronoOrder:6, chronoNote:'2018', director:'Ruben Fleischer', cast:['Tom Hardy','Michelle Williams','Riz Ahmed'], duration:'112 min', synopsis:"Le journaliste Eddie Brock fusionne avec un symbiote extraterrestre et devient Venom, une créature aussi dangereuse que protectrice.", wikiTitle:'Venom (2018 film)'},
{ id:'venom-carnage', poster:'images/posters/venom-carnage.jpg', title:'Venom: Let There Be Carnage', year:2021, type:'Film', franchise:'sony', saga:'Sony\'s Spider-Man Universe', releaseOrder:7, chronoOrder:7, chronoNote:'2021', director:'Andy Serkis', cast:['Tom Hardy','Woody Harrelson','Michelle Williams'], duration:'97 min', synopsis:"Eddie Brock doit affronter Cletus Kasady, tueur en série devenu hôte du symbiote Carnage, encore plus violent que Venom.", wikiTitle:'Venom: Let There Be Carnage'},
{ id:'morbius', poster:'images/posters/morbius.jpg', title:'Morbius', year:2022, type:'Film', franchise:'sony', saga:'Sony\'s Spider-Man Universe', releaseOrder:8, chronoOrder:8, chronoNote:'2022', director:'Daniel Espinosa', cast:['Jared Leto','Matt Smith','Adria Arjona'], duration:'104 min', synopsis:"Atteint d'une maladie rare, le biochimiste Michael Morbius s'inflige un traitement expérimental qui le transforme en vampire vivant.", wikiTitle:'Morbius (film)'},
{ id:'madame-web', poster:'images/posters/madame-web.png', title:'Madame Web', year:2024, type:'Film', franchise:'sony', saga:'Sony\'s Spider-Man Universe', releaseOrder:9, chronoOrder:9, chronoNote:'2003', director:'S.J. Clarkson', cast:['Dakota Johnson','Sydney Sweeney','Isabela Merced'], duration:'116 min', synopsis:"Une ambulancière de New York développe des pouvoirs de précognition et se lance dans la protection de trois jeunes femmes qu'elle voit menacées.", wikiTitle:'Madame Web'},
{ id:'kraven', poster:'images/posters/kraven.jpg', title:'Kraven the Hunter', year:2024, type:'Film', franchise:'sony', saga:'Sony\'s Spider-Man Universe', releaseOrder:10, chronoOrder:10, chronoNote:'origine, plusieurs décennies', director:'J.C. Chandor', cast:['Aaron Taylor-Johnson','Russell Crowe','Ariana DeBose'], duration:'127 min', synopsis:"Sergei Kravinoff devient le chasseur le plus redouté du monde après une expérience surnaturelle qui décuple ses capacités.", wikiTitle:'Kraven the Hunter (film)'},
{ id:'venom-last-dance', poster:'images/posters/venom-last-dance.jpg', title:'Venom: The Last Dance', year:2024, type:'Film', franchise:'sony', saga:'Sony\'s Spider-Man Universe', releaseOrder:11, chronoOrder:11, chronoNote:'2024', director:'Kelly Marcel', cast:['Tom Hardy','Chiwetel Ejiofor','Juno Temple'], duration:'109 min', synopsis:"Traqués par les forces terrestres et un ennemi venu de la planète des symbiotes, Eddie et Venom vivent leur dernière danse.", wikiTitle:'Venom: The Last Dance'},
{ id:'spiderman-into-spiderverse', poster:'images/posters/spiderman-into-spiderverse.png', title:'Spider-Man: Into the Spider-Verse', year:2018, type:'Film', franchise:'sony', saga:'Spider-Verse (animation)', releaseOrder:12, chronoOrder:12, chronoNote:'2018 (Terre-1610)', director:'Bob Persichetti, Peter Ramsey, Rodney Rothman', cast:['Shameik Moore','Jake Johnson','Hailee Steinfeld','Mahershala Ali','Liev Schreiber'], duration:'117 min (animation)', synopsis:"Miles Morales, jeune lycéen de Brooklyn mordu par une araignée radioactive, doit apprendre à devenir Spider-Man aux côtés de variantes du héros venues d'autres dimensions.", wikiTitle:'Spider-Man: Into the Spider-Verse'},
{ id:'spiderman-across-spiderverse', poster:'images/posters/spiderman-across-spiderverse.jpg', title:'Spider-Man: Across the Spider-Verse', year:2023, type:'Film', franchise:'sony', saga:'Spider-Verse (animation)', releaseOrder:13, chronoOrder:13, chronoNote:'peu après le premier film', director:'Joaquim Dos Santos, Kemp Powers, Justin K. Thompson', cast:['Shameik Moore','Hailee Steinfeld','Jake Johnson','Oscar Isaac','Issa Rae'], duration:'140 min (animation)', synopsis:"Miles Morales est propulsé à travers le multivers et rencontre une société secrète de Spider-Héros, la Société de l'Araignée, dont les règles s'opposent radicalement à sa vision de l'héroïsme.", wikiTitle:'Spider-Man: Across the Spider-Verse'},
{ id:'spiderman-beyond-spiderverse', poster:'images/posters/spiderman-beyond-spiderverse.jpg', title:'Spider-Man: Beyond the Spider-Verse', year:2027, type:'Film', franchise:'sony', saga:'Spider-Verse (animation)', releaseOrder:14, chronoOrder:14, chronoNote:'suite directe', director:'Joaquim Dos Santos, Kemp Powers, Justin K. Thompson (attendu)', cast:['Shameik Moore','Hailee Steinfeld'], duration:'non communiquée', synopsis:"Conclusion annoncée de la trilogie Spider-Verse, plusieurs fois repoussée depuis 2024 — les réalisateurs assurent vouloir prendre le temps de faire de ce film la conclusion que la saga mérite.", wikiTitle:'Spider-Man: Beyond the Spider-Verse', upcoming:true},

// ------------------------------------------------------- PRÉ-MCU (classic) ---
{ id:'blade-1998', poster:'images/posters/blade-1998.jpg', title:'Blade', year:1998, type:'Film', franchise:'classic', saga:'Trilogie Blade', releaseOrder:1, chronoOrder:1, chronoNote:'1998', director:'Stephen Norrington', cast:['Wesley Snipes','Stephen Dorff','Kris Kristofferson',"N'Bushe Wright"], duration:'120 min', synopsis:"Mi-homme mi-vampire, Blade traque et extermine les vampires qui infestent les grandes villes, bien décidé à venger sa mère mordue avant sa naissance.", wikiTitle:'Blade (1998 film)'},
{ id:'blade-2', poster:'images/posters/blade-2.jpg', title:'Blade II', year:2002, type:'Film', franchise:'classic', saga:'Trilogie Blade', releaseOrder:2, chronoOrder:2, chronoNote:'2002', director:'Guillermo del Toro', cast:['Wesley Snipes','Kris Kristofferson','Ron Perlman','Leonor Varela'], duration:'117 min', synopsis:"Blade s'allie temporairement à ses ennemis vampires pour affronter une menace commune : les Reapers, une souche mutante et incontrôlable.", wikiTitle:'Blade II'},
{ id:'blade-trinity', poster:'images/posters/blade-trinity.jpg', title:'Blade: Trinity', year:2004, type:'Film', franchise:'classic', saga:'Trilogie Blade', releaseOrder:3, chronoOrder:3, chronoNote:'2004', director:'David S. Goyer', cast:['Wesley Snipes','Kris Kristofferson','Jessica Biel','Ryan Reynolds'], duration:'113 min', synopsis:"Traqué et accusé de meurtre, Blade doit s'allier à une nouvelle génération de chasseurs de vampires pour affronter Dracula lui-même, réveillé par ses ennemis.", wikiTitle:'Blade: Trinity'},
{ id:'daredevil-2003', poster:'images/posters/daredevil-2003.jpg', title:'Daredevil', year:2003, type:'Film', franchise:'classic', saga:'Daredevil / Elektra', releaseOrder:4, chronoOrder:4, chronoNote:'2003', director:'Mark Steven Johnson', cast:['Ben Affleck','Jennifer Garner','Colin Farrell','Michael Clarke Duncan'], duration:'103 min', synopsis:"Avocat aveugle de jour, justicier acrobate de nuit, Matt Murdock affronte le tueur à gages Bullseye et l'énigmatique Kingpin dans les rues de New York.", wikiTitle:'Daredevil (film)'},
{ id:'elektra-2005', poster:'images/posters/elektra-2005.jpg', title:'Elektra', year:2005, type:'Film', franchise:'classic', saga:'Daredevil / Elektra', releaseOrder:5, chronoOrder:5, chronoNote:'2005', director:'Rob Bowman', cast:['Jennifer Garner','Goran Višnjić','Kirsten Prout'], duration:'97 min', synopsis:"Ressuscitée après sa mort dans Daredevil, la tueuse à gages Elektra Natchios est chargée d'un contrat qui va la pousser à protéger, plutôt qu'éliminer, sa cible.", wikiTitle:'Elektra (2005 film)'},
{ id:'fantastic-four-2005', poster:'images/posters/fantastic-four-2005.jpg', title:'Fantastic Four', year:2005, type:'Film', franchise:'classic', saga:'Fantastic Four (Fox, années 2000)', releaseOrder:6, chronoOrder:6, chronoNote:'2005', director:'Tim Story', cast:['Ioan Gruffudd','Jessica Alba','Chris Evans','Michael Chiklis'], duration:'106 min', synopsis:"Une exposition à une tempête cosmique dote quatre astronautes de pouvoirs extraordinaires, qu'ils devront apprendre à maîtriser pour affronter leur ancien collègue devenu Docteur Fatalis.", wikiTitle:'Fantastic Four (2005 film)'},
{ id:'fantastic-four-silver-surfer', poster:'images/posters/fantastic-four-silver-surfer.jpg', title:'Fantastic Four: Rise of the Silver Surfer', year:2007, type:'Film', franchise:'classic', saga:'Fantastic Four (Fox, années 2000)', releaseOrder:7, chronoOrder:7, chronoNote:'2007', director:'Tim Story', cast:['Ioan Gruffudd','Jessica Alba','Chris Evans','Michael Chiklis','Doug Jones'], duration:'92 min', synopsis:"L'arrivée sur Terre du mystérieux Silver Surfer, héraut d'une menace planétaire nommée Galactus, contraint les Quatre Fantastiques à faire équipe avec Docteur Fatalis.", wikiTitle:'Fantastic Four: Rise of the Silver Surfer'},
{ id:'ghost-rider-2007', poster:'images/posters/ghost-rider-2007.jpg', title:'Ghost Rider', year:2007, type:'Film', franchise:'classic', saga:'Ghost Rider', releaseOrder:8, chronoOrder:8, chronoNote:'2007', director:'Mark Steven Johnson', cast:['Nicolas Cage','Eva Mendes','Wes Bentley'], duration:'114 min', synopsis:"Le cascadeur Johnny Blaze, ayant vendu son âme au diable, se transforme la nuit en Ghost Rider, un justicier au crâne enflammé chargé de traquer les âmes damnées.", wikiTitle:'Ghost Rider (2007 film)'},
{ id:'ghost-rider-spirit-vengeance', poster:'images/posters/ghost-rider-spirit-vengeance.jpg', title:'Ghost Rider: L\'Esprit de vengeance', year:2012, type:'Film', franchise:'classic', saga:'Ghost Rider', releaseOrder:9, chronoOrder:9, chronoNote:'2012', director:'Mark Neveldine, Brian Taylor', cast:['Nicolas Cage','Idris Elba','Violante Placido'], duration:'96 min', synopsis:"Réfugié en Europe de l'Est pour échapper à sa malédiction, Johnny Blaze est recruté par une secte pour protéger un jeune garçon convoité par le diable en personne.", wikiTitle:'Ghost Rider: Spirit of Vengeance'},
{ id:'punisher-2004', poster:'images/posters/punisher-2004.jpg', title:'The Punisher', year:2004, type:'Film', franchise:'classic', saga:'Punisher', releaseOrder:10, chronoOrder:10, chronoNote:'2004', director:'Jonathan Hensleigh', cast:['Thomas Jane','John Travolta','Rebecca Romijn'], duration:'124 min', synopsis:"Après le massacre de toute sa famille sur ordre d'un parrain de la mafia, l'agent du FBI Frank Castle abandonne tout pour devenir le Punisher et se venger méthodiquement.", wikiTitle:'The Punisher (2004 film)'},
{ id:'punisher-war-zone', poster:'images/posters/punisher-war-zone.jpg', title:'Punisher: War Zone', year:2008, type:'Film', franchise:'classic', saga:'Punisher', releaseOrder:11, chronoOrder:11, chronoNote:'2008 (reboot, non lié au film de 2004)', director:'Lexi Alexander', cast:['Ray Stevenson','Dominic West','Doug Hutchison'], duration:'107 min', synopsis:"Nouveau reboot du personnage : Frank Castle, devenu un redoutable justicier, doit affronter Jigsaw, un ancien mafieux défiguré bien décidé à se venger.", wikiTitle:'Punisher: War Zone'},
{ id:'fantastic-four-2015', poster:'images/posters/fantastic-four-2015.jpg', title:'Les 4 Fantastiques', year:2015, type:'Film', franchise:'classic', saga:'Fantastic Four (reboot 2015)', releaseOrder:12, chronoOrder:12, chronoNote:'2015 (continuité indépendante)', director:'Josh Trank', cast:['Miles Teller','Kate Mara','Michael B. Jordan','Jamie Bell'], duration:'100 min', synopsis:"Reboot sombre à la production chaotique : quatre jeunes scientifiques acquièrent des pouvoirs après un accident survenu lors d'un voyage vers une dimension parallèle.", wikiTitle:'Fantastic Four (2015 film)'},

];

// Libellés lisibles pour chaque franchise
const FRANCHISE_LABELS = {
  mcu: 'MCU',
  xmen: 'X-Men (Fox)',
  sony: 'Spider-Man (Sony)',
  netflix: 'Netflix',
  classic: 'Pré-MCU (1998-2015)'
};

// Pour l'onglet "MCU" de la page Chronologie : quelles franchises afficher
// ensemble sur la même échelle de chronoOrder (Netflix y est fusionné,
// conformément à l'ordre officiel Disney+). Les autres onglets restent
// filtrés sur leur seule franchise.
const CHRONO_GROUPS = {
  mcu: ['mcu', 'netflix'],
  xmen: ['xmen'],
  sony: ['sony'],
  netflix: ['netflix'],
  classic: ['classic']
};

const FRANCHISE_NOTES = {
  mcu: "Univers cinématographique Marvel porté par Marvel Studios depuis 2008. Cet ordre reproduit tel quel L'ORDRE CHRONOLOGIQUE OFFICIEL publié par Marvel/Disney+ (« See the Complete MCU Timeline on Disney+ », marvel.com, mis à jour le 02/06/2026) : films, séries, spéciaux ET les 5 courts-métrages « One-Shot » — et il entrelace désormais les séries Netflix (badge « Netflix » conservé sur chaque fiche). Les 5 derniers titres de la liste (Your Friendly Neighborhood Spider-Man, VisionQuest, Spider-Man: Brand New Day, Avengers: Doomsday, Avengers: Secret Wars) ne figurent pas encore dans le « Complete Timeline » officiel — soit parce qu'ils ne sont pas encore sortis au 22/08/2026, soit parce que leur statut de continuité (cas de la série animée) reste incertain — et sont donc placés à la suite par déduction.",
  xmen: "Continuité lancée par la Fox en 2000, largement indépendante du MCU jusqu'à sa fusion via Deadpool & Wolverine (2024). La chronologie interne est notoirement incohérente d'un film à l'autre (âges des personnages, événements contradictoires) : l'ordre proposé est celui généralement admis par les fans. X-Men '97, bien que produit par Marvel Animation, est une continuité animée à part — suite directe de la série des années 1990 — non reliée aux films : elle apparaît volontairement à la fin de la liste.",
  sony: "Univers cinématographique de Sony autour de Spider-Man : QUATRE blocs bien distincts et non reliés entre eux — la trilogie Raimi, la duologie Amazing, le « Sony's Spider-Man Universe » centré sur Venom, et la trilogie animée Spider-Verse (sa propre continuité multivers). L'ordre proposé suit la chronologie interne au sein de chaque bloc, dans l'ordre où les blocs sont apparus.",
  netflix: "Séries produites par Marvel Television pour Netflix (2015-2019), partageant un même univers new-yorkais culminant dans le crossover The Defenders. Officiellement, Disney+ les entrelace désormais avec les films du MCU (voir l'onglet MCU) ; cette vue isolée reprend le même ordre, mais filtré aux seules séries Netflix, pratique pour qui veut juste enchaîner le « coin » new-yorkais.",
  classic: "Avant même la création de Marvel Studios (2005), plusieurs héros Marvel ont eu droit à leurs propres films chez d'autres studios (New Line, 20th Century Fox, Sony/Columbia, Lionsgate/Artisan), sans aucun lien entre eux. Regroupés ici par commodité : ce sont en réalité une demi-douzaine de mini-continuités totalement indépendantes (Blade, Daredevil/Elektra, Fantastic Four 2005-2007, Ghost Rider, Punisher, et le reboot Fantastic Four de 2015)."
};
